### ISSUE TITLE
peoblem with /.configure on msys2_shell.bat

### ISSUE THREAD

**Issue by eslamih10** [telegramdesktop/tdesktop#1200]
when run the
$ ./configure --toolchain=msvc --disable-programs --disable-everything --enable-libopus --enable-decoder=aac --enable-decoder=aac_latm --enable-decoder=aasc --enable-decoder=mp1 --enable-decoder=mp1float --enable-decoder=mp2 --enable-decoder=mp2float --enable-decoder=mp3 --enable-decoder=mp3adu --enable-decoder=mp3adufloat --enable-decoder=mp3float --enable-decoder=mp3on4 --enable-decoder=mp3on4float --enable-decoder=wavpack --enable-decoder=opus --enable-decoder=vorbis --enable-decoder=wmalossless --enable-decoder=wmapro --enable-decoder=wmav1 --enable-decoder=wmav2 --enable-decoder=wmavoice --enable-decoder=flac --enable-encoder=libopus --enable-parser=aac --enable-parser=aac_latm --enable-parser=mpegaudio --enable-parser=opus --enable-parser=vorbis --enable-parser=flac --enable-demuxer=aac --enable-demuxer=wav --enable-demuxer=mp3 --enable-demuxer=ogg --enable-demuxer=mov --enable-demuxer=flac --enable-muxer=ogg --enable-muxer=opus --extra-ldflags="-libpath:/d/TBuild/Libraries/opus/win32/VS2010/Win32/Release celt.lib silk_common.lib silk_float.lib"
,i get the "cl is unable to create an executable file.
If cl is a cross-compiler, use the --enable-cross-compile option.
Only do this if you know what cross compiling means.
C compiler test failed." message.What is the problem?

**Comment by telegramdesktop** [comment]
You need to run the command:

PATH="/c/Program Files (x86)/Microsoft Visual Studio 12.0/VC/BIN:$PATH"

With exactly correct path to Visual C++ compiler BIN folder, check it in your msys2_shell.bat, like:

cd "/c/Program Files (x86)/Microsoft Visual Studio 12.0/VC/BIN" and see if it is correct.

**Comment by eslamih10** [comment]
my system cpu is 32 bit,i have not "Program Files (x86)" folder,i run the 
PATH="/c/Program Files/Microsoft Visual Studio 12.0/VC/BIN:$PATH"

**Comment by telegramdesktop** [comment]
It seems like "cl" from path still is not the right one. If you write:

cd "/c/Program Files/Microsoft Visual Studio 12.0/VC/BIN"
ls

is "cl.exe" there?

**Comment by eslamih10** [comment]
when run cl.exe,i get the 
Microsoft (R) C/C++ Optimizing Compiler Version 18.00.40629 for x86
Copyright (C) Microsoft Corporation.  All rights reserved.

usage: cl [ option... ] filename... [ /link linkoption... ]

**Comment by telegramdesktop** [comment]
Well, if you try to run ./configure in the same msys session, what does it tell?

**Comment by eslamih10** [comment]
My problem was solved,thanks

**Comment by auchri** [comment]
And how?

**Comment by eslamih10** [comment]
I did not run the "msys2_shell.bat"  file from VS2012 x86 Native Tools Command Prompt.

**Comment by gilsefidi** [comment]
hey , i have same problem , see full of commands .
but every thing work good !
and i still have this error :

cl is unable to create an executable file.
If cl is a cross-compiler, use the --enable-cross-compile option.
Only do this if you know what cross compiling means.
C compiler test failed.

If you think configure made a mistake, make sure you are using the latest
version from Git.  If the latest version fails, report the problem to the
ffmpeg-user@ffmpeg.org mailing list or IRC #ffmpeg on irc.freenode.net.
Include the log file "config.log" produced by configure as this will help
solve the problem.

**Comment by gilsefidi** [comment]
LINK : fatal error LNK1181: cannot open input file 'silk_float.lib'
i found this in log file

**Comment by JimmyS83** [comment]
## Visual Studio 2015 Community Edition:
hit the same problem, running msys2_shell.cmd from _MSBuild Command Prompt for VS2015_ gave me exact same result.

Make sure you are running it from _**Developer Command Prompt for VS2015**_. I assume this is analogy of Native shell from full edition.
