### ISSUE TITLE
Graphic accents  in vocals (èéàú...) do not appear 

### ISSUE THREAD

**Issue by plagasul** [telegramdesktop/tdesktop#1360]
I am on Telegram Desktop 0.9.10 under Linux Mint 17.2 Rafaela Cinnamon

Spanish/catalan graphic accents on vocals, such as é è ú.... but also ü, etc, are simply not written when writing a message. They are not shown on text input, and neither when the message is sent and appears in the shared part of the screen.

Graphic accents work without any problem in any other part of the system, without exceptions, at least that I come accross.

Thank you

**Comment by auchri** [comment]
Works on windows
![image](https://cloud.githubusercontent.com/assets/5092164/11567376/1a0ab5a4-99e7-11e5-92b8-60139d6c6970.png)

**Comment by z3ntu** [comment]
![selection_010](https://cloud.githubusercontent.com/assets/3768500/11653729/7090562e-9da0-11e5-8cd2-fb684562329d.png)
Works in Ubuntu 15.10

**Comment by psergiojr** [comment]
Here on Telegram 0.9.15 under Ubuntu 14.04 LTS

I've noticed this too. But it only happens after some time. Right after opening the window, it works perfectly. I keep it opened while doing anything else with another program, and then back to the Telegram window, accents do not appear anymore.

If I close the window, then reopen it from the tray icon, it still doesn't work. But if I change the keyboard layout to any other language (here between pt-BR and en-US) and then back, it works again. *Just to stop working again after some time :)*

**Comment by psergiojr** [comment]
Testing now, I found something strange. When switching between windows using the mouse, it works perfectly. But when switching using **Alt+Tab** the accents stop working.

**Comment by psergiojr** [comment]
If it helps tracking the problem: I was testing in Manjaro, and the problem doesn't happen here. Even the *Alt+Tab* works fine with accents. XFCE 4.12

**Comment by Crashillo** [comment]
Problem persists. Telegram just ignores accent keys.

xfce4-about 4.11.1 (Xfce 4.10)
VERSION="14.04.4 LTS, Trusty Tahr"
Telegram Desktop: v 0.9.49

**Comment by Contraculto** [comment]
I also have this problem.
In XFCE 4.12 over Ubuntu 16.04 accented characters don't work, they're simply ignored.
It works perfectly if I switch to Gnome.
Telegram version is 0.9.49, but I have at least a few times in the last couple of weeks.

**Comment by z3ntu** [comment]
Apparently this is a XFCE-only problem (works with i3wm).

**Comment by Rom4nB** [comment]
Same behaviour here. Any dead keys, i.e. accents as well, don't work on Telegram Desktop.

**Operating System**
Ubuntu 16.04 64-bit

**Telegram Desktop Version**
0.9.49

**Comment by z3ntu** [comment]
@Rom4nB what Desktop environment are you using?

**Comment by Rom4nB** [comment]
I use the standard Unity 7 Desktop environment of Ubuntu 16.04.

Unity Version 7.4.0

Am 07.06.2016 um 13:41 schrieb Luca Weiss:

**Comment by z3ntu** [comment]
@auchri @john-preston I compiled a list where it worked and where it didn't:  https://github.com/telegramdesktop/tdesktop/issues/1360#issuecomment-224034232

**Comment by soadroxs** [comment]
Not working here either.

XFCE 4.12
Xubuntu 16.04
Telegram 0.9.49

**Comment by Patola** [comment]
Working in one computer (Ubuntu 16.04 64 bits with NVidia and Unity), not working in another (same configuration). First computer uses abnt2 brazilian portuguese layout for accents, second one does not. Tested in both with dead keys and non-dead keys (composed letters), same thing, in the first it works, in the second it does not.

**Comment by luccamendonca** [comment]
Doesn't work here either

XFCE 4.1
Xubuntu 15.10
Linux 4.4.4-040404-generic
Telegram 0.9.51

**Comment by rcotrina94** [comment]
+1 Doesn't work here either

GNOME Shell 3.16.4
Ubuntu GNOME 15.10
GNU/Linux 4.2.0-36-generic 
Telegram 0.9.51

**Comment by z3ntu** [comment]
**PLEASE! If you write, that it doesn't work for you, please also write what keyboard layout you are using! I am pretty sure, that it isn't because of a desktop environment/window manager, but because of the "special" keyboard layout you are using.**

**Comment by ByScripts** [comment]
Same problem here with dead keys.

Keyboard layout: "Français (Variante)" (AZERTY)

For the moment, I don't have problem with accented letters (éàù...), only with composition (^ ¨ ...)

```
rules:      evdev
model:      pc105
layout:     fr,us,fr
variant:    oss,,oss
```

**Comment by plagasul** [comment]
I initiated this thread, I've noticed the following message on the terminal when updating telegram that I believe may be related, at least in my case, to the problem at hand:

```
Configurando telegram (0.9.50-0ubuntu0) ...
Telegram/
Telegram/Updater
Telegram/Telegram
Configurando kpartx (0.4.9-3ubuntu7.13) ...
Configurando kpartx-boot (0.4.9-3ubuntu7.13) ...
update-initramfs: deferring update (trigger activated)
Processing triggers for menu (2.1.46ubuntu1) ...
Processing triggers for initramfs-tools (0.103ubuntu4.3) ...
update-initramfs: Generating /boot/initrd.img-3.19.0-32-generic
Warning: No support for locale: es_ES.utf8

```

**Comment by z3ntu** [comment]
@plagasul is the language uncommented in your `/etc/locale.conf`? If not, uncomment it and run `locale-gen`. (I don't know if this works on Ubuntu, but it works on Arch Linux so try it)

**Comment by plagasul** [comment]
@z3ntu, there is a etc/locale.alias with a "spanish es_ES.ISO-8859-1" line, uncommented, I run locale-gen, shutdown and up Telegram, but nothing particular happened, graphic accents still not visible. Thanks. Any other ideas?

**Comment by plagasul** [comment]
I tried reinstalling telegram and got this:

`perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_TIME = "es_ES.UTF-8",
	LC_MONETARY = "es_ES.UTF-8",
	LC_ADDRESS = "es_ES.UTF-8",
	LC_TELEPHONE = "es_ES.UTF-8",
	LC_NAME = "es_ES.UTF-8",
	LC_MEASUREMENT = "es_ES.UTF-8",
	LC_IDENTIFICATION = "es_ES.UTF-8",
	LC_NUMERIC = "es_ES.UTF-8",
	LC_PAPER = "es_ES.UTF-8",
	LANG = "es_ES.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
locale: Cannot set LC_CTYPE to default locale: No such file or directory
locale: Cannot set LC_MESSAGES to default locale: No such file or directory
locale: Cannot set LC_ALL to default locale: No such file or directory
Selecting previously unselected package telegram.
(Reading database ... 286519 files and directories currently installed.)
Preparing to unpack .../telegram_0.9.50-0ubuntu0_amd64.deb ...
Unpacking telegram (0.9.50-0ubuntu0) ...
Processing triggers for bamfdaemon (0.5.1+14.04.20140409-0ubuntu1) ...
Rebuilding /usr/share/applications/bamf-2.index...
Processing triggers for gnome-menus (3.10.1-0ubuntu2) ...
Processing triggers for desktop-file-utils (0.22-1ubuntu1) ...
Processing triggers for mime-support (3.54ubuntu1.1) ...
Setting up telegram (0.9.50-0ubuntu0) ...
Telegram/
Telegram/Updater
`

**Comment by XyLoNaMiyX** [comment]
Not working here either. It's strange, because in other operative systems (Linux Mint 17.3 Rosa featuring XFCE desktop) I could type on the chat input with those characters, but not on the photos. I had to use Alt+Tab.

Now under Xubuntu 16.04 with the latest Telegram version as of now (0.9.56) is still **not** working, anywhere. My keyboard is _Generic PC 105 keys (intl), Spanish (Windows keys)_

**Comment by john-preston** [comment]
@XyLoNaMiyX Can you try in other systems (where the chat input was working, but not the photo caption input) does photo caption input now work?

**Comment by XyLoNaMiyX** [comment]
Yeah, on Linux Mint 17.3 Rosa featuring XFCE desktop it works now (ran it on a Virtual Machine setting the Spanish keyboard, not Windows layout though), both on chat input and photo captions.

However, thinking the issue could be the Windows layout part, I switched to "plain" Spanish layout on Xubuntu, and it doesn't work there (not in the chat input, not in the photo captions)

**Comment by camilacampos** [comment]
not working on my ubuntu 14.04 LTS either. keyboard is qwerty for brazilian portuguese. The accents work fine when I first start telegram desktop, and sometime later it stops working. I have to close it and open again, or re-select my keyboard settings, then the accents start working again ):

**Comment by camilosampedro** [comment]
I managed to solve this in Manjaro Budgie 16.06 by adding these lines to my `~/.xinitrx` (or `~/.xprofile` depending on the Window Manager):

```
export GTK_IM_MODULE=ibus
export XMODIFIERS=@im=ibus
export QT_IM_MODULE=ibus
ibus-daemon -drx
```

Check if you have ibus installed on your system.

**Comment by rcotrina94** [comment]
@camilosampedro It worked for me. Thanks!

**Comment by XyLoNaMiyX** [comment]
@camilosampedro in my case, I only had to `sudo apt-get install ibus` and set it up in `Configuration`, but it's working now. Thanks for the hint

**Comment by rafaelcn** [comment]
Confirmed here, Xubuntu 16.04 using the Portuguese (Brazil) layout. Also, in previous versions of Telegram sign accents worked like a charm, not sure though in which version this bug has appeared, since it has stopped working I've been using the web version of telegram.

**Comment by plagasul** [comment]
After installing Linux Mint Sarah, Cinnamon, I have graphical accents.

**Comment by successus100** [comment]
@XyLoNaMiyX Thanks, solved with the same on Xubuntu 16.04, sudo apt install ibus, and sep up on language options and reboot.

**Comment by douglasrizzo** [comment]
@rafaelcn my case is exactly the same as yours.

**Comment by brwolfgang** [comment]
Just noticed: 10 months already...

**Comment by douglasrizzo** [comment]
I found out that the workaround proposed by @narcelio on #1041 works for me.

**Comment by brwolfgang** [comment]
@douglasrizzo works here too, I can now leave the web version alone, thanks

**Comment by rafaelcn** [comment]
Well, I just changed the desktop that I use (to KDE), since then I have no complaints regarding telegram. Either way, as you said the problem is still not solved on Xubuntu.

--
Regards,
Rafael Campos Nunes.
rafaelnunes@engineer.com

**Comment by vs0uz4** [comment]
For those who are using distros like Elementary OS, just edit the file telegramdesktop.desktop, and remove the first line of the [Desktop Entry] that force you to use UTF-8, that way here worked perfectly accents.

Replace "USERNAME" at login your user

```
[Desktop Entry]
Version=1.0
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
Exec=/home/USERNAME/Downloads/Telegram/Telegram -- %u
Icon=telegram
Terminal=false
StartupWMClass=Telegram
Type=Application
Categories=Network;
MimeType=x-scheme-handler/tg;
X-Desktop-File-Install-Version=0.22
```

**Comment by luismanolo** [comment]
First, sorry about my english... ;-)

Thanks to  @vs0uz4 for the solution, but don't work for me.

This is my modification...

create a file in /home/USERNAME/bin/TG.sh with:

```
#!/bin/bash
QT_IM_MODULE=xim /home/USERNAME/Telegram/Telegram
```

then: chmod +x /home/USERNAME/bin/TG.sh

And finally change the file: /home/USERNAME/.local/share/applications/telegramdesktop.desktop with:

```
[Desktop Entry]
Version=1.0
Name=Telegram Desktop
Comment=Official desktop version of Telegram messaging app
Exec=/home/USERNAME/bin/TG.sh
Icon=telegram
Terminal=false
StartupWMClass=Telegram
Type=Application
Categories=Network;
MimeType=x-scheme-handler/tg;
X-Desktop-File-Install-Version=0.22
```

This work for me.

**Comment by XyLoNaMiyX** [comment]
Thanks @luismanolo, I was having the issue again and I didn't want to bother with `ibus` xD

**Comment by stek29** [comment]
@luismanolo @XyLoNaMiyX Why not do `Exec=QT_IM_MODULE=xim /home/USERNAME/Telegram/Telegram`? or with `eval` if it won't work.

**Comment by XyLoNaMiyX** [comment]
@stek29 `Exec=QT_IM_MODULE=xim /home/USERNAME/Telegram/Telegram` fails. I don't know where to put `eval`, and with `env` it didn't work for me either.

**Comment by Aokromes** [comment]
#1041 ?

**Comment by stek29** [comment]
@XyLoNaMiyX oh, i meant `env`, huh.

**Comment by douglasrizzo** [comment]
When I alter the `.desktop` file that fires up Telegram (like @XyLoNaMiyX mentions), sometimes it reverts back to its original state. I don't know if it is related to Telegram updates. However, if I create my own `.desktop` file in some other directory, like `~/.local/autostart`, I am able to keep the custom Exec command.

**Comment by realjumy** [comment]
Also having problems with elementaryOS:

> $ setxkbmap -query
> rules:      evdev
> model:      pc105
> layout:     es,us
> variant:    ,
> options:    grp:alt_shift_toggle
>

**Comment by luismanolo** [comment]
You can put this on your .profile

export  QT_IM_MODULE=xim

**Comment by revagomes** [comment]
@realjumy I've fixed that by running `$ ibus-setup`. But just runing the config this way is not enough because it didn't work after restarting the machine, for example. I'll try some of the other suggestions anyway. but at least there is another workaround.

**Comment by luiars** [comment]
This works for me on elementary OS 0.3 and 0.4

You should have **ibus-unikey** installed, if you don't do it with this command:

`sudo apt-get install ibus-unikey`

Now configure ibus through `ibus-setup`. To do this, run the command on a terminal and go to the input method tab.

1. Install your desired input method for **IBus**.
2. Run `ibus-setup` command from **terminal**.
3. Select 'Input method' tab and **Add** your desired input method.
4. Close 'IBus Setup' and run `ibus-daemon -drx` in **terminal**.

**Comment by jesusgn90** [comment]
The @luiarhs solution works for me, Ubuntu 16.04, Spanish Spain, 64 bits

**Comment by mfrasca** [comment]
but why was the issues closed while we only have a workaround?  
shouldn't it be closed after it's solved in the distributed software?

**Comment by Selhar** [comment]
Had no problems on fedora 25, changed to fedora 27 and had to do the workaround.

**Comment by mikaelmello** [comment]
Happened to me on Elementary OS 0.4.1, @luiarhs solution worked for me.

**Comment by Henriquelay** [comment]
Confirmed, @luiarhs working on elementary OS 0.4.1, Telegram 1.2.17

**Comment by mateusdeap** [comment]
Tried @luiarhs workaround on Ubuntu MATE 18.04 and Telegram 1.2.17, but it did not work at all.

**Comment by mfrasca** [comment]
@auchri , you closed this issue as a duplicate, but you didn't mention of which issue this is a duplicate.

**Comment by Lonami** [comment]
@mfrasca, @Aokromes mentioned #1041 [above](https://github.com/telegramdesktop/tdesktop/issues/1360#issuecomment-258892430).

**Comment by vegbrasil** [comment]
Before 1.3, `export QT_IM_MODULE=xim` used to work fine (except for `ç`). After the update, no special characters work, even with the IBus workaround.

Using Linux Mate with English (US, international with dead keys) working fine everywhere else.

**Comment by mateusdeap** [comment]
I have the same setup as @vegbrasil concerning OS (mine being version 18.04, just to be specific) and keyboard. The only way I got it to work was downloading directly from the telegram site. Neither the snap package or the installations available in the ubuntu store or Mate Boutique work.

**Comment by mfrasca** [comment]
then maybe better invite followup on #1041 
adding comments on a closed issue will not have much impact

**Comment by Sjmuniz** [comment]
I've found a "fix". The problem seems to be related to the Input Method.
From 
https://bugs.launchpad.net/elementaryos/+bug/1630241
I've created a shell script to start telegram:
$ cat bin/telegram.sh 
export QT_IM_MODULE=xim
cd $HOME/Downloads/Telegram
./Telegram &
to comply with the maintainer requests I am using US international with dead keys distribution.
However it is odd that even when I have no IM method configured, and defaults to XIM, I need to pass this variable in order to inform QT I am using XIM.

 smuniz@d630:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.5 LTS
Release:	16.04
Codename:	xenial
using 
smuniz@d630:~/Downloads/Telegram$ cat ~/.xinputrc
# im-config(8) generated on Mon, 26 Feb 2018 03:55:41 -0300
run_im none
# im-config signature: 047389d2485e586bf71ebb0c8d18fa12  -
smuniz@d630:~/Downloads/Telegram$ im-config -l
 xim
smuniz@d630:~/Downloads/Telegram$ im-config -m
default
none
none

none

Regards.

**Comment by Selhar** [comment]
Still happens in fedora 29.

**Comment by JDevezas** [comment]
Having this same issue on Ubuntu 18.04 although it only started to happen one day or two after the installation (not entirely sure on this).

The keyboard layout is portuguese (PT) as well as the language itself.

Installed Telegram through the "Ubuntu Software" app

**Comment by Henriquelay** [comment]
I fixed by download through the Telegram Desktop site link. The one I was using (trough software center) wasn't even updated to 1.4.x

**Comment by vmgustavo** [comment]
I had the same problem here when installed using Snap. I installed from the Telegram Desktop [website](https://desktop.telegram.org/) and the problem is gone.

**Comment by Lukaszz10** [comment]
Happened to me on Elementary OS Juno, telegram installed from the Telegram Desktop Website, @luiarhs solution still working.

**Comment by LawfulHacker** [comment]
This can be solved for the Snap on Ubuntu, setting the `QT_IM_MODULE` environment variable to xim.

This can be done editing the `/var/lib/snapd/desktop/applications/telegram-desktop_telegramdesktop.desktop` file.

Change the line:

```
Exec=env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/telegram-desktop_telegramdesktop.desktop /snap/bin/telegram-desktop -- %u
```

to

```
Exec=env QT_IM_MODULE=xim env BAMF_DESKTOP_FILE_HINT=/var/lib/snapd/desktop/applications/telegram-desktop_telegramdesktop.desktop /snap/bin/telegram-desktop -- %u
```

**Comment by mazulo** [comment]
I was having this issue and tried a *LOT* of things, like rebuild my locale, running with `QT_IM_MODULE=xim`, installing `ibus` and making some adjustments to its preferences, install the official package from telegram.org but nothing worked. I was still getting these weird chars instead of accents: ![Screenshot from 2019-07-04 20-41-23](https://user-images.githubusercontent.com/1661112/60690241-1ff8da00-9e9c-11e9-8fd2-8989ec55e811.png)
 > it was supposed to be: `e num é que é memo`

By the end what solved, for whatever reason, was to uninstall the package (installed by `yay -S telegram-desktop-bin`) and install again with `sudo pacman -S telegram-desktop`

**Comment by fbfdsouza** [comment]
people, you can follow the steps from this video: https://www.youtube.com/watch?v=slbdgsae3Bo

**Comment by ks7000** [comment]
Tested on Ubuntu 18.04.3 LTS: all OK! (iBus installed and configured).

**Comment by arimourao** [comment]
Unfortunately, this is still an issue! I'm on Kubuntu 19.10 on a Portuguese ABNT keyboard. No accents at all. Please reopen this issue, this is still affecting many people. I'm currently using the version 1.8.15.

**Comment by JimmyOlano** [comment]
> Unfortunately, this is still an issue! I'm on Kubuntu 19.10 on a Portuguese ABNT keyboard. No accents at all. Please reopen this issue, this is still affecting many people. I'm currently using the version 1.8.15.

Español: Yo escribí un artículo al respecto, en castellano

Português: Eu escrevi um artigo sobre isso, em espanhol.

English: I wrote an article about it, in Spanish.

https://colaboratorio.net/jimmy/program/2019/configurando-ibus-telegram-ubuntu-18/

**Comment by clxjaguar** [comment]
I also have this problem, in 2020. The alt-tab / click on window methods of switching programs is doing a difference also for me.

**Comment by Selhar** [comment]
This still happens and needs the ibus workaround. No other application has this issue. I only have one keyboard layout in my system.
