### ISSUE TITLE
Telegram can't run natively on Wayland

### ISSUE THREAD

**Issue by bugaevc** [telegramdesktop/tdesktop#2353]
### Steps to reproduce
1. Launch Telegram Desktop under a Wayland session.
2. Use any method to see if it's running via XWayland or on Wayland natively, e.g. [this one](https://medium.com/@bugaevc/how-to-easily-determine-if-an-app-runs-on-xwayland-or-on-wayland-natively-8191b506ab9a#.1cz6e64aq).
### Expected behaviour

Telegram should use Wayland natively, as Qt supports Wayland backend.
### Actual behaviour

Telegram uses X, so it has to be forwarded via XWayland, which causes performance and compatibility issues.
### Configuration

**Operating system:** Fedora 24, GNOME on Wayland session

**Version of Telegram Desktop:** 0.10.1
### Logs

Manually asking Telegram to run on Wayland results in an error:

```
$ QT_QPA_PLATFORM=wayland-egl /opt/telegram/Telegram 
This application failed to start because it could not find or load the Qt platform plugin "wayland-egl"
in "".

Available platform plugins are: xcb.

Reinstalling the application may fix this problem.
<traceback>
```

Suggesting that the bundled Qt is only built with X support.

Relevant Qt docs: https://wiki.qt.io/QtWayland

**Comment by bugaevc** [comment]
Related to #2255

**Comment by stek29** [comment]
Can you try to build it including QtWayland? Would it work then?

**Comment by bugaevc** [comment]
I don't dare -- [the instructions](https://github.com/telegramdesktop/tdesktop/blob/master/doc/building-qmake.md) are truly horrendous (I wish it would just be `./configure && make && make install`). Whoever does Linux builds should (try to) do it.

Also, I _suspect_ Qt Wiki is out-of-date and Qt5 now supports Wayland by default -- but somehow Telegram is still built without Wayland support.

cc @auchri

**Comment by stek29** [comment]
It supports it, but you should "enable" it by linking.

**Comment by stek29** [comment]
#2255 related btw
Also, I think someone should try to build it with and without wayland to see if size difference isn't much

**Comment by bugaevc** [comment]
> #2255 related btw

Yep, that's what I said in my second message ;)

> Also, I think someone should try to build it with and without wayland to see if size difference isn't much

Please, please, do!

**Comment by subdiff** [comment]
Is there some progress being made in the last months? Still can't run the binary from webpage on KDE Wayland. Needs to be compiled with the "wayland" plugin.

Terminal output:
```This application failed to start because it could not find or load the Qt platform plugin "wayland"
in "".

Available platform plugins are: xcb.

**Comment by Germano0** [comment]
Very useful workaround https://github.com/telegramdesktop/tdesktop/issues/2255#issuecomment-272303275

**Comment by bugaevc** [comment]
I can't see why the workaround is even necessary -- Telegram works with XWayland just fine. This issue is about it lacking _native_ Wayland support.

**Comment by Germano0** [comment]
@bugaevc I am using upstream Telegram on KDE Plasma 5.9.4 and the workaround is the first stuff I have found out that lets me use Telegram

**Comment by bugaevc** [comment]
@Germano0 Wayland support in KDE Plasma is not stable yet, so if X apps don't run properly it's Plasma's or distro's issue, not Telegram's -- you better report it to them.

**Comment by Germano0** [comment]
@bugaevc Ok

**Comment by davidedmundson** [comment]
@Germano0 Wayland support in KDE Plasma is not stable yet, so if X apps don't run properly it's Plasma's or distro's issue, not Telegram's -- you better report it to them.

That would be our fault, and I'd be happy for someone to report what those issues actually are to KDE.
"performance and compatibility issues." is not specific enough.

The crash (https://github.com/telegramdesktop/tdesktop/issues/2255) however, is not Plasma's doing.

It shows that your app is trying to load a plugin, and then failing. That's either you, Qt or packaging - but definitely not Plasma. 
Do you bundle Qt? If so it looks like you're also loading the system's plugins, so it finds something but it's not ABI compatiable.

**Comment by raneon** [comment]
Any progress to run Telegram natively on Wayland?

**Comment by bugaevc** [comment]
Update: Today I learned that there is https://github.com/xvitaly/tgbuild. Moreover, there is `telegram-desktop` package in RPM Fusion that is not only easier to install (in fact, that's what Fedy now uses), but it also integrates way better with the rest of the system. In particular, it uses the native system libraries, including Qt, not the bundled & patched copy.

While the version of Qt that Fedora uses does support Wayland (try `QT_QPA_PLATFORM=wayland telegram-desktop`), the experience is quite poor (there are rendering and theming artefacts and more). This is probably why Qt is configured to use X11 by default.

Those are Qt/Fedora issues, but considering that the upcoming Ubuntu 17.10 will use Wayland by default, it should make sense for Telegram developers to ensure their bundled version of Qt works well on Wayland, too.

(By the way, is Telegram really supposed to be built on Ubuntu 12.04? That would be like still using XCode 4 on OS X Mountain Lion)

**Comment by john-preston** [comment]
@bugaevc For Linux I build on the minimal version I support. For macOS I know a way to build Telegram Desktop on macOS 10.12.6 using Xcode 8.3.3 so that it runs on 64bit OS X 10.6.8 - but when I tried to build Telegram Desktop on Ubuntu 14.04 and then launch on Ubuntu 12.04 I've got some binary incompatibility with available glibc version =(

If someone will show me how to build Telegram Desktop on Ubuntu 16.04 that will run without any additional dependencies on Ubuntu 12.04 I'll gladly switch.

**Comment by ziggy42** [comment]
Are you sure you want to continue to support a 5 year old version of ubuntu? It's not even supported by Canonical anymore (unless you pay for it).

**Comment by john-preston** [comment]
@ziggy42 The building will be done on Ubuntu 14.04, launching will still be supported for some time on the old version as well.

**Comment by rburchell** [comment]
It might be interesting to some people to know about http://github.com/CrimsonAS/gtkplatform/ which allows for running Qt applications using gtk+ as a "host" (for window management, input events etc). This means that there's no need for xwayaldn in this picture.

One of the applications I wrote this for was actually Telegram Desktop, run via the Fedora packages, so I know it works pretty well.

**Comment by ziggy42** [comment]
Any updates on this?

**Comment by fenris** [comment]
any update on this? as KDE Plasma 5.12 Beta already supported Wayland ... 
https://paste.ubuntu.com/26397953/

**Comment by gbcox** [comment]
OK, it's 2018 now and Wayland is default in F28 KDE.  I'm receiving:

./Telegram 
This application failed to start because it could not find or load the Qt platform plugin "wayland"
in "".

Available platform plugins are: xcb.

The workaround is to install the package from the RPM Fusion repository - but now that Wayland is now becoming mainstream in Plasma, don't you folks think it's time to fix this build?

**Comment by HaoZeke** [comment]
QT's wayland is pretty unusable with sway. My notifications literally pop up in a new split, making it much worse than `xwayland`.

**Comment by nortexoid** [comment]
Waiting anxiously (for years) for Telegram linux to run natively in a wayland session. Wayland is now very usable on the top two DEs (gnome and kde plasma), and it woudl be nice to do without xwayland if possible. One can of course run the web client, but persistent tray notification are pretty essential for a chat client.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5180#issuecomment-423763413 states it already runs natively in a wayland session.

**Comment by Johnnynator** [comment]
@Aokromes He was not talking about the official binary but about the one shipped by certain linux distributions. This issues is about the binary that is compiled with the internal qt. Therefore both issues are unrelated.

**Comment by mateodif** [comment]
GNOME is getting closer and closer to having Wayland as a default. Is there any update on this? As far as I know, Qt supports Wayland natively and it shouldn't be hard to get it working.

**Comment by bugaevc** [comment]
> GNOME is getting closer and closer to having Wayland as a default.

GNOME has already defaulted to Wayland for many releases. Ubuntu still ships the X.Org session by default though.

**Comment by jonleighton** [comment]
I'm on Fedora 30. Installed `telegram-desktop` from RPMFusion and launching via `QT_QPA_PLATFORM=wayland /usr/bin/telegram-desktop` seems to work well. I don't know a way to make this happen automatically though.

**Comment by HaoZeke** [comment]
Have you tried the xeyes test? 


________________________________

**Comment by bugaevc** [comment]
Indeed, the Telegram packaged by distros uses the system version of Qt that supports Wayland (see [my comment above](https://github.com/telegramdesktop/tdesktop/issues/2353#issuecomment-324627599)). This issue is about the build of Telegram distributed by the upstream, with the bundled Qt.

**Comment by nortexoid** [comment]
It doesn't depend on whether the version of qt the distro ships supports wayland. It depends on how they build their telegram-desktop package. E.g., the arch package does not support wayland. If you run QT_QPA_PLATFORM=wayland /usr/bin/telegram-desktop you get back:
```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
```

**Comment by Johnnynator** [comment]
> It doesn't depend on whether the version of qt the distro ships supports wayland. It depends on how they build their telegram-desktop package. E.g., the arch package does not support wayland. If you run QT_QPA_PLATFORM=wayland /usr/bin/telegram-desktop you get back:
> 
> ```
> Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
> qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
> ```

@nortexoid Do you have `qt5-wayland` installed? It does not get pulled in by default.

**Comment by nortexoid** [comment]
> > It doesn't depend on whether the version of qt the distro ships supports wayland. It depends on how they build their telegram-desktop package. E.g., the arch package does not support wayland. If you run QT_QPA_PLATFORM=wayland /usr/bin/telegram-desktop you get back:
> > ```
> > Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
> > qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
> > This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> > 
> > Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
> > ```
> 
> @nortexoid Do you have `qt5-wayland` installed? It does not get pulled in by default. `telegram-desktop` on Arch should work on wayland once you have this installed.

I did not! Thanks for the tip. However, after installing qt5-wayland and running `QT_QPA_PLATFORM=wayland /usr/bin/telegram-desktop`, telegram is still using X as confirmed by using xprop on its window.

**Comment by nortexoid** [comment]
> > > It doesn't depend on whether the version of qt the distro ships supports wayland. It depends on how they build their telegram-desktop package. E.g., the arch package does not support wayland. If you run QT_QPA_PLATFORM=wayland /usr/bin/telegram-desktop you get back:
> > > ```
> > > Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
> > > qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
> > > This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> > > 
> > > Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.
> > > ```
> > 
> > 
> > @nortexoid Do you have `qt5-wayland` installed? It does not get pulled in by default. `telegram-desktop` on Arch should work on wayland once you have this installed.
> 
> I did not! Thanks for the tip. However, after installing qt5-wayland and running `QT_QPA_PLATFORM=wayland /usr/bin/telegram-desktop`, telegram is still using X as confirmed by using xprop on its window.

No, sorry, it does work. Telegram was running in the background when I tried to force wayland.

**Comment by jonleighton** [comment]
Even if it does work on a given platform via `QT_QPA_PLATFORM=wayland /usr/bin/telegram-desktop`, this is a pretty inconvenient way to launch Telegram. It seems to me that it should 'just work', i.e. automatically use Wayland when I am running Wayland. Is this something that needs to be addressed by the tdesktop project, or the distro packagers?

**Comment by jhasse** [comment]
Qt's wayland backend isn't feature complete and GNOME doesn't support server-side decorations on Wayland, so making it the default wouldn't be a good idea just yet.

**Comment by bugaevc** [comment]
> and GNOME doesn't support server-side decorations on Wayland, so making it the default wouldn't be a good idea just yet.

I fail to see how these are related. Yes, on GNOME, and generally on Wayland by default, Qt uses client-side decorations. How is that a reason not to ship Wayland support by default?

**Comment by bugaevc** [comment]
>  It seems to me that it should 'just work', i.e. automatically use Wayland when I am running Wayland. Is this something that needs to be addressed by the tdesktop project, or the distro packagers?

For the Telegram version you've got from the distro, it's up to the distro packagers — perhaps they feel Qt Wayland support is not stable enough yet. For the upstream Telegram Linux builds (https://desktop.telegram.org), it's up to the upstream Telegram developers to build the bundled Qt with Wayland support and perhaps make it the default.

**Comment by nortexoid** [comment]
> > It seems to me that it should 'just work', i.e. automatically use Wayland when I am running Wayland. Is this something that needs to be addressed by the tdesktop project, or the distro packagers?
> 
> For the Telegram version you've got from the distro, it's up to the distro packagers — perhaps they feel Qt Wayland support is not stable enough yet. For the upstream Telegram Linux builds (https://desktop.telegram.org), it's up to the upstream Telegram developers to build the bundled Qt with Wayland support and perhaps make it the default.

Qt now supports fallback platforms, e.g. `QT_QPA_PLATFORM="wayland;xcb"` will default to wayland but fall back to xcb if needed. So defaulting to wayland while providing xcb as fallback would incur no cost.

**Comment by john-preston** [comment]
@nortexoid Will it work fine with wayland platform plugin from Qt 5.6.2? 🙈

**Comment by nortexoid** [comment]
> @nortexoid Will it work fine with wayland platform plugin from Qt 5.6.2? see_no_evil

Unfortunately not. It's new to qt 5.11: [see here.](https://blog.qt.io/blog/2018/05/29/whats-new-in-qt-5-11-for-the-wayland-platform-plugin/)

**Comment by noamcore** [comment]
Tried to build on my Gentoo without success xD

The issue is from 2016, any plans to upgrade the Qt version?

**Comment by jonleighton** [comment]
> QT's wayland is pretty unusable with sway. My notifications literally pop up in a new split, making it much worse than `xwayland`.

I had this issue with sway too. I just discovered there's a checkbox in Telegram's settings called 'Use native notifications' -- turning that on solves this.

**Comment by Aokromes** [comment]
@noamcore on september preston will deprecate windows xp and more old OSs and that will allow to upgrade QT.

**Comment by vvrein** [comment]
For Arch Linux users:  
https://wiki.archlinux.org/index.php/Telegram#Wayland_support

**Comment by Aokromes** [comment]
telegram desktop is using now updated QT, this bug must be fixed now.

**Comment by Johnnynator** [comment]
> telegram desktop is using now updated QT, this bug must be fixed now.

No, telegram's Qt build has Wayland disabled.

**Comment by Aokromes** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7105#issuecomment-579832159

**Comment by c-thun** [comment]
The Flatpak builds still cause Telegram to run on Xwayland rather than Wayland. And considering that RPMFusion didn't have telegram-desktop, how to go about it?

**Comment by genodeftest** [comment]
Same here as @c-thun reported. Please reopen this issue as Telegram still can't run natively on Wayland. Or should we open a separate issue for the Flatpak?

**Comment by ilya-fedin** [comment]
> The Flatpak builds still cause Telegram to run on Xwayland rather than Wayland.

Qt defaults to XWayland on GNOME due to bad compatibility, you should set `QT_QPA_PLATFORM=wayland`

**Comment by genodeftest** [comment]
> Qt defaults to XWayland on GNOME due to bad compatibility, you should set `QT_QPA_PLATFORM=wayland`

makes telegram work nicely and GNOME shell's looking glass tells me it is a wayland window, when running with `QT_QPA_PLATFORM=wayland flatpak run --socket=wayland org.telegram.desktop`. It even still has a tray icon (surprisingly).

**Comment by iMonZ** [comment]
I get this error

```
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

fish: “telegram-desktop” terminated by signal SIGABRT (Abort)

```

**Comment by iMonZ** [comment]
Please reopen this issue because its not even close from *fixed*!

**Comment by ilya-fedin** [comment]
It's fixed, I can run Telegram on Wayland.

**Comment by iMonZ** [comment]
> It's definitely fixed, I can run Telegram on Wayland.

The problem is that you run it in X11 on top of Wayland!
You get a much better performance with native wayland!
You can force QT apps to run native wayland only if you set this variable after that you need to re-login:
`QT_QPA_PLATFORM = wayland`

Telegram is not able to run on Native Wayland without X11

(look in your activity's for xwayland)

**Comment by nortexoid** [comment]
> > It's definitely fixed, I can run Telegram on Wayland.
> 
> The problem is that you run it in X11 on top of Wayland!
> You get a much better performance with native wayland!
> You can force QT apps to run native wayland only if you set this variable after that you need to re-login:
> `QT_QPA_PLATFORM = wayland`
> 
> Telegram is not able to run on Native Wayland without X11
> 
> (look in your activity's for xwayland)

Actually, I'm running it natively on wayland as well. I'm running telegram-desktop from the manjaro repos in a KDE wayland session and running xprop shows that telegram is running natively in wayland.

**Comment by iMonZ** [comment]
> It's definitely fixed, I can run Telegram on Wayland.

The problem is that you run it in X11 on top of Wayland!
You get a much better performance with native wayland!
You can force QT apps to run native wayland only if you set this variable after that you need to re-login:
`QT_QPA_PLATFORM = wayland`

Telegram is not able to run on Native Wayland without X11

(look in your activity's for xwayland)


> > > It's definitely fixed, I can run Telegram on Wayland.
> > 
> > 
> > The problem is that you run it in X11 on top of Wayland!
> > You get a much better performance with native wayland!
> > You can force QT apps to run native wayland only if you set this variable after that you need to re-login:
> > `QT_QPA_PLATFORM = wayland`
> > Telegram is not able to run on Native Wayland without X11
> > (look in your activity's for xwayland)
> 
> Actually, I'm running it natively on wayland as well. I'm running telegram-desktop from the manjaro repos in a KDE wayland session and running xprop shows that telegram is running natively in wayland.

Which version do you have?

**Comment by ilya-fedin** [comment]
> Telegram is not able to run on Native Wayland without X11

That's a lie, I'm talking about native wayland. Telegram supports it for a long time.

**Comment by nortexoid** [comment]
I'm running 2.5.8, but as others have remarked, native wayland support has been there for some time now. You can tell on KDE and gnome (and other DEs) because it doesn't use the native window decoration when running natively.

**Comment by Aokromes** [comment]
> > It's definitely fixed, I can run Telegram on Wayland.
> 
> The problem is that you run it in X11 on top of Wayland!
> You get a much better performance with native wayland!
> You can force QT apps to run native wayland only if you set this variable after that you need to re-login:
> `QT_QPA_PLATFORM = wayland`
> 

from where you have downloaded telegram desktop?

**Comment by iMonZ** [comment]
> > > It's definitely fixed, I can run Telegram on Wayland.
> > 
> > 
> > The problem is that you run it in X11 on top of Wayland!
> > You get a much better performance with native wayland!
> > You can force QT apps to run native wayland only if you set this variable after that you need to re-login:
> > `QT_QPA_PLATFORM = wayland`
> 
> from where you have downloaded telegram desktop?

from the ubuntu universe

**Comment by iMonZ** [comment]
So Telegram is running inside of X11:
https://wayland.freedesktop.org/xserver.html  

Here is everything explained:
https://wiki.qt.io/QtWayland

**Comment by ilya-fedin** [comment]
> from the ubuntu universe

You probably should install qtwayland from the repos. It will be a very old version with a lot of Wayland bugs though, given that Ubuntu updates once in six months (once in two years for LTS) and Debian package is updated rarely whoever maintains it...

> because it doesn't use the native window decoration when running natively

Native decorations are supported on Wayland as well unless you running GNOME with xdg-decoration support or a build somewhere from rpmfusion where the maintainer disables Wayland and GTK integrations.

**Comment by iMonZ** [comment]
> > from the ubuntu universe
> 
> You probably should install qtwayland from the repos. It will be a very old version with a lot of Wayland bugs though, given that Ubuntu updates once in six months (once in two years for LTS) and Debian package is updated rarely whoever maintains it...
> 
> > because it doesn't use the native window decoration when running natively
> 
> Native decorations are supported on Wayland as well unless you running GNOME with xdg-decoration support or a build somewhere from rpmfusion where the maintainer disables Wayland and GTK integrations.

Its a library for compiling where should I install that?

**Comment by ilya-fedin** [comment]
> Its a library for compiling where should I install that?

It's https://archlinux.org/packages/extra/x86_64/qt5-wayland/ in Arch, you should find the same package on Ubuntu. It contains libraries for Wayland support for Qt apps (Telegram, VLC, qBittorrent, etc)

**Comment by Aokromes** [comment]
> > > > It's definitely fixed, I can run Telegram on Wayland.
> > > 
> > > 
> > > The problem is that you run it in X11 on top of Wayland!
> > > You get a much better performance with native wayland!
> > > You can force QT apps to run native wayland only if you set this variable after that you need to re-login:
> > > `QT_QPA_PLATFORM = wayland`
> > 
> > 
> > from where you have downloaded telegram desktop?
> 
> from the ubuntu universe

download it from desktop.telegram.org and try again.

**Comment by iMonZ** [comment]
Well... its really fixed!
with this command:
`snap install telegram-desktop`

just avoid installing telegram over apt on Ubuntu or anything similar
