### ISSUE TITLE
Telegram Desktop won't open on windows

### ISSUE THREAD

**Issue by sohantanna** [telegramdesktop/tdesktop#2377]
I'm not the only one who seems to be having this issue: https://www.reddit.com/r/Telegram/comments/4af1lc/qa_windows_desktop_app_wont_open/
### Steps to reproduce
1. Open telegram
2. 
3. 
### Expected behaviour

Should open the program
### Actual behaviour

Nothing happens. Nothing pops up, no errors.
### Configuration

Win 10

Telegram tsetup.0.10.1.exe
### Logs

[2016.08.22 18:33:14] Launched version: 10001, alpha: [FALSE], beta: 0, debug mode: [FALSE], test dc: [FALSE]
[2016.08.22 18:33:14] Executable dir: C:/Users/Sohan/AppData/Roaming/Telegram Desktop New/, name: Telegram.exe
[2016.08.22 18:33:14] Initial working dir: C:/Users/Sohan/AppData/Roaming/Telegram Desktop New/
[2016.08.22 18:33:14] Working dir: C:/Users/Sohan/AppData/Roaming/Telegram Desktop New/
[2016.08.22 18:33:14] Arguments: "C:\Users\Sohan\AppData\Roaming\Telegram Desktop New\Telegram.exe"
[2016.08.22 18:33:14] Logs started
[2016.08.22 18:33:14] Connecting local socket to Global\279160af93eddeeb70fd0d1e17345bd4-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2016.08.22 18:33:14] This is the only instance of Telegram, starting server and app...
[2016.08.22 18:33:14] Moved logging from 'log_start0.txt' to 'C:/Users/Sohan/AppData/Roaming/Telegram Desktop New/log.txt'!
[2016.08.22 18:33:14] Opened 'C:/Users/Sohan/AppData/Roaming/Telegram Desktop New/tdata/working' for reading, the previous Telegram Desktop launch was not finished properly :( Crash log size: 0
[2016.08.22 18:33:14] App Info: reading settings...
[2016.08.22 18:33:14] App Info: reading encrypted settings...

**Comment by sohantanna** [comment]
Portable version does not work either.

**Comment by tjhorner** [comment]
Same logs with the portable version?

**Comment by kode54** [comment]
Crash from freshly unpacked tportable.0.10.19.zip:

````
[2016.10.29 18:48:22] Launched version: 10019, alpha: [FALSE], beta: 0, debug mode: [FALSE], test dc: [FALSE]
[2016.10.29 18:48:22] Executable dir: C:/Users/kode5/Documents/Utilities/Telegram/, name: Telegram.exe
[2016.10.29 18:48:22] Initial working dir: C:/Users/kode5/Documents/Utilities/Telegram/
[2016.10.29 18:48:22] Working dir: C:/Users/kode5/Documents/Utilities/Telegram/
[2016.10.29 18:48:22] Arguments: "C:\Users\kode5\Documents\Utilities\Telegram\Telegram.exe"
[2016.10.29 18:48:22] Logs started
[2016.10.29 18:48:22] Connecting local socket to Global\cb6ea254e48742706034780e4c3079bc-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2016.10.29 18:48:22] This is the only instance of Telegram, starting server and app...
[2016.10.29 18:48:22] Moved logging from 'log_start0.txt' to 'C:/Users/kode5/Documents/Utilities/Telegram/log.txt'!
[2016.10.29 18:48:22] Checking...
[2016.10.29 18:48:22] Checking C:\Users\kode5\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\.
[2016.10.29 18:48:22] Checking C:\Users\kode5\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\..
[2016.10.29 18:48:22] Checking C:\Users\kode5\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\desktop.ini
[2016.10.29 18:48:22] Checking C:\Users\kode5\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\File Explorer.lnk
[2016.10.29 18:48:22] Checking C:\Users\kode5\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\foobar2000.lnk
[2016.10.29 18:48:22] Checking C:\Users\kode5\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Google Chrome.lnk
[2016.10.29 18:48:23] Checking C:\Users\kode5\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Skype.lnk
[2016.10.29 18:48:23] Checking C:\Users\kode5\AppData\Roaming\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Steam.lnk
````

**Comment by auchri** [comment]
@kode54 which version of windows do you use?

**Comment by kode54** [comment]
Windows 10 Pro [10.0.14393]

**Comment by ladislavsulc** [comment]
Same here :( It used to work, then it stopped to work and started to crash on WIN10 startup, now it won't start at all even manually. Tried everything.

`[2017.05.02 16:05:07] Launched version: 1000029, alpha: [FALSE], beta: 0, debug mode: [FALSE], test dc: [FALSE]
[2017.05.02 16:05:07] Executable dir: C:/Users/Lada/AppData/Roaming/Telegram Desktop/, name: Telegram.exe
[2017.05.02 16:05:07] Initial working dir: C:/Users/Lada/AppData/Roaming/Telegram Desktop/
[2017.05.02 16:05:07] Working dir: C:/Users/Lada/AppData/Roaming/Telegram Desktop/
[2017.05.02 16:05:07] Arguments: "C:\Users\Lada\AppData\Roaming\Telegram Desktop\Telegram.exe"
[2017.05.02 16:05:07] Logs started
[2017.05.02 16:05:07] Connecting local socket to Global\a5e51fbebccc0462f833256c726c720d-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2017.05.02 16:05:07] This is the only instance of Telegram, starting server and app...
[2017.05.02 16:05:07] Moved logging from 'log_start0.txt' to 'C:/Users/Lada/AppData/Roaming/Telegram Desktop/log.txt'!
[2017.05.02 16:05:07] Opened 'C:/Users/Lada/AppData/Roaming/Telegram Desktop/tdata/working' for reading, the previous Telegram Desktop launch was not finished properly :( Crash log size: 535
[2017.05.02 16:05:07] App Error: _basePath is empty in writeSettings()
[2017.05.02 16:05:07] App Info: reading settings...
[2017.05.02 16:05:07] App Info: reading encrypted settings...
[2017.05.02 16:05:07] OpenAL Logging Level: (not set)
[2017.05.02 16:05:07] Audio Playback Devices: OpenAL Soft
[2017.05.02 16:05:07] Audio Playback Default Device: OpenAL Soft
[2017.05.02 16:05:07] Audio Capture Devices: OpenAL Soft on Mikrofon (HD Pro Webcam C920);OpenAL Soft on Mikrofon (ZvukovĂ© zaĹ™Ă­zenĂ­ High Definition Audio)
[2017.05.02 16:05:07] Audio Capture Default Device: OpenAL Soft on Mikrofon (HD Pro Webcam C920)
[2017.05.02 16:05:08] App Info: reading map...
[2017.05.02 16:05:08] App Info: reading encrypted map...
[2017.05.02 16:05:08] App Info: reading encrypted user settings...
[2017.05.02 16:05:08] App Info: encrypted user settings read.
[2017.05.02 16:05:08] App Info: reading encrypted mtp data...
[2017.05.02 16:05:08] MTP Info: read keys, current: 0, to destroy: 2
[2017.05.02 16:05:08] Map read time: 15
[2017.05.02 16:05:08] Window Shadow: 1, 1, 3, 4, 6, 9, 13, 18, 24, 31, 38, 46
[2017.05.02 16:05:08] TCP Error: error packet received, code = -404
[2017.05.02 16:05:08] MTP Info: -404 error received on destroying key 2560002, assuming it is destroyed.
[2017.05.02 16:05:08] TCP Error: error packet received, code = -404
[2017.05.02 16:05:08] MTP Info: -404 error received on destroying key 2560004, assuming it is destroyed.
[2017.05.02 16:05:08] MTP Info: all keys scheduled for destroy are destroyed.
[2017.05.02 16:05:30] Assertion Failed! "!snapshotWas.isNull() || !snapshotNow.isNull()" t:\tbuild\twin\telegram\sourcefiles\ui\widgets\labels.cpp:64
`

Any idea anyone? The Chrome app is not as good as the desktop one...

**Comment by stek29** [comment]
@lafislavsulc this was fixed in 4fc2c18. Do you have the latest version installed?

**Comment by stek29** [comment]
@ladislavsulc this was fixed in 4fc2c18. Please download latest version and try again (app won't autoupdate since it can't start)

**Comment by john-preston** [comment]
@ladislavsulc This fix is not in the stable version yet, please reinstall the app or try the alpha version from https://desktop.telegram.org/changelog#alpha-version

**Comment by ladislavsulc** [comment]
@john-preston perfect, that works! Thank you!

**Comment by Aokromes** [comment]
close?

**Comment by NeonWizard** [comment]
Issue still persisting a year later. Deleted and reinstalled with the latest release.

**Comment by DarkSilence** [comment]
Have the same issue. Can't start Telegram. My logs below.
Tried to run it in debug mode with "-debug" param - no luck. Log says debug mode: [FALSE] anyways.
How to turn on debug mode and any clues how to run TG?

Windows 7 x64 latest updates. TG beta and TG stable latest.

`[2019.02.15 00:45:32] Launched version: 1005007, install beta: [TRUE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
[2019.02.15 00:45:32] Executable dir: C:/Users/DarkSilence/Application Data/Telegram Desktop/, name: Telegram.exe
[2019.02.15 00:45:32] Initial working dir: C:/Users/DarkSilence/Application Data/Telegram Desktop/
[2019.02.15 00:45:32] Working dir: C:/Users/DarkSilence/Application Data/Telegram Desktop/
[2019.02.15 00:45:32] Command line: C:\Users\DarkSilence\Application Data\Telegram Desktop\Telegram.exe -debug
[2019.02.15 00:45:32] Executable path before check: C:/Users/DarkSilence/Application Data/Telegram Desktop/Telegram.exe
[2019.02.15 00:45:32] Logs started
`

**Comment by Aokromes** [comment]
@DarkSilence iirc it's -- debug 2 "-" not one.

**Comment by DarkSilence** [comment]
@Aokromes I've tried without any success -debug -debugmode --debug --debugmode /debug /debugmode -debug-mode --debug-mode /debug-mode 
Then I've found in the sources that TG checks for `withdebug` file in the data folder. I've created this file and debug mode was activated... 
But debug mode didn't help me at all, because neither any additional log was created nor basic log file had any additional info.
Also I checked win registry and removed any nodes related to Telegram. Didn't help.
Then I ran TG and just waited. Telegram.exe process was present in Task Manager. After ~20 mins TG window appeared! I closed it again and tried to run it again. Same behavior. TG process was present but no window was created.
Before that I had an issue with my wifi. I didn't have Internet connection for some time. Maybe it's related somehow. It seems that TG is running some routing in background before main window creation process and, this routine maybe checks Internet connection or something? And this routine doesn't leave any traces in logs.

**Comment by KIJIMT123** [comment]
![image](https://user-images.githubusercontent.com/47878019/53219930-f84b6700-369c-11e9-9c42-14424a3078cd.png)

**Comment by KIJIMT123** [comment]
My desktop telegram can't start, no respond. but Android and Ios is normal working.

**Comment by KIJIMT123** [comment]
![image](https://user-images.githubusercontent.com/47878019/53220043-7445af00-369d-11e9-9cae-257a15fd8c26.png)

**Comment by KIJIMT123** [comment]
I already uninstall and reinstall 10 times. Restart the computer 10 times^^still can't, who can help me, please.
By the way telegram web working also.

**Comment by fabman** [comment]
> Have the same issue. Can't start Telegram. My logs below.
> Tried to run it in debug mode with "-debug" param - no luck. Log says debug mode: [FALSE] anyways.
> How to turn on debug mode and any clues how to run TG?
> 
> Windows 7 x64 latest updates. TG beta and TG stable latest.
> 
> ```
> [2019.02.15 00:45:32] Launched version: 1005007, install beta: [TRUE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
> [2019.02.15 00:45:32] Executable dir: C:/Users/DarkSilence/Application Data/Telegram Desktop/, name: Telegram.exe
> [2019.02.15 00:45:32] Initial working dir: C:/Users/DarkSilence/Application Data/Telegram Desktop/
> [2019.02.15 00:45:32] Working dir: C:/Users/DarkSilence/Application Data/Telegram Desktop/
> [2019.02.15 00:45:32] Command line: C:\Users\DarkSilence\Application Data\Telegram Desktop\Telegram.exe -debug
> [2019.02.15 00:45:32] Executable path before check: C:/Users/DarkSilence/Application Data/Telegram Desktop/Telegram.exe
> [2019.02.15 00:45:32] Logs started
> ```

Have you been able to solve it?. I have exactly the same problem with the same log file:
```

[2019.07.31 15:36:28] Launched version: 1007015, install beta: [TRUE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
[2019.07.31 15:36:28] Executable dir: C:/Users/fabman/AppData/Roaming/Telegram/, name: Telegram.exe
[2019.07.31 15:36:28] Initial working dir: C:/Users/fabman/AppData/Roaming/Telegram/
[2019.07.31 15:36:28] Working dir: C:/Users/fabman/AppData/Roaming/Telegram/
[2019.07.31 15:36:28] Command line: Telegram.exe
[2019.07.31 15:36:28] Executable path before check: C:/Users/fabman/AppData/Roaming/Telegram/Telegram.exe
[2019.07.31 15:36:28] Logs started

```

**Comment by kondr1** [comment]
same problem

**Comment by Aokromes** [comment]
plz next time on restart if you get send crash click it and post id here.

**Comment by DzmitryFil** [comment]
Same problem. log:
`[2020.03.24 11:13:04] Launched version: 1009021, install beta: [FALSE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
[2020.03.24 11:13:04] Executable dir: C:/Users/dmitr/AppData/Roaming/Telegram Desktop/, name: Telegram.exe
[2020.03.24 11:13:04] Initial working dir: C:/Users/dmitr/AppData/Roaming/Telegram Desktop/
[2020.03.24 11:13:04] Working dir: C:/Users/dmitr/AppData/Roaming/Telegram Desktop/
[2020.03.24 11:13:04] Command line: C:\Users\dmitr\AppData\Roaming\Telegram Desktop\Telegram.exe
[2020.03.24 11:13:04] Executable path before check: C:/Users/dmitr/AppData/Roaming/Telegram Desktop/Telegram.exe
[2020.03.24 11:13:04] Logs started
[2020.03.24 11:13:04] Connecting local socket to Global\9c0ff13a557add809af071d02962d3e4-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2020.03.24 11:13:04] This is the only instance of Telegram, starting server and app...
[2020.03.24 11:13:04] Moved logging from 'C:/Users/dmitr/AppData/Roaming/Telegram Desktop/log_start0.txt' to 'C:/Users/dmitr/AppData/Roaming/Telegram Desktop/log.txt'!
[2020.03.24 11:13:04] Primary screen DPI: 96
[2020.03.24 11:13:04] Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
[2020.03.24 11:13:04] Font: from ':/gui/fonts/DAOpenSansRegularItalic.ttf' loaded 'DAOpenSansRegularItalic'
[2020.03.24 11:13:04] Font: from ':/gui/fonts/DAOpenSansBold.ttf' loaded 'DAOpenSansBold'
[2020.03.24 11:13:04] Font: from ':/gui/fonts/DAOpenSansBoldItalic.ttf' loaded 'DAOpenSansBoldItalic'
[2020.03.24 11:13:04] Font: from ':/gui/fonts/DAOpenSansSemibold.ttf' loaded 'DAOpenSansSemibold'
[2020.03.24 11:13:04] Font: from ':/gui/fonts/DAOpenSansSemiboldItalic.ttf' loaded 'DAOpenSansSemiboldItalic'
[2020.03.24 11:13:04] App Info: reading settings...
[2020.03.24 11:13:04] App Info: reading encrypted settings...
[2020.03.24 11:13:04] Lang Info: Loaded cached, keys: 2582
[2020.03.24 11:13:04] OpenAL Logging Level: (not set)
[2020.03.24 11:13:04] Audio Playback Devices: OpenAL Soft on Digital Audio (S/PDIF) (2- High Definition Audio Device);OpenAL Soft on LG HDR WQHD (3- NVIDIA High Definition Audio)
[2020.03.24 11:13:04] Audio Playback Default Device: OpenAL Soft on Digital Audio (S/PDIF) (2- High Definition Audio Device)
[2020.03.24 11:13:04] Audio Capture Devices: 
[2020.03.24 11:13:04] Audio Capture Default Device: 
[2020.03.24 11:13:04] Audio Error: Could not open capture device!
[2020.03.24 11:13:04] App Info: reading map...
[2020.03.24 11:13:04] App Info: reading encrypted map...
[2020.03.24 11:13:04] App Info: reading encrypted user settings...
[2020.03.24 11:13:04] App Info: encrypted user settings read.
[2020.03.24 11:13:04] App Info: reading encrypted mtp data...
[2020.03.24 11:13:04] MTP Info: read keys, current: 5, to destroy: 0
[2020.03.24 11:13:04] Map read time: 2
[2020.03.24 11:13:05] Export Info: Destroy top bar by controller removal.
[2020.03.24 11:13:05] Window Shadow: 1, 1, 3, 4, 6, 9, 13, 18, 24, 31, 38, 46
`

**Comment by vtuu** [comment]
Have the same issue.
Each time it is a 50/50: will app be opened or not.
Such a shame.

\AppData\Roaming\Telegram Desktop\log_start.txt
```
[2020.04.04 20:11:58] Launched version: 2000001, install beta: [FALSE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
[2020.04.04 20:11:58] Executable dir: C:/Users/tu/AppData/Roaming/Telegram Desktop/, name: Telegram.exe
[2020.04.04 20:11:58] Initial working dir: C:/Users/tu/AppData/Roaming/Telegram Desktop/
[2020.04.04 20:11:58] Working dir: C:/Users/tu/AppData/Roaming/Telegram Desktop/
[2020.04.04 20:11:58] Command line: C:\Users\tu\AppData\Roaming\Telegram Desktop\Telegram.exe
[2020.04.04 20:11:58] Executable path before check: C:/Users/tu/AppData/Roaming/Telegram Desktop/Telegram.exe
[2020.04.04 20:11:58] Logs started
[2020.04.04 20:11:58] Connecting local socket to Global\7cb75daf5ace1a68a3d61ba746e20f14-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2020.04.04 20:11:58] This is the only instance of Telegram, starting server and app...
[2020.04.04 20:11:58] Moved logging from 'C:/Users/tu/AppData/Roaming/Telegram Desktop/log_start0.txt' to 'C:/Users/tu/AppData/Roaming/Telegram Desktop/log.txt'!
[2020.04.04 20:11:58] Old start log 'log_start1.txt' found, deleted: [FALSE]
[2020.04.04 20:11:58] Opened 'C:/Users/tu/AppData/Roaming/Telegram Desktop/tdata/working' for reading, the previous Telegram Desktop launch was not finished properly :( Crash log size: 0
[2020.04.04 20:11:58] Primary screen DPI: 96
[2020.04.04 20:11:58] Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
[2020.04.04 20:11:58] Font: from ':/gui/fonts/DAOpenSansRegularItalic.ttf' loaded 'DAOpenSansRegularItalic'
[2020.04.04 20:11:58] Font: from ':/gui/fonts/DAOpenSansBold.ttf' loaded 'DAOpenSansBold'
[2020.04.04 20:11:58] Font: from ':/gui/fonts/DAOpenSansBoldItalic.ttf' loaded 'DAOpenSansBoldItalic'
[2020.04.04 20:11:58] Font: from ':/gui/fonts/DAOpenSansSemibold.ttf' loaded 'DAOpenSansSemibold'
[2020.04.04 20:11:58] Font: from ':/gui/fonts/DAOpenSansSemiboldItalic.ttf' loaded 'DAOpenSansSemiboldItalic'
[2020.04.04 20:11:58] App Info: reading settings...
[2020.04.04 20:11:58] App Info: reading encrypted settings...
[2020.04.04 20:11:58] Lang Info: Loaded cached, keys: 2654
[2020.04.04 20:11:59] OpenAL Logging Level: (not set)
[2020.04.04 20:11:59] Audio Playback Devices: OpenAL Soft on Speakers (AudioBox 22VSL Audio)
[2020.04.04 20:11:59] Audio Playback Default Device: OpenAL Soft on Speakers (AudioBox 22VSL Audio)
[2020.04.04 20:11:59] Audio Capture Devices: OpenAL Soft on Line (AudioBox 22VSL Audio)
[2020.04.04 20:11:59] Audio Capture Default Device: OpenAL Soft on Line (AudioBox 22VSL Audio)
[2020.04.04 20:11:59] Audio Error: Could not open capture device!
[2020.04.04 20:11:59] App Info: reading map...
[2020.04.04 20:11:59] App Info: reading encrypted map...
[2020.04.04 20:12:00] App Info: reading encrypted user settings...
[2020.04.04 20:12:00] App Info: encrypted user settings read.
[2020.04.04 20:12:00] App Info: reading encrypted mtp data...
[2020.04.04 20:12:00] MTP Info: read keys, current: 5, to destroy: 0
[2020.04.04 20:12:00] Map read time: 148
[2020.04.04 20:12:01] Export Info: Destroy top bar by controller removal.
[2020.04.04 20:12:01] Window Shadow: 1, 1, 3, 4, 6, 9, 13, 18, 24, 31, 38, 46
[2020.04.04 20:12:34] RPC Error: request 25 got fail with code 400, error CHAT_ADMIN_REQUIRED
[2020.04.04 20:12:41] RPC Error: request 38 got fail with code 400, error CHAT_ADMIN_REQUIRED
[2020.04.04 20:12:41] RPC Error: request 51 got fail with code 400, error CHAT_ADMIN_REQUIRED
```

\AppData\Roaming\Telegram Desktop\log_start1.txt
```
[2020.04.04 20:11:58] Launched version: 2000001, install beta: [FALSE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
[2020.04.04 20:11:58] Executable dir: C:/Users/tu/AppData/Roaming/Telegram Desktop/, name: Telegram.exe
[2020.04.04 20:11:58] Initial working dir: C:/Users/tu/AppData/Roaming/Telegram Desktop/
[2020.04.04 20:11:58] Working dir: C:/Users/tu/AppData/Roaming/Telegram Desktop/
[2020.04.04 20:11:58] Command line: C:\Users\tu\AppData\Roaming\Telegram Desktop\Telegram.exe
[2020.04.04 20:11:58] Executable path before check: C:/Users/tu/AppData/Roaming/Telegram Desktop/Telegram.exe
[2020.04.04 20:11:58] Logs started
[2020.04.04 20:11:58] Connecting local socket to Global\7cb75daf5ace1a68a3d61ba746e20f14-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2020.04.04 20:11:58] Socket connected, this is not the first application instance, sending show command...
[2020.04.04 20:12:02] Show command written, waiting response...
[2020.04.04 20:12:02] Show command response received, pid = 9768, activating and quitting...

```

**Comment by nikitamatrosoff** [comment]
It's an error.

**Comment by ilya-fedin** [comment]
> It's an error.

Don't see a log from you

**Comment by stasych** [comment]
I have same problem. Win10. I solved it, when rename (more safety rather delete) AppData\Roaming\Telegram Desktop\tdata\settingss . TG starts with my account, but without background settings.
FYI, also i set exe to run as administrator, and give full access to tg folder.
