### ISSUE TITLE
Opening videos in Telegram causes a green tint to be applied to video

### ISSUE THREAD

**Issue by Tony2987** [telegramdesktop/tdesktop#24360]
### Steps to reproduce

1. Find any video that has been uploaded to Telegram and sent as a message (preview is fine, by the way)
2. Open the video to visualize it inside Telegram.
It loads and runs fine but acquires a green tint over it.

### Expected behaviour

No green tint on videos, just like preview shows up.

### Actual behaviour

Green tint over the video once visualizing it in the video player in Telegram.

### Operating system

Windows 7 64x

### Version of Telegram Desktop

v3.7

### Installation source

Static binary from official website

**Comment by Aokromes** [comment]
try to change acceleration from directx to opengl

**Comment by jimmy-1000** [comment]
I have the same problem with new 3.7 version.

![FQgvZ6BXEAokA2J](https://user-images.githubusercontent.com/78575427/163720364-b2067a70-d1f3-4d93-8e10-c19ccc66ad6b.png)

**Comment by john-preston** [comment]
@jimmy-1000 You can disable hardware accelerated video decoding in Settings > Advanced > Performance.

**Comment by Yurbason** [comment]
> @jimmy-1000 You can disable hardware accelerated video decoding in Settings > Advanced > Performance.

thanks, really helped solve the problem
My video also turned green on the new version (v3.7 win7 x32)
this was not the case in previous versions

**Comment by jimmy-1000** [comment]
> @jimmy-1000 You can disable hardware accelerated video decoding in Settings > Advanced > Performance.

Thanks for your help. This is strange, I have a Nvidia graphic card 🤷

**Comment by VetaLioSTV** [comment]
@john-preston there is problem with memory leaks on fresh client 3.7 x64 (Windows 8.1). Play several videos/GIF's and it will allocate 2-3GBs with no reason(without release), wtf :(.

Something is broken... Even if you try to close client(to erase\freed memory), it will not have any effect, since after exit it stays anyway in process with same amount of captured memory.

**Comment by XJIOP** [comment]
Tthis is happening on my Nvidiar RTX 2080 (driver 512.15), telegram version 3.7 and same on prev version.

**Comment by jimmy-1000** [comment]
> Tthis is happening on my Nvidia RTX 2080 (driver 512.15), telegram version 3.7 and same on prev version.

It's correct, the change was made in version 3.6.3

**Comment by Tony2987** [comment]
To add, I also have an nVidia graphics card. Might be nVidia only related?

**Comment by Aokromes** [comment]
> To add, I also have an nVidia graphics card. Might be nVidia only related?

i don't have problem with geforce 960 + windows 11.

**Comment by Batchute** [comment]
> @jimmy-1000 You can disable hardware accelerated video decoding in Settings > Advanced > Performance.

Thanks. Almost worked for me (x64 Win7); mine turned red. Found another in my Tele chat with same problem.

**Comment by jez9999** [comment]
I have the same problem.  Windows 7, Intel HD graphics.

**Comment by FoxOscar** [comment]
I had this issue and after trying various things noted above (not with much success because bizarrely my control panel doesn't have a 'Display' option) I decided to go hunting in the Telegram Settings. Within Settings > Advanced, scroll down to Performance and there I disabled 'Hardware accelerated video decoding'. Next time I played a video it came up with a red hue on it instead of green. After Exiting Telegram and relaunching, all is good again... Hopefully if anyone else encounters difficulty with this and the previous solutions didn't do it or weren't able to be applied, this one might sort you out... ;-)
![Untitled](https://user-images.githubusercontent.com/103961838/163865308-717b02a6-0636-45b7-9777-781255aef23c.jpg)

**Comment by FoxOscar** [comment]
> > @jimmy-1000 You can disable hardware accelerated video decoding in Settings > Advanced > Performance.
> 
> Thanks. Almost worked for me (x64 Win7 Intel(R)Graphics); mine turned red. Found another in my Tele chat with same problem.

Look down a couple of comments - I think if you Exit Telegram (make sure to Exit and not just minimise to taskbar) and relaunch you should be fixed...

**Comment by jimmy-1000** [comment]
> To add, I also have an nVidia graphics card. Might be nVidia only related?

Yes I think it is possible. I will test it deactivating my Nvidia to see what happens.

**Comment by Batchute** [comment]
> > > @jimmy-1000 You can disable hardware accelerated video decoding in Settings > Advanced > Performance.
> > 
> > 
> > Thanks. Almost worked for me (x64 Win7 Intel(R)Graphics); mine turned red. Found another in my Tele chat with same problem.
> 
> Look down a couple of comments - I think if you Exit Telegram (make sure to Exit and not just minimise to taskbar) and relaunch you should be fixed...

Yes, always do exit completely, but seemingly it is working now. Thanks.

**Comment by jez9999** [comment]
Yeah, same here.  Red hue after disabling hardware acceleration, then exit and restart fixed it.  Still, if it requires disabling hardware acceleration, isn't this still a bug in Telegram's video system?

**Comment by cxavierpb** [comment]
The same thing happened to me with the green screens, when deactivating hard acceleration the screens turned red but the problem persisted. I fixed it by changing Angle Graphics to OpenGL
![Telegram verde](https://user-images.githubusercontent.com/103978593/163914113-c97112c3-3549-451c-b8e1-56335e92858c.JPG)

**Comment by aeiouaeiouaeiouaeiouaeiouaeiou** [comment]
I see that [this commit](https://github.com/telegramdesktop/tdesktop/commit/1c5a3aef54db0a716589923296590293266911bc) has been added, hopefully we will get an update soon.

**Comment by Neurotoxin001** [comment]
HW accelerated enabled with ANGLE DX9 - videos is green
HW accelerated disabled with ANGLE DX9 - videos is red
HW accelerated enabled with ANGLE Auto - videos is fine but I still got this bug:
https://github.com/telegramdesktop/tdesktop/issues/17109

**Comment by jimmy-1000** [comment]
Version 3.7 not only has this problem. I have a problem with "Open Telegram with system start". This application doesn't work exactly like previous versions does I will back to 3.6.1

**Comment by amgrypingvi** [comment]
> I had this issue and after trying various things noted above (not with much success because bizarrely my control panel doesn't have a 'Display' option) I decided to go hunting in the Telegram Settings. Within Settings > Advanced, scroll down to Performance and there I disabled 'Hardware accelerated video decoding'. Next time I played a video it came up with a red hue on it instead of green. After Exiting Telegram and relaunching, all is good again... Hopefully if anyone else encounters difficulty with this and the previous solutions didn't do it or weren't able to be applied, this one might sort you out... ;-) ![Untitled](https://user-images.githubusercontent.com/103961838/163865308-717b02a6-0636-45b7-9777-781255aef23c.jpg)

Thank you so much! This is the only one advice that really helped me.

**Comment by Neurotoxin001** [comment]
4.5.8 beta still have this issue

**Comment by gleruzh** [comment]
same issue - green screen instead of stream from camera
old laptop with windows 10x64 actual update, tg 4.8.9 (latest stable for now)
any combination of video accelleration and backend for ANGLE same result
intel hd graphics or nvidia 740m - same result.

**Comment by Aokromes** [comment]
older intel drivers are very bad.... it's recommended to update video drivers when possible, get dedicate gfx if possible, if unable to do such things the only solution without expend money is disable acceleration.

**Comment by gleruzh** [comment]
> older intel drivers are very bad.... it's recommended to update video drivers when possible, get dedicate gfx if possible, if unable to do such things the only solution without expend money is disable acceleration.

disabling acceleration DO not helps, as I wrote in the issue you'd closed as duplication.

**Comment by gleruzh** [comment]
Already try any combinations of three parameters

1. run Telegram with Intel or Nvidia GPU
2. turn on or turn off Hardware Video Accelleration
3. all different ANGLE backends.

Do not solved.

**Comment by john-preston** [comment]
@aeiouaeiouaeiouaeiouaeiouaeiou OpenGL was not working before, it just used software rendering really, like "Disabled" option.

**Comment by ytdjtjctyghngtdx** [comment]
> try to change acceleration from directx to opengl
![image](https://github.com/telegramdesktop/tdesktop/assets/94878796/8b41506f-fff7-483e-a04a-9324bf93088f)

**Comment by ytdjtjctyghngtdx** [comment]
> @aeiouaeiouaeiouaeiouaeiouaeiou OpenGL was not working before, it just used software rendering really, like "Disabled" option.

it works
