### ISSUE TITLE
Muted unread messages DO counted over "Back" button even if option "Include muted..." is off.

### ISSUE THREAD

**Issue by tomatojam42** [telegramdesktop/tdesktop#26703]
### Steps to reproduce

0. Update Telegram
1. Mute some chats.
2. Wait for unread muted messages.
3. Open some other chat (that has been read before).
4. Look at "back" button in top of window.

### Expected behaviour

If option "Include muted chats in unread count" is disabled, then muted chats should not be reason for counter to appear. Normal behavior was before and last update brings the bug.

### Actual behaviour

There is number of all unread messages from all chats over "Back" button.

### Operating system

Windows 11, 22621.2215

### Version of Telegram Desktop

4.9.2 x64

### Installation source

Static binary from official website

**Comment by kocane** [comment]
Happens on all my devices with this version, what a weird bug to slip by.

**Comment by pgsill** [comment]
Happening on all devices here as well, driving me nuts.

**Comment by tomatojam42** [comment]
I'm talking about window mode. Otherwise in fullscreen there is no need in "back" button, because chats are always on the left pane. I like focus instead of hubbub

**Comment by 5TXdYWK** [comment]
Is this issue going to get triaged? Any feedback from maintainers?

**Comment by john-preston** [comment]
I can't reproduce :( I've disabled "Include muted chats in unread count", I open any chat and start receiving messages in a muted group or personal chat -- and nothing appears over the arrow.

**Comment by 5TXdYWK** [comment]
@john-preston here's how my settings look:
![image](https://github.com/telegramdesktop/tdesktop/assets/82390521/f284c251-6479-461c-b460-b608b710bb23)

here's the issue:
![image](https://github.com/telegramdesktop/tdesktop/assets/82390521/cb70e930-a626-4e85-b5d9-10bbb3bd23f3)

here's my archived chats:
![image](https://github.com/telegramdesktop/tdesktop/assets/82390521/94157064-8a9c-404e-be0b-24328428da1b)


and what happens when i read some of them:
![image](https://github.com/telegramdesktop/tdesktop/assets/82390521/e267116c-056f-4c49-9e21-c590daa3a21d)

then i mark the second one as read, and the message count is gone:
![image](https://github.com/telegramdesktop/tdesktop/assets/82390521/150918c4-bcc4-46a5-85f4-34a7822399e8)

i can reproduce it on Telegram Desktop for Windows and MacOS.

**Comment by IvanAntonucci** [comment]
I can confirm.
No unread non-muted messages
![image](https://github.com/telegramdesktop/tdesktop/assets/25954299/e513dd03-4217-419b-8ee9-def108e17101)
![image](https://github.com/telegramdesktop/tdesktop/assets/25954299/cfc59dbf-39d2-4fea-82d0-4fd6d2a1e3a5)
But when I open any chat the counter for the muted ones appears on the back button
![image](https://github.com/telegramdesktop/tdesktop/assets/25954299/56b3ef53-2403-4320-aaf0-4993e485e0ae)

Telegram Desktop (4.9.2 x64) on Windows

**Comment by john-preston** [comment]
This is some weird optimization bug. It happens only on Windows (although the code is the same) and only in Release builds, can't reproduce that in a Debug build.

**Comment by pgsill** [comment]
Oh yeah, looks like this is only happening on Windows. Just tested on Mac.

**Comment by john-preston** [comment]
I hope this is fixed by https://github.com/telegramdesktop/tdesktop/commit/dff168c62e275204e680a8075f1b667e82bdce8b in 4.9.4 release.

**Comment by pgsill** [comment]
@john-preston Phenomenal, thank you so much!

**Comment by pgsill** [comment]
@john-preston still seeing this in tdesktop 4.9.5 :(

**Comment by 5TXdYWK** [comment]
@john-preston I can also confirm that this is still an issue. 

![image](https://github.com/telegramdesktop/tdesktop/assets/82390521/dca391bd-bfc0-4db7-9749-728729fcb874)

![image](https://github.com/telegramdesktop/tdesktop/assets/82390521/327ed7b3-2cac-4401-9892-d0283cdeeecb)

![image](https://github.com/telegramdesktop/tdesktop/assets/82390521/3b4dc513-81b8-448a-a941-aecd1f26f260)

Same behavior as before.

**Comment by 5TXdYWK** [comment]
@john-preston any chance we'll see a fix for this? 🥺🥺🥺🥺

**Comment by john-preston** [comment]
@pgsill You show an image of the tray icon with counter. It was always with gray counter if there are only muted unread messages and you have "Include muted chats in unread count" enabled in Settings > Notifications and Sounds > Badge counter.

I checked right now and if I disable this toggle in Settings the gray counter disappears from the tray icon. If I enable this toggle, it reappears. Please check your settings.

@5TXdYWK The same. I see some muted counters in your screenshots but I don't see anything non-consistent in them alone and I can't reproduce any problem with counters on my end.
