### ISSUE TITLE
Ctrl+C doesn't work in secondary Telegram windows while in search mode

### ISSUE THREAD

**Issue by Nasim1337** [telegramdesktop/tdesktop#26909]
### Steps to reproduce

1) Open a chat in a dedicated window (Ctrl+LMB on a chat)
2) Enable search
3) Select text in any message in the chat and press Ctrl+C

### Expected behaviour

Selected text is copied to clipboard

### Actual behaviour

Selected text IS NOT copied to clipboard

### Operating system

Windows 10

### Version of Telegram Desktop

4.10.2 x64

### Installation source

Static binary from official website

**Comment by venzeg** [comment]
Still relevant

**Comment by venzeg** [comment]
The issue still there, waiting for a fix

**Comment by 23rd** [comment]
Should be fixed in the v5.8.5 beta.

**Comment by venzeg** [comment]
hi @23rd, the issue is fixed but the other one is occurring now on 5.8.5 beta - when you press Ctrl+F in secondary window, search field no longer has focus so you can't paste into it with Ctrl+V key sequence without manually clicking into it first. Probably related to the made fix.

Thank you!

**Comment by 23rd** [comment]
Please check the v5.9.0.

**Comment by venzeg** [comment]
Hi @23rd, with 5.9.0 the original issue is back. Just to clarify it. Let's say I'm searching for something in separate window so I copy-pasted some text into search bar (11111111 on the attached screen). Now when I select and try to copy some text ("text test" shown as selection) within the message, it's not copied, original text 11111111 remains in clipboard:

![image](https://github.com/user-attachments/assets/b6d6584b-d184-44b9-ab11-7bc20a22badc)

In order to fix the issue I have to click ESC button to close search menu, click Ctrl+C again and then the selected text is being copied as intended

**Comment by 23rd** [comment]
😭

**Comment by venzeg** [comment]
Bumping, sry not that experienced with github workflow

**Comment by 23rd** [comment]
Maybe now..?

**Comment by venzeg** [comment]
It works now, ty @23rd
