### ISSUE TITLE
[Linux] missing font in data-selection

### ISSUE THREAD

**Issue by Translator5** [telegramdesktop/tdesktop#3418]
Linux Mint 18.1
I did delete sth. and now the fonts are not working.
Need some help, what do I need that my fonts are show normal again?
![bildschirmfoto vom 2017-05-19 21-33-17](https://cloud.githubusercontent.com/assets/9306861/26263966/3ba2fe36-3cdb-11e7-8f39-5576ee69345d.png)

**Comment by john-preston** [comment]
Is this in Telegram Desktop or where? %)

**Comment by stek29** [comment]
@john-preston I guess it's "Select file/dir" dialog

**Comment by Translator5** [comment]
Yes this is Telegram Desktop and the "Select file" dialog.

**Comment by john-preston** [comment]
@Translator5 So no fonts only there? They're fine in other places of tdesktop and in other select file dialogs, not in tdesktop?

**Comment by Translator5** [comment]
@john-preston yes, exactly!

**Comment by evenfrost** [comment]
Got this exact issue as well in Ubuntu. Ran Telegram from Terminal, got following output on file selection:
```bash
(Telegram:16093): Pango-WARNING **: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell 11'

(Telegram:16093): Pango-WARNING **: font_face status is: file not found

(Telegram:16093): Pango-WARNING **: scaled_font status is: file not found

(Telegram:16093): Pango-WARNING **: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='Cantarell 11', text='Recent'

(Telegram:16093): Pango-WARNING **: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell 11'

(Telegram:16093): Pango-WARNING **: font_face status is: file not found

(Telegram:16093): Pango-WARNING **: scaled_font status is: file not found

(Telegram:16093): Pango-WARNING **: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Bold 11'

(Telegram:16093): Pango-WARNING **: font_face status is: file not found

(Telegram:16093): Pango-WARNING **: scaled_font status is: file not found

(Telegram:16093): Pango-WARNING **: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='Cantarell Bold 11', text='Name'

(Telegram:16093): Pango-WARNING **: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Bold 15.83984375'

(Telegram:16093): Pango-WARNING **: font_face status is: file not found

(Telegram:16093): Pango-WARNING **: scaled_font status is: file not found

(Telegram:16093): Pango-WARNING **: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='Cantarell Bold 15.83984375', text='No results found'
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(Telegram:16093): Pango-WARNING **: failed to create cairo scaled font, expect ugly output. the offending font is 'Cantarell Bold 11'

(Telegram:16093): Pango-WARNING **: font_face status is: file not found

(Telegram:16093): Pango-WARNING **: scaled_font status is: file not found
```

Seems Telegram somehow fails to find Cantarell font though it's installed on my machine. Any clue how to fix it?

**Comment by evenfrost** [comment]
**Workaround**: open Telegram via console as root (e.g. `sudo ./Telegram`). It will behave as first-time session, so enter and confirm your number and proceed to main Telegram window. Open file selection dialog and make sure font there is now rendered correctly. Now, exit console-initiated Telegram and run it as usual, font for non-root will be fixed as well.

If still not working, run this:
```bash
sudo find /usr/share/fonts -type f -name "*.[o,t]tf" -exec chmod 775 '{}' \;
```
and try again. Script taken from [here](https://askubuntu.com/a/261007/204111).

**Comment by Translator5** [comment]
... you want to run telegram as root ;D - I pretty sure I don't trust that much to telegram :laughing: !

**Comment by daboross** [comment]
I'm also experiencing this.
```
$ telegram-desktop 
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig error: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 72: non-double matrix element
Fontconfig warning: "/etc/fonts/conf.d/10-scale-bitmap-fonts.conf", line 80: saw unknown, expected number

# opened up dialog now

(telegram-desktop:3648): Pango-WARNING **: failed to create cairo scaled font, expect ugly output. the offending font is 'Open Sans 9.9990234375'

(telegram-desktop:3648): Pango-WARNING **: font_face status is: file not found

(telegram-desktop:3648): Pango-WARNING **: scaled_font status is: file not found

(telegram-desktop:3648): Pango-WARNING **: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='Open Sans 9.9990234375', text='Recent'

(telegram-desktop:3648): Pango-WARNING **: failed to create cairo scaled font, expect ugly output. the offending font is 'Open Sans 9.9990234375'

(telegram-desktop:3648): Pango-WARNING **: font_face status is: file not found

(telegram-desktop:3648): Pango-WARNING **: scaled_font status is: file not found

(telegram-desktop:3648): Pango-WARNING **: failed to create cairo scaled font, expect ugly output. the offending font is 'Open Sans Bold 9.9990234375'

(telegram-desktop:3648): Pango-WARNING **: font_face status is: file not found

(telegram-desktop:3648): Pango-WARNING **: scaled_font status is: file not found

(telegram-desktop:3648): Pango-WARNING **: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='Open Sans Bold 9.9990234375', text='Name'

(telegram-desktop:3648): Pango-WARNING **: failed to create cairo scaled font, expect ugly output. the offending font is 'Open Sans Bold 14.3994140625'

(telegram-desktop:3648): Pango-WARNING **: font_face status is: file not found

(telegram-desktop:3648): Pango-WARNING **: scaled_font status is: file not found

(telegram-desktop:3648): Pango-WARNING **: shaping failure, expect ugly output. shape-engine='PangoFcShapeEngine', font='Open Sans Bold 14.3994140625', text='No results found'
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.

(telegram-desktop:3648): Pango-WARNING **: failed to create cairo scaled font, expect ugly output. the offending font is 'Open Sans Bold 9.9990234375'

(telegram-desktop:3648): Pango-WARNING **: font_face status is: file not found

(telegram-desktop:3648): Pango-WARNING **: scaled_font status is: file not found
```

**Comment by Translator5** [comment]
Issue is fixed in Patch 1.2 or the 12. Dezember 2017

**Comment by terrasoff** [comment]
> Issue is fixed in Patch 1.2 or the 12. Dezember 2017 for me
i've telegram **1.3.9** and still experience this issue

**Comment by Translator5** [comment]
For me it fixed by installing qt5 i thing ... "maybe" ...

**Comment by daboross** [comment]
I still experience this with a locally installed or updated Telegram.

Switching to telegramdesktop from openSUSE repositories fixed it, but it was still there in the non-distro-specific version...

**Comment by daboross** [comment]
oh sorry agh this is the wrong issue. I meant to comment on https://github.com/telegramdesktop/tdesktop/issues/1026, sorry.

**Comment by Aokromes** [comment]
Test after https://github.com/telegramdesktop/tdesktop/commit/8ee958bfa08b2ba87cffaf8de4b65b6890e59ea3

**Comment by Aokromes** [comment]
no answer after near 1 year, if this bug is still valid plz ask to reopen.
