### ISSUE TITLE
Bug: Telegram clears input text when last sent message's status is changed from waiting to sent

### ISSUE THREAD

**Issue by cookiengineer** [telegramdesktop/tdesktop#4852]
As the title states, there's an annoying bug in Telegram which will become very, very annoying when you start using Telegram Desktop via 3G on your laptop.

### Steps to reproduce
1. Send a message via slow internet connection (2G/3G)
2. While the last message is being sent and has the loading animation, start typing already in the still-focussed input field.
3. When the last message changes its status from loading to sent, the input field's text is cleared and you lose everything you have already typed.

### Expected behaviour

It should not clear the input field. Never ever.

### Actual behaviour

It clears the input field, which is super annoying.

### Configuration

**Operating system:** Arch Linux / GNOME

**Version of Telegram Desktop:** 1.2.24-1

**Used theme**: None, standard in Night/Dark mode

**Comment by john-preston** [comment]
@cookiengineer It should clear sometimes, but not in this case :( I'm not sure why this started happen now, perhaps something was changed from the server side. At least I hope it could be fixed there. Otherwise I'll fix this in the next version.

**Comment by Lonami** [comment]
> It should clear sometimes

What are "those times"? In my opinion it should *only* clear the textbox when you press enter, there really shouldn't be another case to clear it (that I can think of)! Is this related to "correctly" handling drafts perhaps?

**Comment by john-preston** [comment]
@Lonami When you write message from desktop, then it is saved as a draft, then you continue this draft from your phone and send it, it should clear the field on desktop.

**Comment by Lonami** [comment]
Right. But if you send it from the desktop is *really* unlikely suddenly there will be a new draft ready to replace your current text. How come this wasn't an issue later? I can only think of some sensible delay (a few seconds) to ignore empty drafts.

Oh, I did notice Telegram lately sends empty drafts in the dialogs instead of omitting them, so probably server's fault.

**Comment by john-preston** [comment]
@Lonami Yes, currently server sends an empty draft update in response to the request that sends a message. I'm not sure it was that way before or not, but currently it causes a lot of trouble and there is no need to send it in the first place.

**Comment by Nerond32** [comment]
I think it's a more serious issue. I'm having the same and heard a lot of people are experiencing same problem recently. I have very fast internet and Windows 10, same on Windows 7 laptop. You happen to lose few first letters when you type multiple messages in a row fast and it is indeed annoying.

**Comment by Tenemo** [comment]
Same happens to me and has been happening for quite some time, but rarely. Today and yesterday, however, are just horrible, practically every message disappears, unless I wait a second or two before typing. I've had several people mention the exact same issue to me just today and yesterday, both on mobile and desktop, it must be quite widespread.

Broadband connection, 90Mbps/21Mbps down/up, Telegram desktop 1.3.7, Windows 10. I let ping run during typing and the issue was still there, clearly disappearing messages are not related to connection speed nor latency - or at least on my side. 
`ping 8.8.8.8 -n 10000`
> Pinging 8.8.8.8 with 32 bytes of data:
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58  
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58  
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58
> Reply from 8.8.8.8: bytes=32 time=6ms TTL=58

**Comment by john-preston** [comment]
@Tenemo Please try now. I hope this thing was fixed for me from the server side.

**Comment by Lonami** [comment]
Neat, it seems to be fine again, thanks!

**Comment by pyraxo** [comment]
Was there an update for this? Still encountering this issue, be it on Android, or Telegram Desktop for OS X and Windows.

**Comment by cookiengineer** [comment]
Damn, this was fast. I think it is fixed for my case. I'm currently using 3G/4G internet connection and it seems to work on my laptop (tdesktop) now.

**Comment by classicmari** [comment]
@john-preston

The issue is fixed for me and the people I know that were also experiencing it. No matter how fast I type, it won't clear my next message preemptively. 

Thank you.

**Comment by Lonami** [comment]
I *can't* reproduce this issue on private chats and small group chats, but I still can reproduce it in megagroups, both public and private.

**Comment by altruistca** [comment]
I still get this problem, using Windows 7 with Telegram 1.3.7.

**Comment by AndrewAndreev** [comment]
> I can't reproduce this issue on private chats and small group chats, but I still can reproduce it in megagroups, both public and private.

I can confirm that this is the case. I can reproduce it with the steps described in the first post, as well as my friend.
I have Windows 10, Telegram Desktop 1.3.7
My friend has Windows 10, Telegram Desktop 1.2.7

And I guess it is not an update. But it still hasn't been fixed.

**Comment by altruistca** [comment]
I get the problem in private chats.

**Comment by AndrewAndreev** [comment]
I have stopped to experience the bug since yesterday.

**Comment by altruistca** [comment]
I get this problem on a stable broadband cable (non-wireless) connection. So I doubt it has anything to do with the connection. 

I do suspect it might be related to the amount of active telegram chat/groups you have going on. Does anyone else here have a lot of groups, and experiencing this problem?

**Comment by Lonami** [comment]
I think we all get the point. Some people have the issue, and some people don't. **Stop posting new comments** for "me too" or "not me" since it notifies everyone for things that we already know, and just upvote comments that reproduce *your* behaviour.

**Comment by CrytoEngineer** [comment]
Hi friends.  I still have the issue but  from reading it seems its fixed for others.  Its driving me insane. I have latest version installed but live in area where internet speeds can  be slow.

Plz help if possible @john-preston..seems like your the man for this. 🤞

**Comment by Mart-Bogdan** [comment]
What telegram version fixes this issue?

**Comment by Lonami** [comment]
Probably `v1.3.9` or higher (if you click on the commit, you can see relevant tags).

**Comment by Mart-Bogdan** [comment]
@Lonami thanks, I was looking at original commit in fork repo, indeed your linked it has tags.

Seems I caught another bug, as  I have 1.5.15 and experience similar behavior.
(Kubuntu 18.04)
