### ISSUE TITLE
Arabic font style isn't good in Ubuntu 18.10 development branch 

### ISSUE THREAD

**Issue by YousefSaber** [telegramdesktop/tdesktop#5172]
English font style is good but Arabic font style isn't good it's some how bold which I don't like 
tried to install GNOME tweaks to change the font but I couldn't succeed  

this is the desired Arabic font style which was present in Ubuntu 18.04.1 on telegram 

![image](https://user-images.githubusercontent.com/33742499/45765797-3d72f500-bc36-11e8-9b8e-5ee423ba35a6.png)

but this is the Arabic font style in Telegram which I don't like 

![image](https://user-images.githubusercontent.com/33742499/45765828-4f549800-bc36-11e8-862d-a3644ef6d66a.png)

**Operating system:**

Ubuntu Cosmic Cuttlefish (development branch) using GNOME shell v3.30 as desktop environment 

telegram v1.3.14 installed from a tar.xz from your official website ( to get updates quickly ) 
https://desktop.telegram.org/

please make sure that this issue will be avoided in the official final release of Ubuntu 18.10

**Comment by Aokromes** [comment]
#728 ?

**Comment by danialbehzadi** [comment]
I have no isuues with the telegram-desktop from Ubuntu archives.

**Comment by saeedtabrizi** [comment]
I have same problem as @YousefSaber  said .

**Comment by danialbehzadi** [comment]
> I have same problem as @YousefSaber said .

Did you install it from Ubuntu archives?

**Comment by saeedtabrizi** [comment]
Hi @danialbehzadi 
I download it from Telegram official website exactly .
but after upgrading to Ubuntu 18.10 the telegram fornt was changed automatically to a non readable arabic font .

**Comment by danialbehzadi** [comment]
> Hi @danialbehzadi
> I download it from Telegram official website exactly .
> but after upgrading to Ubuntu 18.10 the telegram fornt was changed automatically to a non readable arabic font .

Can you try removing it and install from Ubuntu archive to see if it's fine or not?

**Comment by saeedtabrizi** [comment]
> > Hi @danialbehzadi
> > I download it from Telegram official website exactly .
> > but after upgrading to Ubuntu 18.10 the telegram fornt was changed automatically to a non readable arabic font .
> 
> Can you try removing it and install from Ubuntu archive to see if it's fine or not?

OK  i just remove it and install from ubuntu archive as you said . 
Yeah, it's work like a charm now .
![image](https://user-images.githubusercontent.com/10245423/46828271-b08c0900-cda7-11e8-9b9d-b9fc8e705ff5.png)

**Comment by YousefSaber** [comment]
> > > Hi @danialbehzadi
> > > I download it from Telegram official website exactly .
> > > but after upgrading to Ubuntu 18.10 the telegram fornt was changed automatically to a non readable arabic font .
> > 
> > 
> > Can you try removing it and install from Ubuntu archive to see if it's fine or not?
> 
> OK i just remove it and install from ubuntu archive as you said .
> Yeah, it's work like a charm now .
> ![image](https://user-images.githubusercontent.com/10245423/46828271-b08c0900-cda7-11e8-9b9d-b9fc8e705ff5.png)

now that is a good arabic font hope that @danialbehzadi I hope that this issue will be avoided in telegram desktop ( downloaded from your website ) 

I don't like to download apps from repositories because they are often outdated and don't get updates quickly

**Comment by danialbehzadi** [comment]
> I don't like to download apps from repositories because they are often outdated and don't get updates quickly

Unfortunately, I'm afraid that I should say it's not a matter of your interest. You should never install a package out of the repository archive. If you want the latest updates in Ubuntu, you can alternatively pin the package from `devel` release channel with a higher priority in apt preferences.

**Comment by YousefSaber** [comment]
@danialbehzadi this is the official repository of telegram app here issues are posted and must be fixed not ignored 

you developed an executable application of telegram for linux system and it faces issues right now that must be fixed not ignored 

this level of customer support isn't acceptable this issue is still present in the official release of ubuntu 18.10 !!

consider also that this is a small bug if you couldn't fix it then how'll you fix critical bugs !!

**Comment by danialbehzadi** [comment]
> @danialbehzadi this is the official repository of telegram app here issues are posted and must be fixed not ignored

There is no such a thing as app repository. In modern GNU distributions, there is a distro repository archive which should be considered as the only source for installing packages. And no issues could be seen yet.

**Comment by smaznet** [comment]
same problem , and telegram starts very slow on ubuntu 18.10

**Comment by glococo** [comment]
Is it possible to use Beta Channel from Ubuntu repositories ?
I current using linux downloaded version with beta option enabled and **fonts issues since telegram-dektop from repositories is old**.

**Comment by YousefSaber** [comment]
@glococo  aside of the possibility of that will it even be stable as the official telegram app ?!!

Telegram developers must fix all these issues relying on snaps , repositories is inconvenient since they are outdated not to mention that Ubuntu is the most famous Open Source OS on the planet with the largest community support more than any other Linux Distro 

this situation is very embarrassing for Telegram

**Comment by john-preston** [comment]
@YousefSaber Snaps should be built together with the other versions, so they should not be outdated. I hope that they'll become the main way of delivering the app to the Linux users.

**Comment by YousefSaber** [comment]
@john-preston  put in mind that telegram doesn't have an official app build by them directly on snapcraft Telegram team have no choice but to fix the problems of the official executable app

**Comment by john-preston** [comment]
@YousefSaber There is, snapcraft.io/telegram-desktop

It's built on build.snapcraft.io (edge) and on launchpad (stable and beta).

**Comment by YousefSaber** [comment]
@john-preston do you know that there is no official snap telegram app even on snapcraft it isn't verified 

![screenshot_20181123-143131](https://user-images.githubusercontent.com/33742499/48943736-cfe08f00-ef2c-11e8-8a47-90a27285c8f7.png)

can we please stop ignoring this issue I guess that Telegram team must investigate this issue on the biggest open source OS platform on the planet !!!

**Comment by john-preston** [comment]
@YousefSaber I'll fix that "unofficial" in one of the next releases.

**Comment by YousefSaber** [comment]
alright I'll update the status of the bug after v1.5 update 

after the new update the app no longer takes very long time to start and it open instantly but the arabic font style is still ugly and distorted 

```
$ sudo ./Telegram 
[sudo] password for joseph: 

```

**Comment by danialbehzadi** [comment]
@YousefSaber You should never run Telegram or any other graphical app with sudo.

**Comment by NuLL3rr0r** [comment]
I had a Funtoo instance with official Telegram 1.4.3 binaries for Linux which worked fine. Since they hard masked FFmpeg 4 required by [ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium) and also multilib use flag on glibc which breaks Wine compatibility with win32 applications (yes I still play COD4 with friends inside Wine) I had no other way than switching to Gentoo.

To my surprise this is how the new Telegram looks like this with an unreadable font:

<img src="https://i.imgur.com/TzAbJaK.png">

I've always used Telegram Desktop official binaries on Funtoo/Gentoo without any issues. I only had to make sure media-fonts/farsi-fonts ebuild was installed before running Telegram.

**Comment by NuLL3rr0r** [comment]
OK, at the first glance it seems the culprit is GNU Unifont, for whatever reason Telegram Desktop picks it up for both English and Persian when it is installed on the system. I installed Unifont in order to be able to show U+0CA0 KANNADA LETTER TTHA character ( ಠ_ಠ ) as https://github.com/dodie/vim-disapprove-deep-indentation uses it. Uninstalling it makes Telegram font a bit better (still not a good font):

<img src="https://i.imgur.com/J1p3sc7.png">

So, I decided to replace GNU Unifont with Google's Noto font in order to be able to render ಠ_ಠ on my vim-disapprove-deep-indentation plugin. Now my Telegram Desktop looks like this (a lot better but not what I wanted):

<img src="https://i.imgur.com/y2Eq9qY.png">

Gentoo uses [eselect fontconfig](https://wiki.gentoo.org/wiki/Fontconfig) to quickly mess with fontconfig settings without touching its xml configuration files. No matter what Telegram does not respect users choice. I am not familiar with fontconfig's format but I guess it could be done by providing user's own configuration. Any ideas?

**Comment by NuLL3rr0r** [comment]
OK, in my case this resolved the issue:

I disabled Google Noto's font using

```
$ eselect fontconfig disable 66-noto-mono.conf 66-noto-sans.conf 66-noto-serif.conf
```

Which stops Telegram from picking up this font. And kept my regular Persian fonts using:

```
$ eselect fontconfig enable 65-fonts-persian.conf
```

Although no matter what if Unifont is installed on the system, even disabling it does not stop Telegram from picking it up:

```
$ eselect fontconfig disable 65-fonts-persian.conf
// the same as
$ eselect fontconfig enable 65-fonts-persian.conf
```

Now everything works as expected. Neovim works and is able to display ಠ, i3wm correctly shows ಠ in the the Firefox's title bar when I visit https://github.com/dodie/vim-disapprove-deep-indentation 

So, I guess that resolves it for me.

**Comment by YousefSaber** [comment]
@NuLL3rr0r can you please show me how to use or install eselect fontconfig because my system can't identify this command 

```
eselect fontconfig disable 66-noto-mono.conf 66-noto-sans.conf 66-noto-serif.conf

Command 'eselect' not found, did you mean:

  command 'dselect' from deb dselect
  command 'iselect' from deb iselect

Try: sudo apt install <deb name>

```

**Comment by Johnnynator** [comment]
> @NuLL3rr0r can you please show me how to use or install eselect fontconfig because my system can't identify this command

Fontconfig is from Gentoo, you can't use it in other distros,

**Comment by YousefSaber** [comment]
well is there anyway to fix this issue on Ubuntu @Johnnynator  ??

**Comment by NuLL3rr0r** [comment]
@YousefSaber yep there is. You can always read and modify the fontconfig configurations which reside inside /etc/fonts/conf.d/. I can provide you with everything I have inside that directory. But, please be wary that your distro has its own configuration placed in that directory. So, messing with that without knowing what your doing would be unwise. But, you can generate your own configuration and put it in your home directory and override system-wide configurations. What eselect fontconfig did for me is saving my time without getting involved with the underlying configurations. It just works out of the box.

This is a good starting point if you still want to fix it yourself on your distro: [I stared into the fontconfig, and the fontconfig stared back at me ](https://eev.ee/blog/2015/05/20/i-stared-into-the-fontconfig-and-the-fontconfig-stared-back-at-me/).

And here is [the official docs](https://www.freedesktop.org/software/fontconfig/fontconfig-user.html).

**Comment by runo280** [comment]
Here is how I fixed this issue:
- Close Telegram
- Create directory: `~/.fonts`
- Add a font with its **different weights** [I used [Vazir](https://github.com/rastikerdar/vazir-font)]
- Create file: `~/.fonts.conf` and add these line to it:
```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
 <match target="pattern">
  <test name="family" qual="any">
   <string>sans serif</string>
  </test>
  <edit mode="assign" binding="same" name="family">
   <string>Vazir</string>
  </edit>
 </match>
 <dir>~/.fonts</dir>
</fontconfig>
```
- Clear font caches:
` fc-cache -f -v`
`rm -r ~/.cache/fontconfig_11`

- Now open Telegram :)

**Comment by YousefSaber** [comment]
@runo280 didn't work out for me 

```
`(base) joseph@joseph-X541UJ:~$ fc-cache -f -v
/usr/share/fonts: caching, new cache contents: 0 fonts, 6 dirs
/usr/share/fonts/X11: caching, new cache contents: 0 fonts, 4 dirs
/usr/share/fonts/X11/Type1: caching, new cache contents: 8 fonts, 0 dirs
/usr/share/fonts/X11/encodings: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/X11/encodings/large: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/X11/misc: caching, new cache contents: 89 fonts, 0 dirs
/usr/share/fonts/X11/util: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/cMap: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/cmap: caching, new cache contents: 0 fonts, 5 dirs
/usr/share/fonts/cmap/adobe-cns1: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/cmap/adobe-gb1: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/cmap/adobe-japan1: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/cmap/adobe-japan2: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/cmap/adobe-korea1: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/opentype: caching, new cache contents: 0 fonts, 3 dirs
/usr/share/fonts/opentype/fonts-hosny-amiri: caching, new cache contents: 6 fonts, 0 dirs
/usr/share/fonts/opentype/malayalam: caching, new cache contents: 3 fonts, 0 dirs
/usr/share/fonts/opentype/noto: caching, new cache contents: 24 fonts, 0 dirs
/usr/share/fonts/truetype: caching, new cache contents: 1 fonts, 51 dirs
/usr/share/fonts/truetype/Gargi: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/Gubbi: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/Nakula: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/Navilu: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/Sahadeva: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/Sarai: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/abyssinica: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/ancient-scripts: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/truetype/arphic: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/truetype/dejavu: caching, new cache contents: 6 fonts, 0 dirs
/usr/share/fonts/truetype/droid: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/fonts-arabeyes: caching, new cache contents: 36 fonts, 0 dirs
/usr/share/fonts/truetype/fonts-beng-extra: caching, new cache contents: 6 fonts, 0 dirs
/usr/share/fonts/truetype/fonts-deva-extra: caching, new cache contents: 3 fonts, 0 dirs
/usr/share/fonts/truetype/fonts-gujr-extra: caching, new cache contents: 5 fonts, 0 dirs
/usr/share/fonts/truetype/fonts-guru-extra: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/fonts-kalapi: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/fonts-orya-extra: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/fonts-telu-extra: caching, new cache contents: 2 fonts, 0 dirs
/usr/share/fonts/truetype/freefont: caching, new cache contents: 12 fonts, 0 dirs
/usr/share/fonts/truetype/kacst: caching, new cache contents: 15 fonts, 0 dirs
/usr/share/fonts/truetype/kacst-one: caching, new cache contents: 2 fonts, 0 dirs
/usr/share/fonts/truetype/lao: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/liberation: caching, new cache contents: 16 fonts, 0 dirs
/usr/share/fonts/truetype/liberation2: caching, new cache contents: 12 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-assamese: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-bengali: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-devanagari: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-gujarati: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-kannada: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-malayalam: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-oriya: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-punjabi: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-tamil: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-tamil-classical: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/lohit-telugu: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/malayalam: caching, new cache contents: 11 fonts, 0 dirs
/usr/share/fonts/truetype/nanum: caching, new cache contents: 10 fonts, 0 dirs
/usr/share/fonts/truetype/noto: caching, new cache contents: 2 fonts, 0 dirs
/usr/share/fonts/truetype/openoffice: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/padauk: caching, new cache contents: 4 fonts, 0 dirs
/usr/share/fonts/truetype/pagul: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/samyak: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/samyak-fonts: caching, new cache contents: 3 fonts, 0 dirs
/usr/share/fonts/truetype/scheherazade: caching, new cache contents: 2 fonts, 0 dirs
/usr/share/fonts/truetype/sinhala: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/takao-gothic: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/tibetan-machine: caching, new cache contents: 1 fonts, 0 dirs
/usr/share/fonts/truetype/tlwg: caching, new cache contents: 58 fonts, 0 dirs
/usr/share/fonts/truetype/ttf-khmeros-core: caching, new cache contents: 2 fonts, 0 dirs
/usr/share/fonts/truetype/ubuntu: caching, new cache contents: 13 fonts, 0 dirs
/usr/share/fonts/type1: caching, new cache contents: 0 fonts, 1 dirs
/usr/share/fonts/type1/gsfonts: caching, new cache contents: 35 fonts, 0 dirs
/home/joseph/anaconda3/fonts: skipping, no such directory
/home/joseph/.local/share/fonts: skipping, no such directory
/home/joseph/.fonts: caching, new cache contents: 0 fonts, 0 dirs
/usr/share/fonts/X11: skipping, looped directory detected
/usr/share/fonts/cMap: skipping, looped directory detected
/usr/share/fonts/cmap: skipping, looped directory detected
/usr/share/fonts/opentype: skipping, looped directory detected
/usr/share/fonts/truetype: skipping, looped directory detected
/usr/share/fonts/type1: skipping, looped directory detected
/usr/share/fonts/X11/Type1: skipping, looped directory detected
/usr/share/fonts/X11/encodings: skipping, looped directory detected
/usr/share/fonts/X11/misc: skipping, looped directory detected
/usr/share/fonts/X11/util: skipping, looped directory detected
/usr/share/fonts/cmap/adobe-cns1: skipping, looped directory detected
/usr/share/fonts/cmap/adobe-gb1: skipping, looped directory detected
/usr/share/fonts/cmap/adobe-japan1: skipping, looped directory detected
/usr/share/fonts/cmap/adobe-japan2: skipping, looped directory detected
/usr/share/fonts/cmap/adobe-korea1: skipping, looped directory detected
/usr/share/fonts/opentype/fonts-hosny-amiri: skipping, looped directory detected
/usr/share/fonts/opentype/malayalam: skipping, looped directory detected
/usr/share/fonts/opentype/noto: skipping, looped directory detected
/usr/share/fonts/truetype/Gargi: skipping, looped directory detected
/usr/share/fonts/truetype/Gubbi: skipping, looped directory detected
/usr/share/fonts/truetype/Nakula: skipping, looped directory detected
/usr/share/fonts/truetype/Navilu: skipping, looped directory detected
/usr/share/fonts/truetype/Sahadeva: skipping, looped directory detected
/usr/share/fonts/truetype/Sarai: skipping, looped directory detected
/usr/share/fonts/truetype/abyssinica: skipping, looped directory detected
/usr/share/fonts/truetype/ancient-scripts: skipping, looped directory detected
/usr/share/fonts/truetype/arphic: skipping, looped directory detected
/usr/share/fonts/truetype/dejavu: skipping, looped directory detected
/usr/share/fonts/truetype/droid: skipping, looped directory detected
/usr/share/fonts/truetype/fonts-arabeyes: skipping, looped directory detected
/usr/share/fonts/truetype/fonts-beng-extra: skipping, looped directory detected
/usr/share/fonts/truetype/fonts-deva-extra: skipping, looped directory detected
/usr/share/fonts/truetype/fonts-gujr-extra: skipping, looped directory detected
/usr/share/fonts/truetype/fonts-guru-extra: skipping, looped directory detected
/usr/share/fonts/truetype/fonts-kalapi: skipping, looped directory detected
/usr/share/fonts/truetype/fonts-orya-extra: skipping, looped directory detected
/usr/share/fonts/truetype/fonts-telu-extra: skipping, looped directory detected
/usr/share/fonts/truetype/freefont: skipping, looped directory detected
/usr/share/fonts/truetype/kacst: skipping, looped directory detected
/usr/share/fonts/truetype/kacst-one: skipping, looped directory detected
/usr/share/fonts/truetype/lao: skipping, looped directory detected
/usr/share/fonts/truetype/liberation: skipping, looped directory detected
/usr/share/fonts/truetype/liberation2: skipping, looped directory detected
/usr/share/fonts/truetype/lohit-assamese: skipping, looped directory detected
/usr/share/fonts/truetype/lohit-bengali: skipping, looped directory detected
/usr/share/fonts/truetype/lohit-devanagari: skipping, looped directory detected
/usr/share/fonts/truetype/lohit-gujarati: skipping, looped directory detected
/usr/share/fonts/truetype/lohit-kannada: skipping, looped directory detected
/usr/share/fonts/truetype/lohit-malayalam: skipping, looped directory detected
/usr/share/fonts/truetype/lohit-oriya: skipping, looped directory detected
/usr/share/fonts/truetype/lohit-punjabi: skipping, looped directory detected
/usr/share/fonts/truetype/lohit-tamil: skipping, looped directory detected
/usr/share/fonts/truetype/lohit-tamil-classical: skipping, looped directory detected
/usr/share/fonts/truetype/lohit-telugu: skipping, looped directory detected
/usr/share/fonts/truetype/malayalam: skipping, looped directory detected
/usr/share/fonts/truetype/nanum: skipping, looped directory detected
/usr/share/fonts/truetype/noto: skipping, looped directory detected
/usr/share/fonts/truetype/openoffice: skipping, looped directory detected
/usr/share/fonts/truetype/padauk: skipping, looped directory detected
/usr/share/fonts/truetype/pagul: skipping, looped directory detected
/usr/share/fonts/truetype/samyak: skipping, looped directory detected
/usr/share/fonts/truetype/samyak-fonts: skipping, looped directory detected
/usr/share/fonts/truetype/scheherazade: skipping, looped directory detected
/usr/share/fonts/truetype/sinhala: skipping, looped directory detected
/usr/share/fonts/truetype/takao-gothic: skipping, looped directory detected
/usr/share/fonts/truetype/tibetan-machine: skipping, looped directory detected
/usr/share/fonts/truetype/tlwg: skipping, looped directory detected
/usr/share/fonts/truetype/ttf-khmeros-core: skipping, looped directory detected
/usr/share/fonts/truetype/ubuntu: skipping, looped directory detected
/usr/share/fonts/type1/gsfonts: skipping, looped directory detected
/usr/share/fonts/X11/encodings/large: skipping, looped directory detected
/home/joseph/anaconda3/var/cache/fontconfig: cleaning cache directory
/home/joseph/.cache/fontconfig: cleaning cache directory
/home/joseph/.fontconfig: not cleaning non-existent cache directory
fc-cache: succeeded
(base) joseph@joseph-X541UJ:~$ rm -r ~/.cache/fontconfig_11
```
`
![image](https://user-images.githubusercontent.com/33742499/53867464-9542c400-3ffc-11e9-9f0d-b9cd8f0ccf58.png)

this is what written in fonts.conf file 

`<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
 <match target="pattern">
  <test name="family" qual="any">
   <string>sans serif</string>
  </test>
  <edit mode="assign" binding="same" name="family">
   <string>Vazir</string>
  </edit>
 </match>
 <dir>~/.fonts</dir>
</fontconfig>`

but unfortunately I couldn't add Vazir 

  ```
`joseph@joseph-X541UJ:~$ sudo add-apt-repository ppa:blacksuited/fonts
[sudo] password for joseph: 
 Free Persian fonts for your system.
Note: Fonts in this PPA belong to their
respective owners.
 More info: https://launchpad.net/~blacksuited/+archive/ubuntu/fonts
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://eg.archive.ubuntu.com/ubuntu cosmic InRelease
Ign:2 http://ppa.launchpad.net/blacksuited/fonts/ubuntu cosmic InRelease                                                           
Hit:3 http://eg.archive.ubuntu.com/ubuntu cosmic-updates InRelease                                                                 
Ign:4 http://dl.google.com/linux/chrome/deb stable InRelease                                                                       
Get:5 http://security.ubuntu.com/ubuntu cosmic-security InRelease [88.7 kB]                                                        
Hit:6 http://eg.archive.ubuntu.com/ubuntu cosmic-backports InRelease                                                               
Hit:7 http://dl.google.com/linux/chrome/deb stable Release                                                                         
Hit:8 http://ppa.launchpad.net/git-core/ppa/ubuntu cosmic InRelease                                                                
Hit:9 http://linux.teamviewer.com/deb stable InRelease                                                                             
Hit:10 http://ppa.launchpad.net/graphics-drivers/ppa/ubuntu cosmic InRelease                                                       
Hit:11 http://packages.microsoft.com/repos/vscode stable InRelease                                                             
Err:13 http://ppa.launchpad.net/blacksuited/fonts/ubuntu cosmic Release                                                            
  404  Not Found [IP: 91.189.95.83 80]
Hit:14 https://brave-browser-apt-release.s3.brave.com cosmic InRelease                                     
Reading package lists... Done 
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target DEP-11 (main/dep11/Components-all.yml) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target DEP-11-icons-small (main/dep11/icons-48x48.tar) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
E: The repository 'http://ppa.launchpad.net/blacksuited/fonts/ubuntu cosmic Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
W: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target Translations (main/i18n/Translation-en_US) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target DEP-11 (main/dep11/Components-amd64.yml) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target DEP-11 (main/dep11/Components-all.yml) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target DEP-11-icons-small (main/dep11/icons-48x48.tar) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target DEP-11-icons (main/dep11/icons-64x64.tar) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target CNF (main/cnf/Commands-amd64) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
W: Target CNF (main/cnf/Commands-all) is configured multiple times in /etc/apt/sources.list.d/brave-browser.list:3 and /etc/apt/sources.list.d/google-chrome.list:3
(base) joseph@joseph-X541UJ:~$ sudo apt install fonts-vazir
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package fonts-vazir
`
```

**Comment by runo280** [comment]
@YousefSaber 
Dude u are doing wrong.
You should download **Vazir** from its repo, and put *.ttf fonts in `~/.fonts`
Vazir font is mainly for Persian, You could use any font u like, but consider it must have multiple weights.
Please read steps again and do exactly what I wrote.
![capture](https://user-images.githubusercontent.com/13608702/53876177-756ec880-401b-11e9-962c-3ee8b5424e18.PNG)

**Comment by NuLL3rr0r** [comment]
I can confirm @runo280 instructions work. @YousefSaber as @runo280 mentioned you are doing it wrong.

**Comment by NuLL3rr0r** [comment]
Here is the result using [rastikerdar/vazir-font](https://github.com/rastikerdar/vazir-font).

<img src="https://imgur.com/a/cCL24NO" />

**Comment by MahdiPishguy** [comment]
@NuLL3rr0r  whats `eselect` you are using on command?

**Comment by NuLL3rr0r** [comment]
@MahdiPishguy eselect is a Gentoo/Funtoo thing. You can install the fontconfig module by issuing:

```
$ emerge -atuv app-eselect/eselect-fontconfig
```

Then:

```
$ eselect fontconfig usage
```

For more info on how to use it. The rest is [here](https://github.com/telegramdesktop/tdesktop/issues/5172#issuecomment-451329718).

**Comment by itshaadi** [comment]
> Here is how I fixed this issue:
> 
>     * Close Telegram
> 
>     * Create directory: `~/.fonts`
> 
>     * Add a font with its **different weights** [I used [Vazir](https://github.com/rastikerdar/vazir-font)]
> 
>     * Create file: `~/.fonts.conf` and add these lines to it:
> 
> 
> ```
> <?xml version='1.0'?>
> <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
> <fontconfig>
>  <match target="pattern">
>   <test name="family" qual="any">
>    <string>sans serif</string>
>   </test>
>   <edit mode="assign" binding="same" name="family">
>    <string>Vazir</string>
>   </edit>
>  </match>
>  <dir>~/.fonts</dir>
> </fontconfig>
> ```
> 
>     * Clear font caches:
>       ` fc-cache -f -v`
>       `rm -r ~/.cache/fontconfig_11`
> 
>     * Now open Telegram :)

didn't work for me (ubuntu 18.10 - telegram 1.6.1 installed via snap)
there are no errors tho. it just didn't work on Telegram (I can verify the changes because firefox title bar has changed to IRANSans)

**Comment by NuLL3rr0r** [comment]
@runo280 AFAIK Snaps are sandboxed and kept separate from other parts of your system. So, that's why it won't work. You have to download official telegram from https://telegram.org/dl/desktop/linux for 64-bit and https://telegram.org/dl/desktop/linux32 for 32-bit Linux.

**Comment by YousefSaber** [comment]
can anyone test out whether the issue is still present in Ubuntu 19.04 ?

**Comment by itshaadi** [comment]
it is still present in 19.04. the only workaround for now is runo's method.

**Comment by f4h4m** [comment]
![image](https://user-images.githubusercontent.com/20015479/56834587-0da06580-6887-11e9-9d01-8c5746df2fcc.png)
Still Annoying in Ubuntu 19.04 ( i got this from ubuntu software)

**Comment by ThaSami** [comment]
> Here is how I fixed this issue:
> 
> * Close Telegram
> * Create directory: `~/.fonts`
> * Add a font with its **different weights** [I used [Vazir](https://github.com/rastikerdar/vazir-font)]
> * Create file: `~/.fonts.conf` and add these lines to it:
> 
> ```
> <?xml version='1.0'?>
> <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
> <fontconfig>
>  <match target="pattern">
>   <test name="family" qual="any">
>    <string>sans serif</string>
>   </test>
>   <edit mode="assign" binding="same" name="family">
>    <string>Vazir</string>
>   </edit>
>  </match>
>  <dir>~/.fonts</dir>
> </fontconfig>
> ```
> 
> * Clear font caches:
>   ` fc-cache -f -v`
>   `rm -r ~/.cache/fontconfig_11`
> * Now open Telegram :)

did not solve the issue on Fedora30 using *Arabic Font*.

**Comment by MouamleH** [comment]
Any update on when will it be fixed?

Os: `Ubuntu 18`
TG Version: `1.9.3`

![image](https://user-images.githubusercontent.com/31666226/72535681-02182300-388a-11ea-90a5-e2ba48781901.png)

**Comment by ilya-fedin** [comment]
> Any update on when will it be fixed?

No one knows what the problem is :(
Check with actual static binary, it have been migrated to system fontconfig.
This is good to have an example of text.

**Comment by mostafaznv** [comment]
And this is Farsi (Persian) font on my ubuntu.
yesterday when my telegram got an update (1.9.21), I saw a change in farsi fonts.
now it's hard to read text messages.


![image](https://user-images.githubusercontent.com/7619687/76932695-c25cce80-6900-11ea-8806-c1f8a486a0b1.png)

**Comment by YousefSaber** [comment]
I've some good news and bad news after more than a year of creating this issue the problem has finally been solved in the regular executable Linux application in Telegram version 1.9.21

![image](https://user-images.githubusercontent.com/33742499/76954569-386d2f80-6919-11ea-8944-4d875b3cc41d.png)


the bad news is this problem is now present in the snap app application version 1.9.21

![image](https://user-images.githubusercontent.com/33742499/76954746-8a15ba00-6919-11ea-940e-8620fcdc8a12.png)

for me the Arabic font is distorted 
you may want to close this issue if you want but the problem is present in the snap app also be careful in the future try to prevent this issue from reappearing in future Ubuntu or any Linux distro releases.

I personally prefer the executable application over the snap app since it receives updates faster.

**Comment by mostafaznv** [comment]
And I can confirm the executable one has no problem with farsi (persian) in the latest version (1.9.21)

**Comment by ilya-fedin** [comment]
> the bad news is this problem is now present in the snap app application version 1.9.21

There was a choice between [crashing on some configurations](https://github.com/telegramdesktop/tdesktop/issues/7144) and [ugly fonts](https://github.com/telegramdesktop/tdesktop/pull/7387).

> in the regular executable Linux application

The latest change with fonts was [in 1.9.10](https://github.com/telegramdesktop/tdesktop/commit/28a567986d452a334dfe6ba7d9c998ca9b27d514)

**Comment by pvonmoradi** [comment]
Some additional info:
`Xubuntu 18.04, downloaded via Snap, version : 1.9.21 -  1388 - stable`
It seems for both English and Persian languages it is using the default fallback font of the os, in my case: 
```
$ fc-match 
DejaVuSans.ttf: "DejaVu Sans" "Book"
```
I added an exception rule to  `~/.config/fontconfig/fonts.conf`
```
~/.config/fontconfig $ bat fonts.conf 
───────┬─────────────────────────────────────────────────────────────────────────────
       │ File: fonts.conf
───────┼─────────────────────────────────────────────────────────────────────────────
   1   │ <?xml version="1.0"?>
   2   │ <!DOCTYPE fontconfig SYSTEM "fonts.dtd">
   3   │ <fontconfig>
   4   │     <match target="pattern">
   5   │         <test name="lang" compare="contains">
   6   │             <string>fa</string>
   7   │         </test>
   8   │         <test qual="any" name="family">
   9   │             <string>sans-serif</string>
  10   │         </test>
  11   │         <edit name="family" mode="prepend" binding="strong">
  12   │             <string>nazli</string>
  13   │         </edit>
  14   │     </match>
  15   │ 
  16   │     <match target="pattern">
  17   │         <test name="lang" compare="contains">
  18   │             <string>fa</string>
  19   │         </test>
  20   │         <test qual="any" name="family">
  21   │             <string>serif</string>
  22   │         </test>
  23   │         <edit name="family" mode="prepend" binding="strong">
  24   │             <string>nazli</string>
  25   │         </edit>
  26   │     </match>
  27   │ </fontconfig>
```
Still the same font for Persian (Farsi, IR)
I even removed  the conditionals in the fontcong XML so the farsi font is used universially on the system. Still Snap Telegram didn't repect that and used DejaVu Sans Book

**Comment by pvonmoradi** [comment]
Checking the log, it seems Telegram is using DAOpenSansRegular.ttf fonts with different styles which does not exist anywhere on my system:
```
Primary screen DPI: 157
Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
Font: from ':/gui/fonts/DAOpenSansRegularItalic.ttf' loaded 'DAOpenSansRegularItalic'
Font: from ':/gui/fonts/DAOpenSansBold.ttf' loaded 'DAOpenSansBold'
Font: from ':/gui/fonts/DAOpenSansBoldItalic.ttf' loaded 'DAOpenSansBoldItalic'
Font: from ':/gui/fonts/DAOpenSansSemibold.ttf' loaded 'DAOpenSansSemibold'
Font: from ':/gui/fonts/DAOpenSansSemiboldItalic.ttf' loaded 'DAOpenSansSemiboldItalic'
```

**Comment by ilya-fedin** [comment]
They are embedded in binary

**Comment by pvonmoradi** [comment]
@ilya-fedin So it just ignores all font dirs?
Since Telegram is a Qt app, where does it look for deciding on what font to use?

**Comment by smaznet** [comment]
my fonts problems resolved by installing persian fonts pack

use this script to install fonts : https://github.com/fzerorubigd/persian-fonts-linux

**Comment by ilya-fedin** [comment]
> So it just ignores all font dirs?

yes

> Since Telegram is a Qt app, where does it look for deciding on what font to use on a gtk-based system?

Snap version ignores all the font configuration, read my message that before your first message in this issue.

**Comment by uda** [comment]
I just switched to the flatpak version and the the fonts were loaded properly

**Comment by AliDjango** [comment]
> 
> 
> > the bad news is this problem is now present in the snap app application version 1.9.21
> 
> There was a choice between [crashing on some configurations](https://github.com/telegramdesktop/tdesktop/issues/7144) and [ugly fonts](https://github.com/telegramdesktop/tdesktop/pull/7387).
> 

Persian fonts are nearly unreadable now and I have the same problem with snap package `1.9.22-beta-104-gdeb76f38d`

Isn't there a way to fix this?I mean can I hack it to make it like it was before on my system?

**Comment by ilya-fedin** [comment]
At the moment - no, you can't

**Comment by AliDjango** [comment]
So.I don't know what flatpak is but is it available for armhf? (both flatpak and telegram package)
maybe it doesn't have the same problem there?

**Comment by ilya-fedin** [comment]
> is it available for armhf?

I don't know. You can try.

**Comment by AliDjango** [comment]
> Persian fonts are nearly unreadable now and I have the same problem with snap package `1.9.22-beta-104-gdeb76f38d`

I'll rephrase my sentence. I can't even read at all...nope...It looks like a foreign language to me

can't we make an issue in gtk-whatever or snap asking them to fix that crash problem?

I'll test flatpak in few hours.AFAIK it's not official, is it?

**Comment by ilya-fedin** [comment]
> can't we make an issue in gtk-whatever or snap asking them to fix that crash problem?

This would be awesome, but it is unknown what problem exactly is.

> AFAIK it's not official, is it?

AFAIK it's official

**Comment by AliDjango** [comment]
I can confirm this doesn't have a problem with flatpak version.
but it doesn't support alsa so I can't use it :(
I hope you can find this problem.

**Comment by smaznet** [comment]
Do you installing this font pack?

> my fonts problems resolved by installing persian fonts pack
> 
> use this script to install fonts : https://github.com/fzerorubigd/persian-fonts-linux



> I can confirm this doesn't have a problem with flatpak version.
> But it doesn't support alsa, so I can't use it :(
> I hope you can find the problem.

**Comment by AliDjango** [comment]
> Do you installing this font pack?

I've installed Vazir font and it doesn't use it.it is the same as before.this happens in snap package.

**Comment by YousefSaber** [comment]
I've some bad news the issue has resurfaced again in your executable application for Linux in version 2.0 
![image](https://user-images.githubusercontent.com/33742499/77961232-d24db880-72d9-11ea-9884-7a737ba7ab34.png)
the font is distorted again !!!

**Comment by ilya-fedin** [comment]
A font russian roulette

**Comment by hadisfr** [comment]
https://github.com/telegramdesktop/tdesktop/issues/5172#issuecomment-606245725 is confirmed.

https://github.com/telegramdesktop/tdesktop/issues/5172#issuecomment-464297063 not worked with directly-downloaded non-snap version, in version 2.0.

OS: Ubuntu 19.10

**Comment by ilya-fedin** [comment]
preston forgot to do a full rebuild after testing the fix for snap, I guess. The next version should be ok.

**Comment by hadisfr** [comment]
@ilya-fedin I'm interested in technical details. :D
It seems that all related changes are https://github.com/telegramdesktop/tdesktop/commit/aa4968faaa98ed5e72d8c6bee8316a0ee2ff300a, https://github.com/telegramdesktop/tdesktop/commit/0d58f1c9fa5be2934ae59c71b62e4a261d914b30, and https://github.com/desktop-app/lib_ui/commit/86cb882aab071c2a7933fcfc8d0834e38dca3651 and https://github.com/desktop-app/lib_ui/commit/246aa24530ccc5a5ab06053109a030ceccdb9139 (via https://github.com/telegramdesktop/tdesktop/commit/2feaa85ed943b45647d0a04374879cd19df0af2b). Am I right? Could you describe a little please?

**Comment by ilya-fedin** [comment]
> I'm interested in technical details.

I think, preston, after testing of building with TDESKTOP_USE_FONTCONFIG_FALLBACK, forgot to remove cmake cache and release build has been builded with TDESKTOP_USE_FONTCONFIG_FALLBACK

**Comment by H4medRostami** [comment]
well , to improve this issue you should find The master configuration file - usually /etc/fonts/fonts.conf and copy its content to telegram font config file in :
~/.local/share/TelegramDesktop/tdata/fc-custom-1.conf

**Comment by ilya-fedin** [comment]
Does the issue completely gone with 2.0.1?

**Comment by H4medRostami** [comment]
yep absolutely.

**Comment by H4medRostami** [comment]
I used my own solution and ...
yep absolutely issue solved.

**Comment by ilya-fedin** [comment]
I'm only interested in status without any third-party "solutions"

**Comment by khafan11** [comment]
> Does the issue completely gone with 2.0.1?
no

**Comment by ilya-fedin** [comment]
> no

Installation method?

**Comment by khafan11** [comment]
> > no
> 
> Installation method?
Direct through the site and ArchLinux  package too

**Comment by ilya-fedin** [comment]
> Direct through the site and ArchLinux package too

If you have the issue even with distribution package, then you have fonts misconfiguration at system level

**Comment by khafan11** [comment]
> > Direct through the site and ArchLinux package too
> 
> If you have the issue even with distribution package, then you have fonts misconfiguration at system level

it was working good till this last update !! 
i used Vazir fonts ( yay vazir-fonts ) but now its show ugly font ! i try to change system font too, but same result

**Comment by ilya-fedin** [comment]
> it was working good till this last update !!

Which exactly package did you meant under "ArchLinux package"? telegram-desktop from community repository or telegram-desktop-bin from AUR?

**Comment by khafan11** [comment]
> > it was working good till this last update !!
> 
> Which exactly package did you mean by "ArchLinux package"? telegram-desktop from community repository or telegram-desktop-bin from AUR?

I use the site version more often, anyway
Now I'm back to version 2.0 and the problem is fixed
https://github.com/telegramdesktop/tdesktop/releases/tag/v2.0.0

**Comment by ilya-fedin** [comment]
> Now I'm back to version 2.0 and the problem is fixed

What's going on 1.9.21?

**Comment by khafan11** [comment]
> > Now I'm back to version 2.0 and the problem is fixed
> 
> What's going on 1.9.21?

that was fine too , Problem reverted in version 2.0.1
Of course I wonder why it happened
  Because till last night version 2.0.1 was working properly
  But the morning I turned on the system, it was Messed up

**Comment by ilya-fedin** [comment]
Are you 100% sure that you're not confused between 2.0 and 2.0.1? There are a bug with fonts in 2.0, but 2.0.1 works as 1.9.x.

**Comment by khafan11** [comment]
> Are you 100% sure that you're not confused between 2.0 and 2.0.1? There are a bug with fonts in 2.0, but 2.0.1 works as 1.9.x.
:D yes i'm sure what version am using , I had to disable automatic update as well
![Screenshot_2020-04-03_13-50-42](https://user-images.githubusercontent.com/13505498/78344904-4a560000-75b2-11ea-80ae-a16c40995f84.png)
![Screenshot_2020-04-03_13-50-03](https://user-images.githubusercontent.com/13505498/78344907-4b872d00-75b2-11ea-98cd-3c9c0b761394.png)

**Comment by ilya-fedin** [comment]
> :D yes i'm sure what version am using , I had to disable automatic update as well

Sound like a magic. Can you send log?

**Comment by khafan11** [comment]
> > :D yes i'm sure what version am using , I had to disable automatic update as well
> 
> Sound like a magic. Can you send log?

[log.txt](https://github.com/telegramdesktop/tdesktop/files/4426227/log.txt)

**Comment by AliDjango** [comment]
This is how persian looks right now:
> > ![Screenshot_2020-04-03_13-50-42](https://user-images.githubusercontent.com/13505498/78344904-4a560000-75b2-11ea-80ae-a16c40995f84.png)
> > ![Screenshot_2020-04-03_13-50-03](https://user-images.githubusercontent.com/13505498/78344907-4b872d00-75b2-11ea-98cd-3c9c0b761394.png)

This is the one with font problem:
> ![image](https://user-images.githubusercontent.com/7619687/76932695-c25cce80-6900-11ea-8806-c1f8a486a0b1.png)

which one of these are you seeing right now?

**Comment by AliDjango** [comment]
@ilya-fedin this is unrelated but...is there a way to change the font on windows? I just want to see how different fonts change user experience.

**Comment by ilya-fedin** [comment]
> log.txt

Is this a log from problem version? If not, it is useless.

**Comment by ilya-fedin** [comment]
> is there a way to change the font on windows?

no

**Comment by khafan11** [comment]
> > log.txt
> 
> Is this a log from problem version? If not, it is useless.
I thought you wanted version 2
here is 2.0.1
[log.txt](https://github.com/telegramdesktop/tdesktop/files/4428264/log.txt)

**Comment by khafan11** [comment]
> > log.txt
> 
> Is this a log from problem version? If not, it is useless.
I thought you wanted version 2
here is 2.0.1
[log.txt](https://github.com/telegramdesktop/tdesktop/files/4428270/log.txt)

**Comment by Aokromes** [comment]
> @ilya-fedin this is unrelated but...is there a way to change the font on windows? I just want to see how different fonts change user experience.

https://github.com/opumps/TGFont

**Comment by ilya-fedin** [comment]
> log.txt

What does the bad font look like?

**Comment by khafan11** [comment]
> > log.txt
> 
> What does the bad font look like?
You can compare it with the [previous one](https://github.com/telegramdesktop/tdesktop/issues/5172#issuecomment-608331035)
![Screenshot_2020-04-03_20-07-47](https://user-images.githubusercontent.com/13505498/78378873-d41fc080-75e6-11ea-9378-18326e48d28b.png)

**Comment by ilya-fedin** [comment]
> You can compare it with the [previous one](https://github.com/telegramdesktop/tdesktop/issues/5172#issuecomment-608331035)

lol. It's just difference with subpixel rendering. Tweak your system settings until fonts will look good.

**Comment by ilya-fedin** [comment]
https://wiki.archlinux.org/index.php/Font_configuration

**Comment by ilya-fedin** [comment]
Ok, does anyone really have this issue (font should be chosen wrong, not just a difference with anti-aliasing)?

**Comment by SoheilShahbazian** [comment]
Telegram has lots of problem with persian(farsi) font
the above images not relevance to monitors' rendering

**Comment by ilya-fedin** [comment]
> the above images not relevance to monitors' rendering

No, they are related. There is bug on 2.0.0 that adds custom fonts.conf. For almost of you this leads to the use of FreeMono for almost all glyphs. But he has a normal font and he sees only the difference with the anti-aliasing settings. On 2.0.1, system fonts.conf is used, as on previous versions, but he believes that fonts behave worse, but that's wrong, they just reverted to the state of before 2.0.0. He can configure fonts as he want, including as in custom fonts.conf.

**Comment by ilya-fedin** [comment]
That's the settings from custom fonts.conf:
```
<?xml version='1.0'?>
<!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
<fontconfig>
	<match target="font">
	<edit mode="assign" name="antialias">
		<bool>true</bool>
	</edit>
	<edit mode="assign" name="hinting">
		<bool>true</bool>
	</edit>
	<edit mode="assign" name="hintstyle">
		<const>hintslight</const>
	</edit>
	<edit mode="assign" name="lcdfilter">
		<const>lcddefault</const>
	</edit>
	<edit mode="assign" name="rgba">
		<const>rgb</const>
	</edit>
	</match>
</fontconfig>
```
You can put it into ~/.config/fontconfig/conf.d/99-default.conf and your system will use the anti-aliasing settings from custom fonts.conf

**Comment by AliDjango** [comment]
> Here is how I fixed this issue:
> 
> * Close Telegram
> * Create directory: `~/.fonts`
> * Add a font with its **different weights** [I used [Vazir](https://github.com/rastikerdar/vazir-font)]
> * Create file: `~/.fonts.conf` and add these lines to it:
> 
> ```
> <?xml version='1.0'?>
> <!DOCTYPE fontconfig SYSTEM 'fonts.dtd'>
> <fontconfig>
>  <match target="pattern">
>   <test name="family" qual="any">
>    <string>sans serif</string>
>   </test>
>   <edit mode="assign" binding="same" name="family">
>    <string>Vazir</string>
>   </edit>
>  </match>
>  <dir>~/.fonts</dir>
> </fontconfig>
> ```
> 
> * Clear font caches:
>   ` fc-cache -f -v`
>   `rm -r ~/.cache/fontconfig_11`
> * Now open Telegram :)

this doesn't work with normal binaries from telegram website on ubuntu.

i created `./fonts/fonts.conf` and added these lines to it and installed vazir fonts to `./fonts`.
any ideas?

@ilya-fedin ?

**Comment by ilya-fedin** [comment]
~/.config/fontconfig/conf.d/99-default.conf

**Comment by AliDjango** [comment]
@ilya-fedin thanks.i forgot to write the font name with capital letter and that was the problem.not it works
can i also change english fonts to something else?

**Comment by ilya-fedin** [comment]
no, you can't without patching the sources

**Comment by AliDjango** [comment]
@ilya-fedin does it by default use open_sans or noto_sans?
im confused because to me it seems a little different than windows version binary

**Comment by ilya-fedin** [comment]
Open Sans

**Comment by YousefSaber** [comment]
I'm going to close this issue after nearly more than a one and half year of opening since the issue is fixed on Ubuntu 20.04 with telegram version 2.01 in both the executable application and snap app ( didn't test the flatpak app ) I'll reopen this issue if it surfaced again. 
![image](https://user-images.githubusercontent.com/33742499/80158295-6d2f6f00-85c8-11ea-8850-aad5ab0ccc2d.png)
