### ISSUE TITLE
Auto update does not work on linux.

### ISSUE THREAD

**Issue by ManuelSchneid3r** [telegramdesktop/tdesktop#555]
It downloads and tries to restart. Nothing happens. My naive guess is that there are problems with access rights, since  I was not asked to enter the root passwd.

**Comment by auchri** [comment]
Look #540

**Comment by ManuelSchneid3r** [comment]
Thank you.

**Comment by ManuelSchneid3r** [comment]
Oh didnt see that #540 is already closed. Imho the solution to #540 is not a proper one, since this is not really the way to go on a multiuser system. Please ask for the root password and place the binary in `/usr/bin`.

**Comment by kenetik** [comment]
@ManuelSchneid3r 

I believe this will be different per distro as well, however it's more than just the 'Telegram' binary file that's altered on an update. From what I see, 3 files are affected. You could also own it to root and leave permissions as 777 for any user rather than just the 'single user'.

**Comment by angelbladex** [comment]
ohhhh i had same problem on Arch and solved via comment from @kenetik on #540

**Comment by auchri** [comment]
https://github.com/telegramdesktop/tdesktop/issues/540#issuecomment-78043543 :smile:

**Comment by ManuelSchneid3r** [comment]
Yes some things differ between the distro (e.g. /sbin /usr/sbin on debian) but I dont know any distro which does _not_ use /usr/bin. It is the primary place for user accessible apps. Well finally I stopped using autoupdate and receive telegram from the AUR. (using yaout -Syu for an update)

**Comment by Vdragon** [comment]
At the meantime just put in a user's directory like ~/Software/Telegram

**Comment by ManuelSchneid3r** [comment]
I use the packages version now and cant say if its still a problem. So Ill close it.
