### ISSUE TITLE
Videos on 4K resolution have low FPS

### ISSUE THREAD

**Issue by EugeneRymarev** [telegramdesktop/tdesktop#6312]
### Steps to reproduce
1. Set resolution 4K (3840 x 2160)
2. Open any video (stream or saved)
3. Make it on fullscreen

### Expected behaviour
Normal video playing
### Actual behaviour
Low FPS video playing
### Configuration
**Operating system:**
Windows 10
**Version of Telegram Desktop:**
Current last stable
**Used theme**:
Default

**Comment by undbsd** [comment]
Same thing happens with 1280x720 and 1360x768 videos

**Comment by EugeneRymarev** [comment]
> Same thing happens with 1280x720 and 1360x768 videos

Any video resolution fullscreen on 4k monitor resolution.

**Comment by turcandan** [comment]
> on 4k monitor

I have the same problem with a Full HD video on a Full HD monitor(laptop), but not with all of them, tried many FHD videos.

**Comment by Aokromes** [comment]
very likely it needs hardware acceleration.

**Comment by turcandan** [comment]
> 
> 
> very likely it needs hardware acceleration.

That's true, I'm encountering this only when I receive videos recorded in H265(HEVC).

**Comment by OctoNezd** [comment]
Any update on this issue? HEVC videos playback properly on mobile client.
ffmpeg args: `-c:v hevc_qsv -q QUALITY -r 60 -acodec copy `
Channel with sample videos playback of which is broken: https://t.me/tdesktophevcbroken

**Comment by turcandan** [comment]
No update, still the same lags when watching a video sent from a smartphone recorded in HEVC.

**Comment by Aokromes** [comment]
@john-preston maybe this can help you to close this issue :)
https://github.com/wang-bin/QtAV

**Comment by megapro17** [comment]
Where is any fix?? Actually telegram doesn't accelerate any videos AT ALL. It is huge issue!

**Comment by tsumeone** [comment]
This is the only app I'm aware of with such a bad video player in 2020.  If my 3 year old phone can play back 4k60 HEVC video clips using the android Telegram app, then the desktop version with a high end CPU and GPU should be able to.

**Comment by megapro17** [comment]
On desktop macOS version it actually accelerates... On other platforms you have to use this trash client

**Comment by ilya-fedin** [comment]
>  If my 3 year old phone can play back 4k60 HEVC video clips using the android Telegram app, then the desktop version with a high end CPU and GPU should be able to.

On android when you playing video, acceleration is done automatically by the system. For cross-platform desktop client you need to write a lot of code that will interact with GPU and with system API of each supported system.

**Comment by megapro17** [comment]
Bullshit, you just need to add ffmpeg, and it can deal with it easily

чт, 4 июн. 2020 г., 14:32 ilya-fedin <notifications@github.com>:

**Comment by ilya-fedin** [comment]
> Bullshit, you just need to add ffmpeg, and it can deal with it easily

tdesktop already uses ffmpeg, I can't see hardware acceleration

**Comment by ilya-fedin** [comment]
firefox uses ffmpeg too and they added hardware acceleration on linux only a month ago and only on Wayland.
If ffmpeg deal with it easliy then it is strange.

**Comment by megapro17** [comment]
so where is any fix? it is also drains battery on notebooks very fast

**Comment by ilya-fedin** [comment]
> so where is any fix?

well, let's implement hardware decoding (if you think it is very simple) and everyone say thank you for you :)

**Comment by megapro17** [comment]
@ilya-fedin telegram doesn't accept any pull requests from people which not working in the company

**Comment by ilya-fedin** [comment]
> telegram doesn't accept any pull requests from people which are not working in the company

that's false, I'm improving Linux support starting from January. You can make pull requests as soon as they doesn't add any new interface elements (like options in settings)
https://github.com/telegramdesktop/tdesktop/blob/dev/.github/CONTRIBUTING.md

**Comment by Aokromes** [comment]
> @ilya-fedin telegram doesn't accept any pull requests from people which are not working in the company

lies, you only need to check the amount of pull requests from ilya (who is not telegram member)

**Comment by megapro17** [comment]
> doesn't add any new interface elements (like options in settings)

so, implementing hw acceleration requires optional switch to disable it as done in any browser

**Comment by ilya-fedin** [comment]
> so, implementing hw acceleration requires optional switch to disable it as done in any browser

It is not required by the algorithm :)

**Comment by EugeneRymarev** [comment]
I don't know from which version, but for me works fine at this moment. Trying on 1280x720 video.

**Comment by megapro17** [comment]
https://github.com/telegramdesktop/tdesktop/issues/7950 i'm stuck here...

**Comment by megapro17** [comment]
> I don't know from which version, but for me works fine at this moment. Trying on 1280x720 video.

Nothing changed, it still doesn't use gpu at all

**Comment by ashellunts** [comment]
@ilya-fedin @Aokromes is ffmpeg used for h265 decoding?

H265 hardware accelerated decoding is supported on Intel CPUs with Skylake or fresher architecture.

**Comment by ashellunts** [comment]
> > I don't know from which version, but for me works fine at this moment. Trying on 1280x720 video.
> 
> Nothing changed, it still doesn't use gpu at all, i checked in task manager. try to watch high bitrate high resolution video

I suggest that the issue reported by @EugeneRymarev was because of rendering, not decoding. He didn't mention HEVC at all, and said the issue is reproduced in full screen mode.

**Comment by ashellunts** [comment]
I have tried playing videos from https://t.me/tdesktophevcbroken.

When video is played inside chat, it works much better, though still lags. In fullscreen -- 1fps or less. So that means there exist 2 issues:
- Slow software HEVC decoding.
- Some problem with rendering decoded HEVC video in full screen mode.

-

**Comment by ashellunts** [comment]
I have tried playing [this HEVC video](https://t.me/tdesktophevcbroken/3) using ffplay. Both software and hardware decoders can play the video in full screen in 60 fps.

```
ffplay -vcodec hevc_qsv -i q35.mp4 -v verbose # intel qsv hw deocder
ffplay -vcodec hevc -i q35.mp4 -v verbose # sw deocder
```

**Comment by ashellunts** [comment]
> #7950 i'm stuck here...

Have you started working on the issue?

**Comment by ilya-fedin** [comment]
> I guess that the issue reported by @EugeneRymarev was because of rendering, not decoding

Yeah, that very likely, since tdesktop uses only software rendering and tdesktop plays videos with slideshow even that are played smoothly by Firefox (which doesn't have hardware decoding on Linux)

I tried to activate QOpenGLWidget on Linux, but didn't notice any changes...

**Comment by ilya-fedin** [comment]
>  is ffmpeg used for h265 decoding?

it is used for decoding of everything

**Comment by ashellunts** [comment]
I can try to work on this issue.

**Comment by ilya-fedin** [comment]
> I can try to work on this issue.

I think everyone here will be thankful to you, including me :)

**Comment by ashellunts** [comment]
Ok, let's try. 1st task - to build. Build instructions are quite long and complicated. Maybe someone already has scripts to automate build setup? Also what version of Visual Studio is recommended now? People were complaining about latest 16.6 version.

**Comment by EugeneRymarev** [comment]
> 16.6 version

16.7 preview

**Comment by ilya-fedin** [comment]
> Build instructions are quite long and complicated.

I made a possibility to build with system packages on Linux and macOS (with brew). Don't know any way to make build simpler on Windows.

> Also what version of Visual Studio is recommended now?

16.5 or 16.7 preview

**Comment by megapro17** [comment]
ffmpeg in telegram has enabled hw accel support, it seems that it only needed to be enabled in telegram, right before video initialization https://ffmpeg.org/doxygen/3.4/hw__decode_8c_source.html

**Comment by ashellunts** [comment]
> ffmpeg in telegram has enabled hw accel support, it seems that it only needed to be enabled in telegram, right before video initialization https://ffmpeg.org/doxygen/3.4/hw__decode_8c_source.html

From my tests it looks like the problem (this issue) is not in decoding (or only decoding), it is something in rendering.

**Comment by ashellunts** [comment]
Trying to build Telegram. Now stuck with [QT build](https://github.com/telegramdesktop/tdesktop/issues/8294). I would appreciate for help.

**Comment by ashellunts** [comment]
Finally built Telegram!

**Comment by megapro17** [comment]
Wtf incredible

**Comment by john-preston** [comment]
@ashellunts 

I've tried this code from hw_decode.c example. I couldn't make it decode my sample 4K H264 video. It did init the hw decoder successfully and then it failed with "invalid data provided" on the first data packet that I've avcodec_send_packet-d.

I've tried linking with pre-built .dll-s from ffmpeg.org for 4.2.1 version and I got exactly the same - for both "d3d11va" and "dxva2" it initialized successfully and then failed on the first avcodec_send_packet call. Maybe my file is bad, but it works as expected without hw accelerated decoder, and I have no idea how to distinguish between those to at least provide a software-decoder fallback.

Then I've taken hw_decode.c example from 4.3.1 release tag and tried it (it had a few changes), but still I was not able to start decoding that 4K H264 video. If I comment two lines that attempt to enable the hardware decoding:

![image](https://user-images.githubusercontent.com/17900494/88534292-d1732c00-d018-11ea-8cc9-17022752b2b3.png)

Then the first and the next avcodec_send_packet calls succeed. So I don't know how I can use that.

**Comment by ilya-fedin** [comment]
> I've tried this code from hw_decode.c example.

I guess you wanted to mention @megapro17

**Comment by megapro17** [comment]
Noo I'm not a expert

**Comment by ilya-fedin** [comment]
> Noo I'm not a expert

You linked the example :D

**Comment by ilya-fedin** [comment]
"Bullshit, you just need to add ffmpeg, and it can deal with it easily" :copyright: :registered: :tm:

**Comment by ashellunts** [comment]
I have also tried and I saw that avcodec_receive_frame succeeded and I have added copying from hw surface to sw surface and it also succerded. But due to some reason rendering still didn't work.

But I have not checked return code from avcodec_send_packet, I will check today.

**Comment by ashellunts** [comment]
Good news: with small changes hw decoder works in in-chat view.
Bad news: it doesn't work yet in full screen view.

**Comment by megapro17** [comment]
@ashellunts can you show what you changed?

**Comment by ashellunts** [comment]
@megapro17 Sure, will push branch today. Didn't have much time recently to work on the issue.

**Comment by ashellunts** [comment]
@megapro17 here is the branch https://github.com/ashellunts/tdesktop/commits/hw_decoder

**Comment by john-preston** [comment]
@ashellunts Btw to fix the compiler error (regression) you can uncomment the code and change

auto endpoint = TgVoipEndpoint{

To

TgVoipEndpoint endpoint = {

I'm tracking the issue in Visual Studio bugtracker about that regression.

**Comment by ashellunts** [comment]
@john-preston thank you.

**Comment by AetherEternity** [comment]
Current software implementation of HEVC decoding in tdesktop uses only one thread (which is a pain to see on a 24-thread cpu). 
Is there an easy way to enable multithread support for it while @ashellunts is experimenting with hw?

**Comment by john-preston** [comment]
@AetherEternity It will be done in the next version.

**Comment by ashellunts** [comment]
@john-preston have you already got the fix for using more threads in sw HEVC? I can work on it.

**Comment by john-preston** [comment]
@ashellunts This should do it:

https://github.com/telegramdesktop/tdesktop/commit/361b99b0c9c9f69bc8479a4413dbe62113405734#diff-df2c819744fe7d25b5e212988c7e7bf9R178

**Comment by kabachook** [comment]
Any news on hw accel?

**Comment by Aokromes** [comment]
one fix was merged on jul 28

**Comment by ilya-fedin** [comment]
> one fix was merged on jul 28

I don't see any PRs at Jul 28

> Any news on hw accel?

No news, and they won't be most likely, implementing hw accel is a really hard task that require to work with GPU.

**Comment by kabachook** [comment]
So sad 😭 
My CPU goes to 100% on HEVC and 50% on h264

**Comment by megapro17** [comment]
It's still not possible to build telegram under stable version of vs? 😂

**Comment by Tuxino88** [comment]
> > If my 3 year old phone can play back 4k60 HEVC video clips using the android Telegram app, then the desktop version with a high end CPU and GPU should be able to.
> 
> On android when you playing video, acceleration is done automatically by the system. For cross-platform desktop client you need to write a lot of code that will interact with GPU and with system API of each supported system.

Gstreamer uses the VA-API, use gstreamer then

**Comment by ilya-fedin** [comment]
> Gstreamer uses the VA-API, use gstreamer then

Given that Telegram has Windows as its primary system, uses MSVC to build and gstreamer's Windows support is bad...

**Comment by Tuxino88** [comment]
> > Gstreamer uses the VA-API, use gstreamer then
> 
> Given that Telegram has Windows as its primary system, uses MSVC to build and gstreamer's Windows support is bad...

I understand, in Tdesktop components I also see ffmpeg. ffmpeg supports vaapi

**Comment by ilya-fedin** [comment]
> ffmpeg supports vaapi

the problem is that it is too hard too implement hardware decoding with it, please read entire discussion. Of course you can implement and PR it if you want.

**Comment by mzji** [comment]
Maybe we could try to offload the video/audio stream to another player specified by the user which may support hareware acceleration? For example, streaming video via a special file, or a pipe, or a local HTTP endpoint, or even by shared memory…

**Comment by ilya-fedin** [comment]
@mzji PoC would be highly appreciated

**Comment by sgon00** [comment]
This should be a bug instead of enhancement. I am so surprised when I see enhancement label on it. I don't have any high CPU load issues in other chat apps (instant messengers).

**Comment by sgon00** [comment]
Sorry that one more comment. Since all other issues are closed because of this one, can we change the issue's title too? This issue is not about 4K video and low FPS. For me, I get a very high cpu load when playing small resolution videos. Thanks a lot.

**Comment by ilya-fedin** [comment]
> I don't have any high CPU load issues in other chat apps (instant messengers).

Other chat applications are using Electron and get hardware acceleration for free. This is not the case for applications implemented with C++ and Qt.

> This should be a bug instead of enhancement.

No, since this requires implementing of a very big feature.

**Comment by Tuxino88** [comment]
> Sorry that one more comment. Since all other issues are closed because of this one, can we change the issue's title too? This issue is not about 4K video and low FPS. For me, I get a very high cpu load when playing small resolution videos. Thanks a lot.

The problem is : no one contributes on that. Everyone wants but nobody gives , work stinks

**Comment by ilya-fedin** [comment]
Exactly. No one here has enough knowledge/time to implement hardware acceleration.

**Comment by sgon00** [comment]
@Tuxino88 thanks for the reply. Regardless whether the issue will be fixed or not, the title should be changed to a proper one. Anyway, I am using another client which has hardware acceleration as a workaround for now.

**Comment by Tuxino88** [comment]
> @Tuxino88 thanks for the reply. Regardless whether the issue will be fixed or not, the title should be changed to a proper one. Anyway, I am using another client which has hardware acceleration as a workaround for now.

can you tell me which one?  I would be interested because I use the laptop and the battery for me is vital

**Comment by sgon00** [comment]
> > @Tuxino88 thanks for the reply. Regardless whether the issue will be fixed or not, the title should be changed to a proper one. Anyway, I am using another client which has hardware acceleration as a workaround for now.
> 
> can you tell me which one? I would be interested because I use the laptop and the battery for me is vital

It has already been mentioned in this thread. I don't know if it's proper to mention another app here or not. Anyway, it's TelegramSwift, you have to run MacOS. Nowadays, it's not very hard to run MacOS in a PC.

Btw, I remembered telegram desktop does not have a high cpu load when I ran it on Linux. I am not using it right now, so I might be wrong. 
(I never use windows, so I can not comment on that).

**Comment by Tuxino88** [comment]
> Exactly. No one here has enough knowledge/time to implement hardware acceleration.

I imagine the difficulty, but why do you keep neglecting the web version? by implementing videos, calls and all the various devilry you would have solved many complaints by delegating the use of the browser

**Comment by ilya-fedin** [comment]
> I imagine the difficulty, but why do you keep neglecting the web version?

"you"? I'm not a part of Telegram team.

**Comment by Aokromes** [comment]
> > Exactly. No one here has enough knowledge/time to implement hardware acceleration.
> 
> I imagine the difficulty, but why do you keep neglecting the web version? by implementing videos, calls and all the various devilry you would have solved many complaints by delegating the use of the browser

now you have webk and webz much more advanced than the old web version.

**Comment by john-preston** [comment]
@EugeneRymarev I hope with OpenGL renderer it should be much better now.

**Comment by megapro17** [comment]
![dem_60e583dd00b7e](https://user-images.githubusercontent.com/16743370/124745490-8bad2c00-df28-11eb-9d67-152e9f2d5c20.png)

**Comment by thisVioletHydra** [comment]
lags after full screen!

**Comment by Tuxino88** [comment]
I suppose that with the latest update this problem can be considered solved

**Comment by sgon00** [comment]
@Tuxino88 Can you please tell me which code commit solves this issue? Thanks a lot.
