### ISSUE TITLE
[Bug] - See who is online straight from the chat list, not disappear until there is mouse movement

### ISSUE THREAD

**Issue by Jeronimo17** [telegramdesktop/tdesktop#6410]
The connected user does not disappear until there is mouse movement above the user (I do not know if it only happens with users with thumbtacks)
![Fallo](https://user-images.githubusercontent.com/4985763/63062688-167e7b00-befa-11e9-9cf0-ce9a2a66e6b0.png) 
Linux Mint 19.2 64bit XFCE

**Comment by Geobert** [comment]
I confirm this

**Comment by Jeronimo17** [comment]
Does anyone fix something so simple ?, I see many updates of the application and follow the point without taking off and I think the person is still there

**Comment by Laiteux** [comment]
I confirm this

**Comment by Jeronimo17** [comment]
I can't believe they haven't fixed this yet, after a lot of updates and affecting everyone and being quite annoying

**Comment by Laiteux** [comment]
> I can't believe they haven't fixed this yet, after a lot of updates and affecting everyone and being quite annoying

Yeah...

**Comment by Laiteux** [comment]
😴

**Comment by Jeronimo17** [comment]
finally fixed it seems

**Comment by Laiteux** [comment]
No, not fixed. I'm using v2.0.1, please reopen.

![](https://share.laiteux.dev/yfubrc)

**Comment by Jeronimo17** [comment]
fixed on linux only?

**Comment by Jeronimo17** [comment]
I was wrong, it is not fixed in linux either

**Comment by Jeronimo17** [comment]
![Actualizar](https://user-images.githubusercontent.com/4985763/80861665-4a5c2500-8c70-11ea-82ef-77f0848fcb0f.png)
It should not be difficult, make the same system that updates the status under the name hide or show the round icon

**Comment by Optiligence** [comment]
the icon status is updated, but it doesn’t trigger a rerender
that’s why hovering it fixes it

**Comment by Laiteux** [comment]
Would you be able to make any pull request fixing this?

**Comment by Jeronimo17** [comment]
Maybe a refresh of the window?
For this to work wrong, I prefer that the icon never appear

**Comment by Jeronimo17** [comment]
That I know it has not been fixed

**Comment by DeltaTimo** [comment]
Does this issue only appear when hiding online/last seen status?
I've been experiencing the same for a while but I haven't had the time to get the source to work and fix this, but every bit of information helps.

**Comment by Laiteux** [comment]
Hello! No, it's been happening to me for over a year now and I never hide my status nor the other people I talk to (such as my gf), this is really looking like a rendering issue

**Comment by akorb** [comment]
I agree with @Laiteux . It's also 100% consistent. It happens every time and not only sometimes. This should make it easier to hunt it down. For me it happens on Linux and Windows. I don't know about other systems.

**Comment by Jeronimo17** [comment]
The problem continues after many updates :-1:  If it is graphics, is not a general refresh of the screen possible?

**Comment by Jeronimo17** [comment]
It seems that it is finally fixed

**Comment by Laiteux** [comment]
> It seems that it is finally fixed 

Can you link the commit fixing this bug? I can't try to reproduce anymore since I'm on a single screen now

**Comment by Jeronimo17** [comment]
I do not know it, I have only seen that the last update the displacement of what is sent is faster and it seems that this fault is no longer there

**Comment by Jeronimo17** [comment]
I haven't said anything

**Comment by Jeronimo17** [comment]
The error continues, I think it also happens in win10.

**Comment by Laiteux** [comment]
😩

**Comment by Jeronimo17** [comment]
Is it not better to remove the icon if it cannot be fixed, it is very annoying?

**Comment by Laiteux** [comment]
![image](https://user-images.githubusercontent.com/33204743/196576043-1f5e150d-1b00-4826-9870-0176bd35db67.jpeg)

**Comment by ilya-fedin** [comment]
The problem here is the protocol doesn't have offline event, so tdesktop needs to instantiate a timer for every online user in the list to call a redraw according to the `(offline timeout constant - (current time - last user online time))`. This is not really trivial as a non-accurate implementation will trigger too much timers what will cause CPU drain.

The issue is not of high priority while needs a considerable amount of time to write a fix, so it may be resolved not any time soon. I guess the removing of the dot is not going to happen either as it's a part of the design.

**Comment by akorb** [comment]
But I think there is already an event happening, because if a person was online and then goes offline, the text below the person's name changes from 'online' to 'last seen recently'. Couldn't another callback for this event update the dot?

**Comment by ilya-fedin** [comment]
The history widget (chat view) creates a timer for the currently opened dialog. Chat list would need timers for every online person in the list and it should be capable to destruct/create timers on demand when something changes (e.g. a mouse move already caused redraw or there's an event another user is online). In other words, this requires creating a timer manager that should operate very accurate and don't leak the timers.

**Comment by ilya-fedin** [comment]
I'm not sure we can distinguish the ones on the screen from the ones that aren't...

**Comment by ilya-fedin** [comment]
And if we can, it's yet another complication for the future timer manager as it would has to update the timers during scrolling

**Comment by Jeronimo17** [comment]
I don't know how it is programmed, but what you tell me happens when you mouse over everything is updated correctly. can't the same timer as last time connected also update the icons?

**Comment by ilya-fedin** [comment]
what do you mean by 'same timer as last time connected'? There's no timer, that's what I explained in previous messages and that's what needs to be implemented for this to be resolved. But as I also said, it's not so trivial as one might think.

**Comment by Jeronimo17** [comment]
I don't understand, without doing anything if you update the status from online to last connected so long ago. But the green icons do not take advantage of that update that I do not know who triggers it and only updates by moving the mouse over Telegram.

**Comment by john-preston** [comment]
@Jeronimo17 There is no event about a user becoming not online - it is just time that passed beyond the point he was online. The fact that user is not online at the current time is checked when the chat row is painted. So when you put your mouse over the chat row it invokes the repainting and checks the current online status.

**Comment by ilya-fedin** [comment]
> without doing anything yes you update the status from online to last connected so long ago

Have you read https://github.com/telegramdesktop/tdesktop/issues/6410#issuecomment-1285097282? It has answer to this.

**Comment by Optiligence** [comment]
i looked into the code a while ago
from what i could tell the animation to hide the dot gets triggered, but it’s stopped from getting rendered somewhere along the way

@ilya-fedin 
> the currently opened dialog
the issue does happen for the currently open chat, in case you imagine that this is not the case (it reads like that)

**Comment by ilya-fedin** [comment]
> the issue does happen for the currently open chat, in case you assume that not to be the case (it reads like that)

But people in this thread post that the chat view has no issue: https://github.com/telegramdesktop/tdesktop/issues/6410#issuecomment-622932008.

**Comment by Optiligence** [comment]
the dot issue is also present for the active chat
only talking about that

**Comment by Optiligence** [comment]
as far as i can tell there are signals in the program for when any user goes offline
what doesn’t work is having the ui actually render the animation that’s initiated

**Comment by ilya-fedin** [comment]
Apparently you've misread my post, "the currently opened dialog" is about the chat view and the text down the username in it.

**Comment by ilya-fedin** [comment]
> as far as i can tell there are signals in the program for when any user goes offline

No, there's no such signals, there's only a timer in the HistoryWidget that updates the status text in chat view. It won't work for the chat list as it's only about one dialog while chat list has a lot of dialogs and every of them should have a timer to repaint. HistoryWidget is also doesn't always exist.

**Comment by Laiteux** [comment]
Excuse me if I'm misunderstanding, really, but wouldn't it be possible to have a timer for each channel shown on the screen?

Ok, I get it that it's quite a bit of work and would take some time, but I have to agree this issue was  quite a huge pain in the ass back when I was still using a double monitor setup, with Telegram being open 24/7 on one of them. There's a reason as to why I'm still commenting on this issue three years later (:

About detecting which chats are actually visible in the list, don't come and tell me this isn't possible. Out of the many things the developers are able to achieve, you can't tell me this is out of their reach :D

**Comment by ilya-fedin** [comment]
Well, you have a choice: wait until someone else implement it (maybe years) or implement on your own.

**Comment by john-preston** [comment]
@Laiteux It is possible to fix. I'll try to add it for the next release, but I may get caught up in some other things again.

**Comment by Laiteux** [comment]
Wahooo!

**Comment by Laiteux** [comment]
John, you're insane. Thank you so much! <3 <3

**Comment by john-preston** [comment]
@Laiteux I'm not absolutely sure it is fixed, but we'll see in the next version.

**Comment by Optiligence** [comment]
@ilya-fedin this was the signal i was referencing
https://github.com/telegramdesktop/tdesktop/commit/ed895ace66786e706f6f99ee721d3abc9458fe07#diff-062ac533f8eca65eabd17fa0d24d844acb61034f7aed774cc5329adf4f18d596R1857

>Apparently you've misread my post

I was rather trying to facilitate understanding that your conversation partners in this issue where saying that **something** _was_ indeed updated when a user went offline and that it should therefore be possible to update the dot as well. 

@john-preston thanks for working on it!

**Comment by ilya-fedin** [comment]
@Optiligence it's a signal for online status, but it's not emitted when the user goes offline

**Comment by Optiligence** [comment]
@john-preston unfortunately the change didn’t fix it

i took some more time to finally get to the bottom of this

@ilya-fedin i don’t know why you are so eager to argue
- `peerUpdated` is definitely called when a user goes offline
- there already exists an ` _idleFinishTimer`
- the only thing that was broken was the `updateCallback` that’s supposed to allow the animation to trigger a rerender

**Comment by john-preston** [comment]
_idleFinishTimer is about currently authorized user.

**Comment by john-preston** [comment]
I can't understand how https://github.com/Optiligence/tdesktop/commit/8b76d3ba8d86b2bde16989f38fe4c673bcd86d6f can fix the bug. The check for visible means we don't see the row on the screen and update the status of the row that needs to be scrolled to for being seen.

**Comment by Optiligence** [comment]
`repaintDialogRowCornerStatus(history);` doesn’t do what it’s supposed to
replacing that with `this->repaint()` is already enough
i didn’t dig deeper to understand why

**Comment by john-preston** [comment]
Ah, I see, the real part is replacing repaintDialogRowCornerStatus with repaint, not the visibility check removal.

But this is very costly :( I need to find out why the repaint method doesn't work.

**Comment by Optiligence** [comment]
the animation doesn’t happen that often and it’s not like it’s repainting the whole window, so i didn’t bother :see_no_evil: 

but it sure is better to properly fix it^^

**Comment by john-preston** [comment]
I found, it was a very stupid regression. Funny thing I spent some time testing it and didn't see this.

**Comment by Jeronimo17** [comment]
Finally, I think I see it working
