### ISSUE TITLE
Failed to load module "canberra-gtk-module": Telegram Desktop 1.9.9-4-ga25792187 not open on Ubuntu 18.04.4 LTS

### ISSUE THREAD

**Issue by ioan-cristea** [telegramdesktop/tdesktop#7144]
### Steps to reproduce
1. Ubuntu 18.04.4 LTS
2. Install Telegram Desktop 1.9.9-4-ga25792187 from SnapStore
3. Try to open

### Expected behaviour
To open

### Actual behaviour
Don't open

### Configuration
**Operating system:**
Ubuntu 18.04.4 LTS
**Version of Telegram Desktop:**
1.9.9-4-ga25792187
**Used theme**:
-

<details><summary><b>Console run telegram-desktop</b>:</summary>
Gtk-Message: 09:55:48.110: Failed to load module "canberra-gtk-module"
Gtk-Message: 09:55:48.122: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
</details>

**Comment by Aokromes** [comment]
try updating to 1.9.10

**Comment by ilya-fedin** [comment]
> Gtk-Message: 09:55:48.110: Failed to load module "canberra-gtk-module"

that's not an error. snap runs update-desktop-database before app start, it may take some time.

**Comment by ygcaicn** [comment]
Ubuntu 19.10 have the same problem.
```
Gtk-Message: 21:14:17.607: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:14:17.622: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Fontconfig warning: FcPattern object width does not accept value [0.61998 1.29999)
Segmentation fault (core dumped)
```

**Comment by maksymkpr** [comment]
Same on Fedora 31

`Gtk-Message: 16:00:07.590: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:00:07.590: Failed to load module "pk-gtk-module"
Gtk-Message: 16:00:07.592: Failed to load module "canberra-gtk-module"
Gtk-Message: 16:00:07.592: Failed to load module "pk-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Fontconfig warning: FcPattern object width does not accept value [75 100)
[1]    8947 segmentation fault (core dumped)  telegram-desktop
`

**Comment by ioan-cristea** [comment]
I confirm is not a problem from module canberra-gtk-module.
Try to uninstall the app, reboot desktop, and reinstall the stable version from snap.
Take some time when you open the app.

**Comment by ygcaicn** [comment]
> I confirm is not a problem from module canberra-gtk-module.
> Try to uninstall the app, reboot desktop, and reinstall the stable version from snap.
> Take some time when you open the app.

I have tried to the method, but still have the same problem.

```
✼ jachin@hp-pavilion-laptop:~$ snap run telegram-desktop
Gtk-Message: 10:33:23.450: Failed to load module "canberra-gtk-module"
Gtk-Message: 10:33:23.452: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Fontconfig warning: FcPattern object width does not accept value [0.61998 1.29999)
Segmentation fault (core dumped)
```

**Comment by ilya-fedin** [comment]
Without backtrace there is nothing to do...

**Comment by ygcaicn** [comment]
> Without backtrace there is nothing to do...

how to install the pre release snap version?

**Comment by Red-Eyed** [comment]
I have same problem

**Comment by ilya-fedin** [comment]
> Without backtrace there is nothing to do...

**Comment by Rexagon** [comment]
Similar<sup>(?)</sup> problem on Manjaro (linux 5.4.22, xfce). Telegram was installed from snap.

```
> telegram-desktop            
Gtk-Message: 16:00:53.953: Failed to load module "canberra-gtk-module"
Fontconfig warning: FcPattern object weight does not accept value [40 210)
[1]    4991 segmentation fault (core dumped)  telegram-desktop
```

<details>
  <summary>Backtrace</summary>
<pre>
> coredumpctl info        
           PID: 4991 (telegram-deskto)
           UID: 1000 (ivan)
           GID: 1000 (ivan)
        Signal: 11 (SEGV)
     Timestamp: Wed 2020-03-04 16:00:54 MSK (5s ago)
  Command Line: telegram-desktop
    Executable: /snap/telegram-desktop/1038/bin/telegram-desktop
 Control Group: /user.slice/user-1000.slice/session-2.scope
          Unit: session-2.scope
         Slice: user-1000.slice
       Session: 2
     Owner UID: 1000 (ivan)
       Boot ID: 4070de8719a447bbaed7bc27bb0386bb
    Machine ID: 2193264ff0a244829e0bc50dba6de117
      Hostname: enoj
       Storage: /var/lib/systemd/coredump/core.telegram-deskto.1000.4070de8719a447bbaed7bc27bb0386bb.4991.1583326854000000.lz4
       Message: Process 4991 (telegram-deskto) of user 1000 dumped core.
                
                Stack trace of thread 4991:
                #0  0x00007fa514296a11 n/a (libQt5XcbQpa.so.5)
                #1  0x00007fa52878eb21 n/a (libQt5Gui.so.5)
                #2  0x00007fa52879219d _ZN13QFontDatabase8findFontERK8QFontDefi (libQt5Gui.so.5)
                #3  0x00007fa5287929c6 _ZN13QFontDatabase4loadEPK12QFontPrivatei (libQt5Gui.so.5)
                #4  0x00007fa528768423 _ZNK12QFontPrivate15engineForScriptEi (libQt5Gui.so.5)
                #5  0x00007fa5287684b4 _ZNK9QFontInfo6familyEv (libQt5Gui.so.5)
                #6  0x000055f79dd7a8ed _ZN5style8internal10StartFontsEv (telegram-desktop)
                #7  0x000055f79d09b8a6 _ZN4Core11Application3runEv (telegram-desktop)
                #8  0x000055f79d0d2c3a _ZN4Core7Sandbox14notifyOrInvokeEP7QObjectP6QEvent (telegram-desktop)
                #9  0x000055f79d0d2d4e _ZN4Core7Sandbox6notifyEP7QObjectP6QEvent (telegram-desktop)
                #10 0x00007fa527ae39c8 _ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent (libQt5Core.so.5)
                #11 0x00007fa527ae613d _ZN23QCoreApplicationPrivate16sendPostedEventsEP7QObjectiP11QThreadData (libQt5Core.so.5)
                #12 0x00007fa527b3d353 n/a (libQt5Core.so.5)
                #13 0x00007fa521f68417 g_main_context_dispatch (libglib-2.0.so.0)
                #14 0x00007fa521f68650 n/a (libglib-2.0.so.0)
                #15 0x00007fa521f686dc g_main_context_iteration (libglib-2.0.so.0)
                #16 0x00007fa527b3c97f _ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE (libQt5Core.so.5)
                #17 0x00007fa527ae19fa _ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE (libQt5Core.so.5)
                #18 0x00007fa527aeaaa4 _ZN16QCoreApplication4execEv (libQt5Core.so.5)
                #19 0x000055f79d0d1951 _ZN4Core7Sandbox5startEv (telegram-desktop)
                #20 0x000055f79d0c2999 _ZN4Core8Launcher18executeApplicationEv (telegram-desktop)
                #21 0x000055f79d0c2aa7 _ZN4Core8Launcher4execEv (telegram-desktop)
                #22 0x000055f79cced8f2 main (telegram-desktop)
                #23 0x00007fa525f70b97 n/a (/lib/x86_64-linux-gnu/libc-2.27.so)
</pre>
</details>

**Comment by ilya-fedin** [comment]
Try
`sudo fc-cache -f -v`

**Comment by Red-Eyed** [comment]
Did it.
Same error

**Comment by ilya-fedin** [comment]
> Same error

Do you have the `Fontconfig warning: FcPattern object width does not accept value` line?

**Comment by ilya-fedin** [comment]
> Try `sudo fc-cache -f -v`
> And `rm -r ~/snap/telegram-desktop/{current,common}/.cache`

@Rexagon so what?

**Comment by Aokromes** [comment]
> Same on Fedora 31
> 
> `Gtk-Message: 16:00:07.590: Failed to load module "canberra-gtk-module" Gtk-Message: 16:00:07.590: Failed to load module "pk-gtk-module" Gtk-Message: 16:00:07.592: Failed to load module "canberra-gtk-module" Gtk-Message: 16:00:07.592: Failed to load module "pk-gtk-module" Qt: Session management error: None of the authentication protocols specified are supported Fontconfig warning: FcPattern object width does not accept value [75 100) [1] 8947 segmentation fault (core dumped) telegram-desktop `

cannot reproduce myself.

**Comment by ilya-fedin** [comment]
> > Same on Fedora 31
> > `Gtk-Message: 16:00:07.590: Failed to load module "canberra-gtk-module" Gtk-Message: 16:00:07.590: Failed to load module "pk-gtk-module" Gtk-Message: 16:00:07.592: Failed to load module "canberra-gtk-module" Gtk-Message: 16:00:07.592: Failed to load module "pk-gtk-module" Qt: Session management error: None of the authentication protocols specified are supported Fontconfig warning: FcPattern object width does not accept value [75 100) [1] 8947 segmentation fault (core dumped) telegram-desktop `
> 
> cannot reproduce myself.

This looks like people have two different problems, but they confused with this regular gtk warning.
The first half, that have warning form fontconfig have problems with an old fontconfig cache from the old static snap. The second half, that doesn't have fontconfig warning, probably have a problem with socket (log is needed to confirm or deny): #7324 
Or, maybe, there are a segfault with completely different reason on the second half, then, a backtrace for them is needed to resolve the problem.

**Comment by ilya-fedin** [comment]
Can anyone check if issue persists when snap package is installed in devmode (`snap install --devmode telegram-desktop`)?

**Comment by Red-Eyed** [comment]
Will do it next week on my work machine.

Also, interesting fact is that telegram works on my home machine and doesn't work on my work machine.

I use the Manjaro Gnome on both of them

**Comment by Red-Eyed** [comment]
Oh, just connected remotely to my work machine.

```
sudo snap install --devmode telegram-desktop
[sudo] password for redeyed: 
snap "telegram-desktop" is already installed, see 'snap help refresh'
(py37) ➜  ~ sudo snap  --devmode telegram-desktop       
(py37) ➜  ~ which telegram-desktop 
/usr/bin/telegram-desktop
(py37) ➜  ~ snap run telegram-desktop

(telegram-desktop:29500): GdkPixbuf-WARNING **: 12:21:48.031: Cannot open pixbuf loader module file '/home/redeyed/snap/telegram-desktop/common/.cache/gdk-pixbuf-loaders.cache': No such file or directory

This likely means that your installation is broken.
Try running the command
  gdk-pixbuf-query-loaders > /home/redeyed/snap/telegram-desktop/common/.cache/gdk-pixbuf-loaders.cache
to make things work again for the time being.
Gtk-Message: 12:21:48.106: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:21:48.107: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Fontconfig warning: FcPattern object weight does not accept value [0 205)
[1]    29500 segmentation fault (core dumped)  snap run telegram-desktop
(py37) ➜  ~ sudo snap refresh --devmode telegram-desktop
snap "telegram-desktop" has no updates available
(py37) ➜  ~ sudo snap remove telegram-desktop
telegram-desktop removed
(py37) ➜  ~ sudo snap install --devmode telegram-desktop
telegram-desktop 1.9.9-4-ga25792187 from Telegram FZ-LLC (telegram.desktop) installed
(py37) ➜  ~ snap run telegram-desktop
Gtk-Message: 12:23:14.308: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:23:14.319: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Fontconfig warning: FcPattern object weight does not accept value [0 205)
[1]    30072 segmentation fault (core dumped)  snap run telegram-desktop
```

**Comment by ilya-fedin** [comment]
Check snapd version on both. There are some strange problem with unix socket listening on old version of snapd. For example, on debian with snapd 2.37 socket binding resturns EPERM, but on ubuntu with snapd 2.41 everything is ok. On manjaro everything is ok too, but maybe you updated your work machine very very long time ago

**Comment by ilya-fedin** [comment]
> (py37) ➜  ~ sudo snap install --devmode telegram-desktop
> telegram-desktop 1.9.9-4-ga25792187 from Telegram FZ-LLC (telegram.desktop) installed
> (py37) ➜  ~ snap run telegram-desktop
> Gtk-Message: 12:23:14.308: Failed to load module "canberra-gtk-module"
> Gtk-Message: 12:23:14.319: Failed to load module "canberra-gtk-module"
> Qt: Session management error: None of the authentication protocols specified are supported
> Fontconfig warning: FcPattern object weight does not accept value [0 205)
> [1]    30072 segmentation fault (core dumped)  snap run telegram-desktop

Oh.

**Comment by ilya-fedin** [comment]
Try `XDG_CURRENT_DESKTOP=KDE snap run telegram-desktop`

**Comment by Red-Eyed** [comment]
I keep all of my machines up to date.
But checked version of snap and it the same:

```
➜  ~ XDG_CURRENT_DESKTOP=KDE snap run telegram-desktop
Gtk-Message: 12:28:27.614: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:28:27.615: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Fontconfig warning: FcPattern object weight does not accept value [0 205)
[1]    30550 segmentation fault (core dumped)  XDG_CURRENT_DESKTOP=KDE snap run telegram-desktop
```


Same error :(
```
➜  ~ XDG_CURRENT_DESKTOP=KDE snap run telegram-desktop
Gtk-Message: 12:28:27.614: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:28:27.615: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Fontconfig warning: FcPattern object weight does not accept value [0 205)
[1]    30550 segmentation fault (core dumped)  XDG_CURRENT_DESKTOP=KDE snap run telegram-desktop
```

**Comment by ilya-fedin** [comment]
Also `sudo fc-cache -r -v` (-r instead of -f)

**Comment by Red-Eyed** [comment]
This command `sudo fc-cache -r -v` works!

**Comment by ilya-fedin** [comment]
> I keep all of my machines up to date.

you have fontconfig warning, so it is an other case (there are two issues, as I said in https://github.com/telegramdesktop/tdesktop/issues/7144#issuecomment-595739846)
And both are really strange.

**Comment by ilya-fedin** [comment]
> This command `sudo fc-cache -r -v` works!

Wow. So, the case is invalid cache on your machine. Hooray! :tada:

**Comment by Red-Eyed** [comment]
My friend also has this issue on Manjaro Gnome as well

**Comment by Red-Eyed** [comment]
Don't know what could lead to invalid cache.

**Comment by Red-Eyed** [comment]
More over, I faced with same issue with other snaps like `keepassxc`

**Comment by ilya-fedin** [comment]
> My friend also has this issue on Manjaro Gnome as well
Maybe manjaro maintainers made a mistake when packaging some font or fontconfig/freetype itself, [they often do it](manjaro.auteiy.me).

**Comment by Red-Eyed** [comment]
link is broken :(

**Comment by ilya-fedin** [comment]
Fixed.

**Comment by ilya-fedin** [comment]
> But why it works on another same manjaro?

I have no idea, apparently Russian roulette :)

**Comment by p3732** [comment]
Having the same issue on Arch with tg installed via snap. Some research shows that also other software is facing the same problem. The best result was this Inkscape Issue comment: 

https://gitlab.com/inkscape/inkscape/issues/491#note_290716614

The problem seems to be having an outdated version of libfontconfig bundled, thus the solution that OpenShot used, was to simply not do that. (See https://github.com/OpenShot/openshot-qt/issues/1775#issuecomment-552202572).

Maybe tg desktop could do the same?

**Comment by ilya-fedin** [comment]
> Maybe tg desktop could do the same?

AppImage can access system libraries, snaps - no

**Comment by p3732** [comment]
> AppImage can access system libraries, snaps are not
Ah, I see.

`fc-cache -r` did not help for my setup, but installing the `ubuntu-fontconfig` from the AUR did. Weirdly enough ever since reverting to the normal Arch fontconfig package a simple `snap run telegram-desktop` still crashes as before installing, while when running it with gdb, which previously also caused a crash, it works. So I don't know how to create a usable backtrace anymore.

**Comment by p3732** [comment]
Oh, also maybe renaming this issue to 'Crash due to fontconfig cache' or something similar :)

**Comment by dhruvan2912** [comment]
> sudo fc-cache -r -v

Didn't work for me

**Comment by ilya-fedin** [comment]
> Didn't work for me
Can you send log and output?

**Comment by dhruvan2912** [comment]
> > Didn't work for me
> 
> Can you send log and output?

Gtk-Message: 20:56:29.634: Failed to load module "canberra-gtk-module"
Fontconfig warning: FcPattern object weight does not accept value [40 210)
[1]    3258 segmentation fault (core dumped)  snap run telegram-desktop

**Comment by p3732** [comment]
Here is the backtrace of running the current `alish-tdesktop` version:

```
Thread 1 "telegram-deskto" received signal SIGSEGV, Segmentation fault.
0x0000ffffa178f5dc in ?? ()
   from target:/snap/alish-tdesktop/33/usr/lib/aarch64-linux-gnu/libQt5XcbQpa.so.5
(gdb) bt
#0  0x0000ffffa178f5dc in ?? ()
   from target:/snap/alish-tdesktop/33/usr/lib/aarch64-linux-gnu/libQt5XcbQpa.so.5
#1  0x0000ffffa529f000 in ?? ()
   from target:/snap/alish-tdesktop/33/usr/lib/aarch64-linux-gnu/libQt5Gui.so.5
Backtrace stopped: previous frame inner to this frame (corrupt stack?)
```

The corrupt stack seems bad. Logfile looks normal but abruptly ends:

```
[2020.03.14 02:28:54] Launched version: 1009019, install beta: [TRUE], alpha: 0, debug mode: [FALSE], test dc: [FALSE]
[2020.03.14 02:28:54] Executable dir: /snap/alish-tdesktop/33/bin/, name: telegram-desktop
[2020.03.14 02:28:54] Initial working dir: /home/p3732/
[2020.03.14 02:28:54] Working dir: /root/snap/alish-tdesktop/33/.local/share/TelegramDesktop/
[2020.03.14 02:28:54] Command line: telegram-desktop
[2020.03.14 02:28:54] Executable path before check: /snap/alish-tdesktop/33/bin/telegram-desktop
[2020.03.14 02:28:54] Logs started
[2020.03.14 02:28:54] Launcher filename: alish-tdesktop_telegram-desktop.desktop
[2020.03.14 02:28:56] Connecting local socket to /run/user/0/snap.alish-tdesktop/40653d80da50b735d7510db7a39cf818...
[2020.03.14 02:28:56] This is the only instance of Telegram, starting server and app...
[2020.03.14 02:28:56] Moved logging from '/root/snap/alish-tdesktop/33/.local/share/TelegramDesktop/log_start0.txt' to '/root/snap/alish-tdesktop/33/.local/share/TelegramDesktop/log.txt'!
[2020.03.14 02:28:56] Primary screen DPI: 95.958
[2020.03.14 02:28:57] Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
```

**Comment by ilya-fedin** [comment]
`env QT_LOGGING_RULES="*.debug=true" telegram-desktop > output.txt  2>&1`
I hope this will give a light :(

**Comment by p3732** [comment]
Aha! Now we have a proper error!

```
qt.qpa.screen: adding QXcbScreen(0xaaab08ea2420, name="XWAYLAND0", geometry=1920x1080+0+0, availableGeometry=1920x1080+0+0, devicePixelRatio=1.0, logicalDpi=QPair(96.0,95.9), physicalSize=309.0x174.0mm, screenNumber=0, virtualSize=1920x1080 (1920.0x1080.0mm), orientation=Qt::ScreenOrientation(LandscapeOrientation), depth=24, refreshRate=59.0, root=39c, windowManagerName="") (Primary: true )
qt.qpa.screen: primary output is "XWAYLAND0"
qt.qpa.input.devices: XInput version 2.2 is available and Qt supports 2.2 or greater
qt.qpa.input.devices: input device  Virtual core XTEST pointer ID 4
qt.qpa.input.devices:    has 10 buttons
qt.qpa.input.devices:    has valuator "Rel X" recognized? true
qt.qpa.input.devices:    has valuator "Rel Y" recognized? true
qt.qpa.input.devices:    it's a scrolling device
qt.qpa.input.devices: input device  xwayland-pointer:16 ID 6
qt.qpa.input.devices:    has 10 buttons
qt.qpa.input.devices:    has valuator "Abs X" recognized? true
qt.qpa.input.devices:    has valuator "Abs Y" recognized? true
qt.qpa.input.devices:    has valuator "Rel Horiz Wheel" recognized? true
qt.qpa.input.devices:    has valuator "Rel Vert Wheel" recognized? true
qt.qpa.input.devices:    it's a scrolling device
qt.qpa.input.devices: input device  xwayland-relative-pointer:16 ID 7
qt.qpa.input.devices:    has 10 buttons
qt.qpa.input.devices:    has valuator "Rel X" recognized? true
qt.qpa.input.devices:    has valuator "Rel Y" recognized? true
qt.qpa.input.devices:    it's a scrolling device
qt.qpa.gl: Choosing xcb gl-integration based on following priority
 ("xcb_glx", "xcb_egl")
qt.qpa.gl: Xcb EGL gl-integration created
qt.qpa.gl: Xcb EGL gl-integration retrying with display 0x0
qt.qpa.gl: Xcb EGL gl-integration successfully initialized
qt.qpa.gl: Failed to initialize xcb gl-integration "xcb_egl"
qt.qpa.gl: Failed to create xcb gl-integration
Gtk-Message: 20:53:03.016: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:53:03.019: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Fontconfig warning: FcPattern object weight does not accept value [40 210)
```

**Comment by ilya-fedin** [comment]
Does everyone else here also uses wayland and didn’t even say? :see_no_evil:

**Comment by ilya-fedin** [comment]
> Aha! Now we have a proper error!

Can you reproduce with xorg?

**Comment by p3732** [comment]
Here it is with Xorg:

```
qt.qpa.screen: Output DP-1 is not connected
qt.qpa.screen: adding QXcbScreen(0xaaaaef6fd420, name="eDP-1", geometry=1920x1080+0+0, availableGeometry=1920x1053+0+27, devicePixelRatio=1.0, logicalDpi=QPair(96.0,96.0), physicalSize=508.0x285.0mm, screenNumber=0, virtualSize=1920x1080 (1920.0x1080.0mm), orientation=Qt::ScreenOrientation(LandscapeOrientation), depth=24, refreshRate=60.0, root=207, windowManagerName="GNOME Shell") (Primary: true )
qt.qpa.screen: primary output is "eDP-1"
qt.qpa.input.devices: XInput version 2.2 is available and Qt supports 2.2 or greater
qt.qpa.input.devices: input device  Virtual core XTEST pointer ID 4
qt.qpa.input.devices:    has 10 buttons
qt.qpa.input.devices:    has valuator "Rel X" recognized? true
qt.qpa.input.devices:    has valuator "Rel Y" recognized? true
qt.qpa.input.devices:    it's a scrolling device
qt.qpa.input.devices: input device  HAILUCK CO.,LTD USB KEYBOARD Mouse ID 10
qt.qpa.input.devices:    has 7 buttons
qt.qpa.input.devices:    has valuator "Rel X" recognized? true
qt.qpa.input.devices:    has valuator "Rel Y" recognized? true
qt.qpa.input.devices:    has valuator "Rel Horiz Scroll" recognized? true
qt.qpa.input.devices:    has valuator "Rel Vert Scroll" recognized? true
qt.qpa.input.devices:    it's a scrolling device
qt.qpa.input.devices: input device  HAILUCK CO.,LTD USB KEYBOARD Touchpad ID 11
qt.qpa.input.devices:    has 7 buttons
qt.qpa.input.devices:    has valuator "Rel X" recognized? true
qt.qpa.input.devices:    has valuator "Rel Y" recognized? true
qt.qpa.input.devices:    has valuator "Rel Horiz Scroll" recognized? true
qt.qpa.input.devices:    has valuator "Rel Vert Scroll" recognized? true
qt.qpa.input.devices:    it's a scrolling device
qt.qpa.gl: Choosing xcb gl-integration based on following priority
 ("xcb_glx", "xcb_egl")
qt.qpa.gl: Xcb EGL gl-integration created
qt.qpa.gl: Xcb EGL gl-integration retrying with display 0x0
qt.qpa.gl: Xcb EGL gl-integration successfully initialized
qt.qpa.gl: Failed to initialize xcb gl-integration "xcb_egl"
qt.qpa.gl: Failed to create xcb gl-integration
Gtk-Message: 20:55:28.265: Failed to load module "canberra-gtk-module"
Gtk-Message: 20:55:28.269: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Fontconfig warning: FcPattern object weight does not accept value [40 210)
```

**Comment by p3732** [comment]
I remember testing both at the beginnig, but at some point stopped, sorry :sweat:

**Comment by ilya-fedin** [comment]
Are you using rpi3 / rpi4? Have you activated KMS?

**Comment by p3732** [comment]
I am using a Pinebook (https://www.pine64.org/pinebook-pro/) and I never configured any KMS, but maybe it came with the distro. Gonna investigate.

**Comment by p3732** [comment]
So uboot does not seem to be set up to use pass on any parameters. Although probably not helpful at all, here is `lsmod`:

```
odule                  Size  Used by
ecryptfs               98304  1
rfcomm                 57344  0
bnep                   28672  2
uvcvideo              110592  0
joydev                 32768  0
squashfs               53248  5
snd_soc_hdmi_codec     16384  0
loop                   40960  10
snd_soc_simple_amplifier    16384  1
panfrost               57344  4
gpu_sched              32768  1 panfrost
snd_soc_rockchip_i2s    16384  2
snd_soc_rockchip_pcm    16384  1 snd_soc_rockchip_i2s
dw_wdt                 20480  0
rockchip_rga           28672  0
hantro_vpu             81920  0
videobuf2_dma_sg       20480  1 rockchip_rga
videobuf2_dma_contig    24576  1 hantro_vpu
videobuf2_vmalloc      20480  2 hantro_vpu,uvcvideo
v4l2_mem2mem           45056  2 hantro_vpu,rockchip_rga
videobuf2_memops       20480  3 videobuf2_vmalloc,videobuf2_dma_contig,videobuf2_dma_sg
videobuf2_v4l2         36864  4 hantro_vpu,rockchip_rga,uvcvideo,v4l2_mem2mem
videobuf2_common       57344  5 videobuf2_v4l2,hantro_vpu,rockchip_rga,uvcvideo,v4l2_mem2mem
cw2015_battery         20480  0
hci_uart              114688  0
btqca                  16384  1 hci_uart
btbcm                  20480  1 hci_uart
btintel                32768  1 hci_uart
btsdio                 20480  0
bluetooth             430080  33 btqca,btsdio,btintel,hci_uart,btbcm,bnep,rfcomm
rockchip_thermal       24576  0
ecdh_generic           16384  1 bluetooth
ecc                    32768  1 ecdh_generic
snd_soc_es8316         40960  1
brcmfmac              315392  0
brcmutil               20480  1 brcmfmac
rockchip_saradc        16384  0
cfg80211              372736  1 brcmfmac
rockchipdrm           135168  11
rfkill                 40960  8 bluetooth,cfg80211
analogix_dp            40960  1 rockchipdrm
dw_mipi_dsi            20480  1 rockchipdrm
dw_hdmi                49152  1 rockchipdrm
cec                    61440  1 dw_hdmi
rc_core                57344  1 cec
drm_kms_helper        225280  4 dw_mipi_dsi,rockchipdrm,dw_hdmi,analogix_dp
syscopyarea            16384  1 drm_kms_helper
sysfillrect            16384  1 drm_kms_helper
sysimgblt              16384  1 drm_kms_helper
fb_sys_fops            16384  1 drm_kms_helper
snd_soc_simple_card    20480  2
snd_soc_simple_card_utils    20480  1 snd_soc_simple_card
panel_simple           73728  0
pwm_bl                 16384  0
crypto_user            16384  0
drm                   593920  15 gpu_sched,drm_kms_helper,dw_mipi_dsi,panel_simple,rockchipdrm,dw_hdmi,panfrost,analogix_dp
drm_panel_orientation_quirks    20480  1 drm
gpio_keys              24576  0
hid_multitouch         32768  0
```

**Comment by p3732** [comment]
>  Aha! Now we have a proper error!

I noticed that this is actually the same error as in all the other posted logs. (The `Qt: Session management error: None of the authentication protocols specified are supported`)

**Comment by ilya-fedin** [comment]
Xorg log (/var/log/Xorg.0.log if you're use a display manager) would be more helpful

**Comment by p3732** [comment]
```
[  4379.138] (--) Log file renamed from "/var/log/Xorg.pid-46721.log" to "/var/log/Xorg.0.log"
[  4379.139] (WW) Failed to open protocol names file lib/xorg/protocol.txt
[  4379.140] 
X.Org X Server 1.20.7
X Protocol Version 11, Revision 0
[  4379.140] Build Operating System: Linux Arch Linux
[  4379.140] Current Operating System: Linux buddy 5.5.0-3.1-MANJARO-ARM #1 SMP Mon Feb 10 20:59:01 +03 2020 aarch64
[  4379.140] Kernel command line: console=ttyS2,1500000 root=PARTUUID=bb56caf9-01 rw rootwait bootsplash.bootfile=bootsplash-themes/manjaro/bootsplash initrd=0x06000000,20M ramdisk_size=10M
[  4379.140] Build Date: 16 January 2020  05:48:33PM
[  4379.140]  
[  4379.141] Current version of pixman: 0.38.4
[  4379.141] 	Before reporting problems, check http://wiki.x.org
	to make sure that you have the latest version.
[  4379.141] Markers: (--) probed, (**) from config file, (==) default setting,
	(++) from command line, (!!) notice, (II) informational,
	(WW) warning, (EE) error, (NI) not implemented, (??) unknown.
[  4379.141] (==) Log file: "/var/log/Xorg.0.log", Time: Sat Mar 14 20:55:09 2020
[  4379.143] (==) Using config directory: "/etc/X11/xorg.conf.d"
[  4379.143] (==) Using system config directory "/usr/share/X11/xorg.conf.d"
[  4379.144] (==) No Layout section.  Using the first Screen section.
[  4379.144] (==) No screen section available. Using defaults.
[  4379.145] (**) |-->Screen "Default Screen Section" (0)
[  4379.145] (**) |   |-->Monitor "<default monitor>"
[  4379.146] (==) No monitor specified for screen "Default Screen Section".
	Using a default monitor configuration.
[  4379.146] (==) Automatically adding devices
[  4379.146] (==) Automatically enabling devices
[  4379.146] (==) Automatically adding GPU devices
[  4379.146] (==) Automatically binding GPU devices
[  4379.146] (==) Max clients allowed: 256, resource mask: 0x1fffff
[  4379.146] (WW) The directory "/usr/share/fonts/misc" does not exist.
[  4379.146] 	Entry deleted from font path.
[  4379.146] (WW) The directory "/usr/share/fonts/OTF" does not exist.
[  4379.146] 	Entry deleted from font path.
[  4379.146] (WW) The directory "/usr/share/fonts/Type1" does not exist.
[  4379.146] 	Entry deleted from font path.
[  4379.146] (WW) The directory "/usr/share/fonts/100dpi" does not exist.
[  4379.146] 	Entry deleted from font path.
[  4379.146] (WW) The directory "/usr/share/fonts/75dpi" does not exist.
[  4379.146] 	Entry deleted from font path.
[  4379.146] (==) FontPath set to:
	/usr/share/fonts/TTF
[  4379.146] (==) ModulePath set to "/usr/lib/xorg/modules"
[  4379.146] (II) The server relies on udev to provide the list of input devices.
	If no devices become available, reconfigure udev or disable AutoAddDevices.
[  4379.146] (II) Module ABI versions:
[  4379.147] 	X.Org ANSI C Emulation: 0.4
[  4379.147] 	X.Org Video Driver: 24.1
[  4379.147] 	X.Org XInput driver : 24.1
[  4379.147] 	X.Org Server Extension : 10.0
[  4379.149] (++) using VT number 2

[  4379.157] (II) systemd-logind: took control of session /org/freedesktop/login1/session/c4
[  4379.160] (II) xfree86: Adding drm device (/dev/dri/card0)
[  4379.163] (II) systemd-logind: got fd for /dev/dri/card0 226:0 fd 11 paused 0
[  4379.164] (II) xfree86: Adding drm device (/dev/dri/card1)
[  4379.169] (II) systemd-logind: got fd for /dev/dri/card1 226:1 fd 12 paused 0
[  4379.169] (II) no primary bus or device found
[  4379.169] 	falling back to /sys/devices/platform/display-subsystem/drm/card0
[  4379.170] (II) LoadModule: "glx"
[  4379.174] (II) Loading /usr/lib/xorg/modules/extensions/libglx.so
[  4379.185] (II) Module glx: vendor="X.Org Foundation"
[  4379.185] 	compiled for 1.20.7, module version = 1.0.0
[  4379.185] 	ABI class: X.Org Server Extension, version 10.0
[  4379.185] (==) Matched modesetting as autoconfigured driver 0
[  4379.185] (==) Matched fbdev as autoconfigured driver 1
[  4379.185] (==) Assigned the driver to the xf86ConfigLayout
[  4379.185] (II) LoadModule: "modesetting"
[  4379.187] (II) Loading /usr/lib/xorg/modules/drivers/modesetting_drv.so
[  4379.191] (II) Module modesetting: vendor="X.Org Foundation"
[  4379.192] 	compiled for 1.20.7, module version = 1.20.7
[  4379.192] 	Module class: X.Org Video Driver
[  4379.192] 	ABI class: X.Org Video Driver, version 24.1
[  4379.192] (II) LoadModule: "fbdev"
[  4379.193] (WW) Warning, couldn't open module fbdev
[  4379.193] (EE) Failed to load module "fbdev" (module does not exist, 0)
[  4379.193] (II) modesetting: Driver for Modesetting Kernel Drivers: kms
[  4379.193] (II) modeset(0): using drv /dev/dri/card0
[  4379.193] (II) modeset(0): Creating default Display subsection in Screen section
	"Default Screen Section" for depth/fbbpp 24/32
[  4379.194] (==) modeset(0): Depth 24, (==) framebuffer bpp 32
[  4379.194] (==) modeset(0): RGB weight 888
[  4379.194] (==) modeset(0): Default visual is TrueColor
[  4379.194] (II) Loading sub module "glamoregl"
[  4379.194] (II) LoadModule: "glamoregl"
[  4379.194] (II) Loading /usr/lib/xorg/modules/libglamoregl.so
[  4379.220] (II) Module glamoregl: vendor="X.Org Foundation"
[  4379.220] 	compiled for 1.20.7, module version = 1.0.1
[  4379.220] 	ABI class: X.Org ANSI C Emulation, version 0.4
[  4379.380] (II) modeset(0): glamor X acceleration enabled on Mali T860 (Panfrost)
[  4379.380] (II) modeset(0): glamor initialized
[  4379.381] (II) modeset(0): Output eDP-1 has no monitor section
[  4379.381] (II) modeset(0): Output DP-1 has no monitor section
[  4379.381] (II) modeset(0): EDID for output eDP-1
[  4379.381] (II) modeset(0): Printing probed modes for output eDP-1
[  4379.381] (II) modeset(0): Modeline "1920x1080"x60.0  148.50  1920 1968 2000 2200  1080 1083 1088 1125 (67.5 kHz eP)
[  4379.381] (II) modeset(0): EDID for output DP-1
[  4379.381] (II) modeset(0): Output eDP-1 connected
[  4379.381] (II) modeset(0): Output DP-1 disconnected
[  4379.381] (II) modeset(0): Using exact sizes for initial modes
[  4379.381] (II) modeset(0): Output eDP-1 using initial mode 1920x1080 +0+0
[  4379.381] (==) modeset(0): Using gamma correction (1.0, 1.0, 1.0)
[  4379.381] (==) modeset(0): DPI set to (96, 96)
[  4379.381] (II) Loading sub module "fb"
[  4379.381] (II) LoadModule: "fb"
[  4379.382] (II) Loading /usr/lib/xorg/modules/libfb.so
[  4379.384] (II) Module fb: vendor="X.Org Foundation"
[  4379.384] 	compiled for 1.20.7, module version = 1.0.0
[  4379.384] 	ABI class: X.Org ANSI C Emulation, version 0.4
[  4379.439] (==) modeset(0): Backing store enabled
[  4379.439] (==) modeset(0): Silken mouse disabled
[  4379.445] (II) modeset(0): Initializing kms color map for depth 24, 8 bpc.
[  4379.445] (==) modeset(0): DPMS enabled
[  4379.445] (II) modeset(0): [DRI2] Setup complete
[  4379.445] (II) modeset(0): [DRI2]   DRI driver: rockchip
[  4379.445] (II) modeset(0): [DRI2]   VDPAU driver: rockchip
[  4379.445] (II) Initializing extension Generic Event Extension
[  4379.446] (II) Initializing extension SHAPE
[  4379.446] (II) Initializing extension MIT-SHM
[  4379.446] (II) Initializing extension XInputExtension
[  4379.446] (II) Initializing extension XTEST
[  4379.447] (II) Initializing extension BIG-REQUESTS
[  4379.447] (II) Initializing extension SYNC
[  4379.447] (II) Initializing extension XKEYBOARD
[  4379.447] (II) Initializing extension XC-MISC
[  4379.447] (II) Initializing extension SECURITY
[  4379.447] (II) Initializing extension XFIXES
[  4379.447] (II) Initializing extension RENDER
[  4379.447] (II) Initializing extension RANDR
[  4379.447] (II) Initializing extension COMPOSITE
[  4379.447] (II) Initializing extension DAMAGE
[  4379.447] (II) Initializing extension MIT-SCREEN-SAVER
[  4379.447] (II) Initializing extension DOUBLE-BUFFER
[  4379.447] (II) Initializing extension RECORD
[  4379.447] (II) Initializing extension DPMS
[  4379.447] (II) Initializing extension Present
[  4379.447] (II) Initializing extension DRI3
[  4379.447] (II) Initializing extension X-Resource
[  4379.447] (II) Initializing extension XVideo
[  4379.447] (II) Initializing extension XVideo-MotionCompensation
[  4379.447] (II) Initializing extension GLX
[  4379.454] (II) AIGLX: Loaded and initialized rockchip
[  4379.454] (II) GLX: Initialized DRI2 GL provider for screen 0
[  4379.454] (II) Initializing extension XFree86-VidModeExtension
[  4379.454] (II) Initializing extension XFree86-DGA
[  4379.454] (II) Initializing extension XFree86-DRI
[  4379.454] (II) Initializing extension DRI2
[  4379.456] (II) modeset(0): Damage tracking initialized
[  4379.456] (II) modeset(0): Setting screen physical size to 508 x 285
[  4379.536] (II) config/udev: Adding input device rockchip,es8316-codec Headphones (/dev/input/event8)
[  4379.537] (II) No input driver specified, ignoring this device.
[  4379.537] (II) This device may have been added with another device file.
[  4379.538] (II) config/udev: Adding input device HAILUCK CO.,LTD USB KEYBOARD (/dev/input/event0)
[  4379.538] (**) HAILUCK CO.,LTD USB KEYBOARD: Applying InputClass "libinput keyboard catchall"
[  4379.538] (**) HAILUCK CO.,LTD USB KEYBOARD: Applying InputClass "system-keyboard"
[  4379.538] (II) LoadModule: "libinput"
[  4379.538] (II) Loading /usr/lib/xorg/modules/input/libinput_drv.so
[  4379.544] (II) Module libinput: vendor="X.Org Foundation"
[  4379.544] 	compiled for 1.20.5, module version = 0.29.0
[  4379.544] 	Module class: X.Org XInput Driver
[  4379.544] 	ABI class: X.Org XInput driver, version 24.1
[  4379.544] (II) Using input driver 'libinput' for 'HAILUCK CO.,LTD USB KEYBOARD'
[  4379.550] (II) systemd-logind: got fd for /dev/input/event0 13:64 fd 23 paused 0
[  4379.550] (**) HAILUCK CO.,LTD USB KEYBOARD: always reports core events
[  4379.550] (**) Option "Device" "/dev/input/event0"
[  4379.550] (**) Option "_source" "server/udev"
[  4379.555] (II) event0  - HAILUCK CO.,LTD USB KEYBOARD: is tagged by udev as: Keyboard
[  4379.555] (II) event0  - HAILUCK CO.,LTD USB KEYBOARD: device is a keyboard
[  4379.556] (II) event0  - HAILUCK CO.,LTD USB KEYBOARD: device removed
[  4379.556] (**) Option "config_info" "udev:/sys/devices/platform/fe3a0000.usb/usb3/3-1/3-1:1.0/0003:258A:001E.0001/input/input0/event0"
[  4379.556] (II) XINPUT: Adding extended input device "HAILUCK CO.,LTD USB KEYBOARD" (type: KEYBOARD, id 6)
[  4379.556] (**) Option "xkb_layout" "de"
[  4379.556] (**) Option "xkb_variant" "neo"
[  4379.619] (II) event0  - HAILUCK CO.,LTD USB KEYBOARD: is tagged by udev as: Keyboard
[  4379.619] (II) event0  - HAILUCK CO.,LTD USB KEYBOARD: device is a keyboard
[  4379.621] (II) config/udev: Adding input device HAILUCK CO.,LTD USB KEYBOARD System Control (/dev/input/event5)
[  4379.621] (**) HAILUCK CO.,LTD USB KEYBOARD System Control: Applying InputClass "libinput keyboard catchall"
[  4379.621] (**) HAILUCK CO.,LTD USB KEYBOARD System Control: Applying InputClass "system-keyboard"
[  4379.621] (II) Using input driver 'libinput' for 'HAILUCK CO.,LTD USB KEYBOARD System Control'
[  4379.626] (II) systemd-logind: got fd for /dev/input/event5 13:69 fd 26 paused 0
[  4379.626] (**) HAILUCK CO.,LTD USB KEYBOARD System Control: always reports core events
[  4379.626] (**) Option "Device" "/dev/input/event5"
[  4379.626] (**) Option "_source" "server/udev"
[  4379.629] (II) event5  - HAILUCK CO.,LTD USB KEYBOARD System Control: is tagged by udev as: Keyboard
[  4379.629] (II) event5  - HAILUCK CO.,LTD USB KEYBOARD System Control: device is a keyboard
[  4379.629] (II) event5  - HAILUCK CO.,LTD USB KEYBOARD System Control: device removed
[  4379.629] (**) Option "config_info" "udev:/sys/devices/platform/fe3a0000.usb/usb3/3-1/3-1:1.1/0003:258A:001E.0002/input/input10/event5"
[  4379.629] (II) XINPUT: Adding extended input device "HAILUCK CO.,LTD USB KEYBOARD System Control" (type: KEYBOARD, id 7)
[  4379.629] (**) Option "xkb_layout" "de"
[  4379.629] (**) Option "xkb_variant" "neo"
[  4379.632] (II) event5  - HAILUCK CO.,LTD USB KEYBOARD System Control: is tagged by udev as: Keyboard
[  4379.633] (II) event5  - HAILUCK CO.,LTD USB KEYBOARD System Control: device is a keyboard
[  4379.634] (II) config/udev: Adding input device HAILUCK CO.,LTD USB KEYBOARD Consumer Control (/dev/input/event6)
[  4379.634] (**) HAILUCK CO.,LTD USB KEYBOARD Consumer Control: Applying InputClass "libinput keyboard catchall"
[  4379.634] (**) HAILUCK CO.,LTD USB KEYBOARD Consumer Control: Applying InputClass "system-keyboard"
[  4379.634] (II) Using input driver 'libinput' for 'HAILUCK CO.,LTD USB KEYBOARD Consumer Control'
[  4379.639] (II) systemd-logind: got fd for /dev/input/event6 13:70 fd 27 paused 0
[  4379.639] (**) HAILUCK CO.,LTD USB KEYBOARD Consumer Control: always reports core events
[  4379.640] (**) Option "Device" "/dev/input/event6"
[  4379.640] (**) Option "_source" "server/udev"
[  4379.642] (II) event6  - HAILUCK CO.,LTD USB KEYBOARD Consumer Control: is tagged by udev as: Keyboard
[  4379.643] (II) event6  - HAILUCK CO.,LTD USB KEYBOARD Consumer Control: device is a keyboard
[  4379.643] (II) event6  - HAILUCK CO.,LTD USB KEYBOARD Consumer Control: device removed
[  4379.643] (**) Option "config_info" "udev:/sys/devices/platform/fe3a0000.usb/usb3/3-1/3-1:1.1/0003:258A:001E.0002/input/input11/event6"
[  4379.643] (II) XINPUT: Adding extended input device "HAILUCK CO.,LTD USB KEYBOARD Consumer Control" (type: KEYBOARD, id 8)
[  4379.643] (**) Option "xkb_layout" "de"
[  4379.643] (**) Option "xkb_variant" "neo"
[  4379.646] (II) event6  - HAILUCK CO.,LTD USB KEYBOARD Consumer Control: is tagged by udev as: Keyboard
[  4379.647] (II) event6  - HAILUCK CO.,LTD USB KEYBOARD Consumer Control: device is a keyboard
[  4379.648] (II) config/udev: Adding input device HAILUCK CO.,LTD USB KEYBOARD Wireless Radio Control (/dev/input/event7)
[  4379.648] (**) HAILUCK CO.,LTD USB KEYBOARD Wireless Radio Control: Applying InputClass "libinput keyboard catchall"
[  4379.648] (**) HAILUCK CO.,LTD USB KEYBOARD Wireless Radio Control: Applying InputClass "system-keyboard"
[  4379.648] (II) Using input driver 'libinput' for 'HAILUCK CO.,LTD USB KEYBOARD Wireless Radio Control'
[  4379.654] (II) systemd-logind: got fd for /dev/input/event7 13:71 fd 28 paused 0
[  4379.654] (**) HAILUCK CO.,LTD USB KEYBOARD Wireless Radio Control: always reports core events
[  4379.654] (**) Option "Device" "/dev/input/event7"
[  4379.654] (**) Option "_source" "server/udev"
[  4379.658] (II) event7  - HAILUCK CO.,LTD USB KEYBOARD Wireless Radio Control: is tagged by udev as: Keyboard
[  4379.658] (II) event7  - HAILUCK CO.,LTD USB KEYBOARD Wireless Radio Control: device is a keyboard
[  4379.659] (II) event7  - HAILUCK CO.,LTD USB KEYBOARD Wireless Radio Control: device removed
[  4379.659] (**) Option "config_info" "udev:/sys/devices/platform/fe3a0000.usb/usb3/3-1/3-1:1.1/0003:258A:001E.0002/input/input12/event7"
[  4379.659] (II) XINPUT: Adding extended input device "HAILUCK CO.,LTD USB KEYBOARD Wireless Radio Control" (type: KEYBOARD, id 9)
[  4379.659] (**) Option "xkb_layout" "de"
[  4379.659] (**) Option "xkb_variant" "neo"
[  4379.663] (II) event7  - HAILUCK CO.,LTD USB KEYBOARD Wireless Radio Control: is tagged by udev as: Keyboard
[  4379.664] (II) event7  - HAILUCK CO.,LTD USB KEYBOARD Wireless Radio Control: device is a keyboard
[  4379.666] (II) config/udev: Adding input device HAILUCK CO.,LTD USB KEYBOARD Mouse (/dev/input/event3)
[  4379.666] (**) HAILUCK CO.,LTD USB KEYBOARD Mouse: Applying InputClass "libinput pointer catchall"
[  4379.666] (II) Using input driver 'libinput' for 'HAILUCK CO.,LTD USB KEYBOARD Mouse'
[  4379.670] (II) systemd-logind: got fd for /dev/input/event3 13:67 fd 29 paused 0
[  4379.670] (**) HAILUCK CO.,LTD USB KEYBOARD Mouse: always reports core events
[  4379.670] (**) Option "Device" "/dev/input/event3"
[  4379.670] (**) Option "_source" "server/udev"
[  4379.674] (II) event3  - HAILUCK CO.,LTD USB KEYBOARD Mouse: is tagged by udev as: Mouse
[  4379.675] (II) event3  - HAILUCK CO.,LTD USB KEYBOARD Mouse: device is a pointer
[  4379.675] (II) event3  - HAILUCK CO.,LTD USB KEYBOARD Mouse: device removed
[  4379.675] (**) Option "config_info" "udev:/sys/devices/platform/fe3a0000.usb/usb3/3-1/3-1:1.1/0003:258A:001E.0002/input/input8/event3"
[  4379.675] (II) XINPUT: Adding extended input device "HAILUCK CO.,LTD USB KEYBOARD Mouse" (type: MOUSE, id 10)
[  4379.676] (**) Option "AccelerationScheme" "none"
[  4379.676] (**) HAILUCK CO.,LTD USB KEYBOARD Mouse: (accel) selected scheme none/0
[  4379.676] (**) HAILUCK CO.,LTD USB KEYBOARD Mouse: (accel) acceleration factor: 2.000
[  4379.676] (**) HAILUCK CO.,LTD USB KEYBOARD Mouse: (accel) acceleration threshold: 4
[  4379.680] (II) event3  - HAILUCK CO.,LTD USB KEYBOARD Mouse: is tagged by udev as: Mouse
[  4379.680] (II) event3  - HAILUCK CO.,LTD USB KEYBOARD Mouse: device is a pointer
[  4379.682] (II) config/udev: Adding input device HAILUCK CO.,LTD USB KEYBOARD Mouse (/dev/input/mouse0)
[  4379.682] (II) No input driver specified, ignoring this device.
[  4379.682] (II) This device may have been added with another device file.
[  4379.684] (II) config/udev: Adding input device HAILUCK CO.,LTD USB KEYBOARD Touchpad (/dev/input/event4)
[  4379.684] (**) HAILUCK CO.,LTD USB KEYBOARD Touchpad: Applying InputClass "libinput touchpad catchall"
[  4379.684] (II) Using input driver 'libinput' for 'HAILUCK CO.,LTD USB KEYBOARD Touchpad'
[  4379.689] (II) systemd-logind: got fd for /dev/input/event4 13:68 fd 30 paused 0
[  4379.689] (**) HAILUCK CO.,LTD USB KEYBOARD Touchpad: always reports core events
[  4379.690] (**) Option "Device" "/dev/input/event4"
[  4379.690] (**) Option "_source" "server/udev"
[  4379.693] (II) event4  - HAILUCK CO.,LTD USB KEYBOARD Touchpad: is tagged by udev as: Touchpad
[  4379.695] (II) event4  - HAILUCK CO.,LTD USB KEYBOARD Touchpad: device is a touchpad
[  4379.695] (II) event4  - HAILUCK CO.,LTD USB KEYBOARD Touchpad: device removed
[  4379.696] (**) Option "config_info" "udev:/sys/devices/platform/fe3a0000.usb/usb3/3-1/3-1:1.1/0003:258A:001E.0002/input/input9/event4"
[  4379.696] (II) XINPUT: Adding extended input device "HAILUCK CO.,LTD USB KEYBOARD Touchpad" (type: TOUCHPAD, id 11)
[  4379.698] (**) Option "AccelerationScheme" "none"
[  4379.698] (**) HAILUCK CO.,LTD USB KEYBOARD Touchpad: (accel) selected scheme none/0
[  4379.698] (**) HAILUCK CO.,LTD USB KEYBOARD Touchpad: (accel) acceleration factor: 2.000
[  4379.698] (**) HAILUCK CO.,LTD USB KEYBOARD Touchpad: (accel) acceleration threshold: 4
[  4379.701] (II) event4  - HAILUCK CO.,LTD USB KEYBOARD Touchpad: is tagged by udev as: Touchpad
[  4379.703] (II) event4  - HAILUCK CO.,LTD USB KEYBOARD Touchpad: device is a touchpad
[  4379.705] (II) config/udev: Adding input device HAILUCK CO.,LTD USB KEYBOARD Touchpad (/dev/input/mouse1)
[  4379.705] (II) No input driver specified, ignoring this device.
[  4379.705] (II) This device may have been added with another device file.
[  4379.707] (II) config/udev: Adding input device USB Camera: USB Camera (/dev/input/event9)
[  4379.707] (**) USB Camera: USB Camera: Applying InputClass "libinput keyboard catchall"
[  4379.707] (**) USB Camera: USB Camera: Applying InputClass "system-keyboard"
[  4379.707] (II) Using input driver 'libinput' for 'USB Camera: USB Camera'
[  4379.723] (II) systemd-logind: got fd for /dev/input/event9 13:73 fd 31 paused 0
[  4379.723] (**) USB Camera: USB Camera: always reports core events
[  4379.723] (**) Option "Device" "/dev/input/event9"
[  4379.723] (**) Option "_source" "server/udev"
[  4379.727] (II) event9  - USB Camera: USB Camera: is tagged by udev as: Keyboard
[  4379.727] (II) event9  - USB Camera: USB Camera: device is a keyboard
[  4379.727] (II) event9  - USB Camera: USB Camera: device removed
[  4379.727] (**) Option "config_info" "udev:/sys/devices/platform/fe3c0000.usb/usb2/2-1/2-1.2/2-1.2:1.0/input/input14/event9"
[  4379.727] (II) XINPUT: Adding extended input device "USB Camera: USB Camera" (type: KEYBOARD, id 12)
[  4379.727] (**) Option "xkb_layout" "de"
[  4379.727] (**) Option "xkb_variant" "neo"
[  4379.732] (II) event9  - USB Camera: USB Camera: is tagged by udev as: Keyboard
[  4379.732] (II) event9  - USB Camera: USB Camera: device is a keyboard
[  4379.734] (II) config/udev: Adding input device gpio-key-lid (/dev/input/event2)
[  4379.734] (II) No input driver specified, ignoring this device.
[  4379.734] (II) This device may have been added with another device file.
[  4379.735] (II) config/udev: Adding input device gpio-key-power (/dev/input/event1)
[  4379.735] (**) gpio-key-power: Applying InputClass "libinput keyboard catchall"
[  4379.735] (**) gpio-key-power: Applying InputClass "system-keyboard"
[  4379.735] (II) Using input driver 'libinput' for 'gpio-key-power'
[  4379.740] (II) systemd-logind: got fd for /dev/input/event1 13:65 fd 32 paused 0
[  4379.740] (**) gpio-key-power: always reports core events
[  4379.740] (**) Option "Device" "/dev/input/event1"
[  4379.740] (**) Option "_source" "server/udev"
[  4379.741] (II) event1  - gpio-key-power: is tagged by udev as: Keyboard
[  4379.742] (II) event1  - gpio-key-power: device is a keyboard
[  4379.742] (II) event1  - gpio-key-power: device removed
[  4379.742] (**) Option "config_info" "udev:/sys/devices/platform/gpio-key-power/input/input6/event1"
[  4379.742] (II) XINPUT: Adding extended input device "gpio-key-power" (type: KEYBOARD, id 13)
[  4379.742] (**) Option "xkb_layout" "de"
[  4379.742] (**) Option "xkb_variant" "neo"
[  4379.744] (II) event1  - gpio-key-power: is tagged by udev as: Keyboard
[  4379.744] (II) event1  - gpio-key-power: device is a keyboard
```

**Comment by ilya-fedin** [comment]
> I noticed that this is actually the same error as in all the other posted logs.

It is always there, it's normal

**Comment by p3732** [comment]
Reading my own log, I would say that is a yes on KMS

**Comment by ilya-fedin** [comment]
`ls /usr/lib/dri`

**Comment by p3732** [comment]
```
armada-drm_dri.so  ili9225_dri.so  ingenic-drm_dri.so  lima_dri.so   mi0283qt_dri.so   nouveau_dri.so        panfrost_dri.so  rockchip_dri.so  stm_dri.so        v3d_dri.so
exynos_dri.so      ili9341_dri.so  kgsl_dri.so         mcde_dri.so   msm_dri.so        nouveau_drv_video.so  pl111_dri.so     st7586_dri.so    sun4i-drm_dri.so  vc4_dri.so
hx8357d_dri.so     imx-drm_dri.so  kms_swrast_dri.so   meson_dri.so  mxsfb-drm_dri.so  nouveau_vieux_dri.so  repaper_dri.so   st7735r_dri.so   swrast_dri.so     virtio_gpu_dri.so
```

**Comment by ilya-fedin** [comment]
`glxinfo | grep Device`
glxinfo is in `mesa-demons` package

**Comment by p3732** [comment]
`Device: Mali T860 (Panfrost) (0xffffffff)`

**Comment by p3732** [comment]
This driver is still very much in development afaik, so if you think that is the cause then as I suspected in #6647 I can't be of much help with debugging unfortunately.

**Comment by ilya-fedin** [comment]
`env QT_LOGGING_RULES="*.debug=true" MESA_LOADER_DRIVER_OVERRIDE=swrast telegram-desktop > output.txt 2>&1`

**Comment by p3732** [comment]
`
qt.qpa.screen: Output DP-1 is not connected
qt.qpa.screen: adding QXcbScreen(0xaaaadc3e6430, name="eDP-1", geometry=1920x1080+0+0, availableGeometry=1920x1053+0+27, devicePixelRatio=1.0, logicalDpi=QPair(96.0,96.0), physicalSize=508.0x285.0mm, screenNumber=0, virtualSize=1920x1080 (1920.0x1080.0mm), orientation=Qt::ScreenOrientation(LandscapeOrientation), depth=24, refreshRate=60.0, root=207, windowManagerName="GNOME Shell") (Primary: true )
qt.qpa.screen: primary output is "eDP-1"
qt.qpa.input.devices: XInput version 2.2 is available and Qt supports 2.2 or greater
qt.qpa.input.devices: input device  Virtual core XTEST pointer ID 4
qt.qpa.input.devices:    has 10 buttons
qt.qpa.input.devices:    has valuator "Rel X" recognized? true
qt.qpa.input.devices:    has valuator "Rel Y" recognized? true
qt.qpa.input.devices:    it's a scrolling device
qt.qpa.input.devices: input device  HAILUCK CO.,LTD USB KEYBOARD Mouse ID 10
qt.qpa.input.devices:    has 7 buttons
qt.qpa.input.devices:    has valuator "Rel X" recognized? true
qt.qpa.input.devices:    has valuator "Rel Y" recognized? true
qt.qpa.input.devices:    has valuator "Rel Horiz Scroll" recognized? true
qt.qpa.input.devices:    has valuator "Rel Vert Scroll" recognized? true
qt.qpa.input.devices:    it's a scrolling device
qt.qpa.input.devices: input device  HAILUCK CO.,LTD USB KEYBOARD Touchpad ID 11
qt.qpa.input.devices:    has 7 buttons
qt.qpa.input.devices:    has valuator "Rel X" recognized? true
qt.qpa.input.devices:    has valuator "Rel Y" recognized? true
qt.qpa.input.devices:    has valuator "Rel Horiz Scroll" recognized? true
qt.qpa.input.devices:    has valuator "Rel Vert Scroll" recognized? true
qt.qpa.input.devices:    it's a scrolling device
qt.qpa.gl: Choosing xcb gl-integration based on following priority
 ("xcb_glx", "xcb_egl")
qt.qpa.gl: Xcb EGL gl-integration created
qt.qpa.gl: Xcb EGL gl-integration retrying with display 0x0
qt.qpa.gl: Xcb EGL gl-integration successfully initialized
qt.qpa.gl: Failed to initialize xcb gl-integration "xcb_egl"
qt.qpa.gl: Failed to create xcb gl-integration
Gtk-Message: 21:36:38.549: Failed to load module "canberra-gtk-module"
Gtk-Message: 21:36:38.558: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
Fontconfig warning: FcPattern object weight does not accept value [40 210)
`

**Comment by p3732** [comment]
All these are with the `alish-tdesktop` version FYI

**Comment by ilya-fedin** [comment]
Please, everyone who was affected, post your distribution name, distribution version, DE, hardware architecture (i386/x86_64/armhf/arm64/etc), fontconfig version (`fc-cache --version`)

**Comment by p3732** [comment]
Arch Linux ARM, rolling, Gnome Shell 3.36, arm64, fontconfig 2.13.91

**Comment by ilya-fedin** [comment]
@ioan-cristea 
@ygcaicn 
@kprm 
@Red-Eyed 
@Rexagon 
@dhruvan2912

**Comment by dhruvan2912** [comment]
uname -a                                                                                  
Linux  5.4.24-1-MANJARO #1 SMP PREEMPT Thu Mar 5 20:29:25 UTC 2020 x86_64 GNU/Linux
fc-cache --version
fontconfig version 2.13.1
Shell: zsh 5.8
DE: KDE 5.67.0 / Plasma 5.18.3

**Comment by ilya-fedin** [comment]
@ioan-cristea
@ygcaicn
You have the most interesting configuration here (Ubuntu), when all others Arch/Manjaro. I'm waiting for you.

**Comment by dthpulse** [comment]
same problem on openSUSE Tumbleweed
Linux 5.10.9-1-default  x86_64 GNU/Linux
fontconfig version 2.13.1
