### ISSUE TITLE
Non-telegram stickers added by url get lost after reboot or aplication shutdown

### ISSUE THREAD

**Issue by alferpal** [telegramdesktop/tdesktop#758]
After the inclusion of custom stickers in tdesktop, my girlfriend and I started noticing that the only sticker pack we use ( https://telegram.me/addstickers/Stich ) aside from the official stickers gets lost sometimes  after the application is closed ( from the tray or because system shutdown ) and the pc rebooted or shutdown.

When reopening telegram after the reboot, the sticker pack might or not be present as if you never included it in the first place.

This behaviour has been observed in both the windows client ( Windows 8.1 64 bits) and Linux ( Arch Linux x64_86 ). Both running the latest published version ( 0.8.17).

What else can I do in order to give you a more meaningful report?

**Comment by soren121** [comment]
I'd just like to add that custom stickers (i.e. WebP images, not from a sticker pack) also disappear.

**Comment by halcion** [comment]
how

**Comment by joshery420** [comment]
You have to re-add them manually from my experience.
Same problem here, 0.8.17 and Win 8.1 x64

**Comment by alferpal** [comment]
Ueah, you have to add them again each time they get lost for whatever the reason is

**Comment by Katzen-Gott** [comment]
@alferpal , please re-check on v.0.8.19. Release notes say it should be fixed. And could you please close the issue if it's actually fixed?

**Comment by auchri** [comment]
Fixed released with 0.8.21. Please close the issue if it's fixed.

**Comment by alferpal** [comment]
Seems fixed with 0.8.21.

**Comment by Mindstormer619** [comment]
i'm still facing this issue with 0.8.21. I tried closing and restarting, logging out and in... nothing works. Only about half the packs I use are loading. Please reopen the issue.

**Comment by alferpal** [comment]
Theory: If they were added pre-0.8.19-21 maybe they could still get lost. Added post installing 0.8.21 could fix that. As said, just my 0.02€

Could you please verify this?

**Comment by Mindstormer619** [comment]
Cool, I'll try that. I'll make a list of them on the Android client and then send it to myself. Will remove all the packs from both and then readd manually. Will post once done.

**Comment by Mindstormer619** [comment]
Oh god I found it. **There's a limit on the number of sticker packs that can be added on Telegram Desktop**,

I removed all my stickers from both the Android and Desktop clients after saving a list of URLs for them. Then I logged out and exited both clients. I fired up Desktop first, logged in and then proceeded to add the packs one by one. I got this soon:

![image](https://cloud.githubusercontent.com/assets/441849/7980937/2d1ece26-0ac9-11e5-84ba-671b348e980e.png)

I tried with ALL the remaining packs I had not added yet and got the same message. Then I tried *removing* one of the packs at random and then clicked the URL. **The pack was added normally**.

Upon trying with the next URL, I got the same error message. This time I tried removing *two* packs and adding from the URLs. I was able to add two others, no more.

This points to the simple fact that there's a total limit on the **number of packs** you can add to TDesktop. Note that this is not affected by the number of stickers INSIDE the pack. You can add one pack of 100 stickers or 1 pack of 10 stickers: it means the same thing.

Please **reopen this issue**. Also, I think this problem warrants its own issue, which I guess I'll open shortly.

**Comment by Mindstormer619** [comment]
For me, this above limit seems to be **22 packs** (including the default Great Minds one). Please contribute if you are not facing this issue or are seeing a different number of packs.

**Comment by Mindstormer619** [comment]
@alferpal I cannot reopen an issue I did not make. Only you and the repository owners can do so.

**Comment by auchri** [comment]
Create a new issue, it's a different one

**Comment by Mindstormer619** [comment]
@auchri I'm fairly sure this issue is related anyway, but even so, I'll make a new one.
