### ISSUE TITLE
Audio transmission is completely broken

### ISSUE THREAD

**Issue by 0xCA** [telegramdesktop/tdesktop#8443]
### Steps to reproduce
1. Receive or initiate a call
2. Video is working normally
3. Audio is silent for both sides

### Expected behaviour
Both parties hear each other

### Actual behaviour
No sound for both sides

### Configuration
**Operating system:**
Tested on three PCs: Windows 10, two on 1909, one on 2004
**Version of Telegram Desktop:**
2.3
**Used theme**:
null (theme name)

### Details
I called my PC (1) to\from two different phones with TG Android 7.0.0 and from PC 3 with TD 2.3. In all the cases I had no sound for both sides. Complete silence.
I also tried calling from PC 3 with old TDesktop, I could hear it, but they couldn't.
PC2: tried with phones only, no sound both sides.
PC3: complete silence with PC1 (both 2.3). Unexpected: PC3 was working both sides with both phone 1 and 2.

**Comment by casa98** [comment]
I also Tested with Telegram (v7.0) in iPhone (SE v1) and Windows 7. Got exactly what you got, no sound from none of the sides

**Comment by skoglar** [comment]
This is happening on Linux too (v2.3) (on ArchLinux x86_64 on Kernel 5.7.12)

**Comment by iFA88** [comment]
Greetings!

I just downloaded the latest (2.3) version of the Telegram, but I can not make any calls because there is no in/out audio on the app since version ~1.9 .

I just got these lines when I try microphone test:
```
error: : cannot open
error: : cannot open
error: : cannot open
E/tgvoip: Error connecting to audio device ''
W/tgvoip: PulseAudio available but not working; trying ALSA
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM 
QTextCursor::setPosition: Position '-1' out of range
```

Audacity works fine with ALSA (I can record and play).
Teamspeak works fine with PulseAudio.

`Linux IFAPC 4.19.0-0.bpo.6-amd64 #1 SMP Debian 4.19.67-2+deb10u2~bpo9+1 (2019-11-12) x86_64 GNU/Linux`

**Comment by ilya-fedin** [comment]
> I just got these lines when I try microphone test

Microphone test is broken, don't trust it. #7296

**Comment by iFA88** [comment]
> > I just got these lines when I try microphone test
> 
> Microphone test is broken, don't trust it. #7296

Oh, I have tested again, a complete reinstall has solved my problem.

**Comment by ilya-fedin** [comment]
Maybe you had set a non-existing device in settings ¯\_(ツ)_/¯

**Comment by Aokromes** [comment]
i tried to call from android 10 (LOSQ) and telegram android 7 build 2064 to windows 10 (unknown version) and worked for me.

**Comment by metkram** [comment]
> i tried to call from android 10 (LOSQ) and telegram android 7 build 2064 to windows 10 (unknown version) and worked for me.

I tried to reinstall but it doesn't help (as I describe it here https://github.com/telegramdesktop/tdesktop/issues/8511)

2.2 version works well

**Comment by Deilan** [comment]
I also confirm that 2.3.0 and 2.3.1 breaks audio transmission in both directions, video transmission works though.

The only workaround is to revert back to 2.2.0.

**Comment by 0xCA** [comment]
Updating to Win10 2004 fixes this, anything with 1909 remains silent.

**Comment by semihsmg** [comment]
Using Windows 10 2004 version and Telegram Desktop 2.3.1 but when calling from either from PC or Android 10 phone the call is complete silent... Reinstalling Telegram on PC didn't worked and tried different input/output devices in call settings.

**Comment by metkram** [comment]
I have updated windows to 2004 and "silent issue" is still here

**Comment by zaid894** [comment]
I have the same problem and not sure how to solve it, waiting for update to solve it

**Comment by 0xCA** [comment]
So far I "fixed" TD on 3 PCs by upgrading them to 2004.

**Comment by 0xCA** [comment]
I found out some interesting thing about non-working microphone. By default it's set to 2ch 24bit 192kHz by Windows. TDesktop can't work with it. The limit is 96kHz. Once I set it to 96kHz or lower (16 or 24 bits), it started working. Note for "Call Settings" screen: after any adjust in system settings, change your input device selection to something else and back to see if it's working.

**Comment by semihsmg** [comment]
> 
> 
> I found out some interesting thing about non-working microphone. By default it's set to 2ch 24bit 192kHz by Windows. TDesktop can't work with it. The limit is 96kHz. Once I set it to 96kHz or lower (16 or 24 bits), it started working. Note for "Call Settings" screen: after any adjust in system settings, change your input device selection to something else and back to see if it's working.

As I found out my mic can't reach above 1 channel, 16 bit, 48kHz but I changed speakers settings to 24bits, 96kHz it started working... For me the issue is solved. Thank you 0xCA

**Comment by 0xCA** [comment]
> 
> As I found out my mic can't reach above 16 bit, 48kHz but I changed speakers settings to 24bits, 96kHz. Then restarted TDesktop and now calls working as intended...
> For me the issue is solved. Thank you 0xCA

You're absolutely right. I think we actually found it. Output is limited at 96 kHz **as well**. They both have to not exceed the limit.
Updating to 2004 made that thing: it reset everything to lowest possible bitrate and that was the true reason why it was "fixed".

**Comment by ilya-fedin** [comment]
Looks like the library just doesn't support frequency higher than 96KHz

**Comment by metkram** [comment]
> I found out some interesting thing about non-working microphone. By default it's set to 2ch 24bit 192kHz by Windows. TDesktop can't work with it. The limit is 96kHz. Once I set it to 96kHz or lower (16 or 24 bits), it started working. Note for "Call Settings" screen: after any adjust in system settings, change your input device selection to something else and back to see if it's working.

you're man. Thanks, now it works

**Comment by Aokromes** [comment]
to the ones still having problems, can you try the last post of:
https://www.tenforums.com/sound-audio/148115-how-do-i-reset-sound-settings-windows-10-a.html

**Comment by zaid894** [comment]
it's not supporting my microphone array, a single channel microphone works while the defaults microphone of my laptop isn't supported by the used library

**Comment by ilya-fedin** [comment]
There is no sense to use microphone array since mono audio stream is used anyway

**Comment by zaid894** [comment]
it's pre-installed in my asus laptop already and I have to connect an external microphone to solve the problem

**Comment by ilya-fedin** [comment]
> it's pre-installed in my asus laptop already

Why there is no compatibility layer for applications that support only classic microphones then?

**Comment by zaid894** [comment]
The only app that doesn't work is telegram desktop,  there must be something wrong in the library

**Comment by ilya-fedin** [comment]
> The only app that doesn't work is telegram desktop, there must be something wrong in the library

are you talking about calls or voice messages? Calls are using google's webrtc, chrome should have the same issues with web apps for calls. Voice messages are using openal and... I can't remember any app that uses openal on Windows.

**Comment by metkram** [comment]
> > The only app that doesn't work is telegram desktop, there must be something wrong in the library
> 
> Are you talking about calls or voice messages? Calls are using google's webrtc library, chrome should have the same issues with web apps for calls. Voice messages are using openal and... I can't remember any other app that uses openal on Windows.

I had no issues with google hangouts

**Comment by ilya-fedin** [comment]
> I had no issues with google hangouts

Oh, looks like they are using their own internal audio methods for webrtc (why am I not surprised 🙄)

**Comment by Aokromes** [comment]
again, the ones still having problems, can you try the last post of:
tenforums.com/sound-audio/148115-how-do-i-reset-sound-settings-windows-10-a.html

**Comment by zaid894** [comment]
I am talking about the calls only , vioce messages works perfectly and I already tried resetting widows sounds

**Comment by x-tropic** [comment]
same problem! I have an external USB audio interface and an external USB microphone. Voicemail works well both ways. But when I call, I do not hear my interlocutor, while he hears me normally.
Other applications do not have this problem.
Can I tell the program the output device for the call?

Mac OS 10.14.6
Telegram 7.0.1 (205092) Beta

**Comment by x-tropic** [comment]
2.2.0 works fine for me. (without video calls)

**Comment by metkram** [comment]
> same problem! I have an external USB audio interface and an external USB microphone. Voicemail works well both ways. But when I call, I do not hear my interlocutor, while he hears me normally.
> Other applications do not have this problem.
> Can I tell the program the output device for the call?
> 
> Mac OS 10.14.6
> Telegram 7.0.1 (205092) Beta

try this out https://github.com/telegramdesktop/tdesktop/issues/8443#issuecomment-691675354

in most cases it helps

**Comment by Aokromes** [comment]
> same problem! I have an external USB audio interface and an external USB microphone. Voicemail works well both ways. But when I call, I do not hear my interlocutor, while he hears me normally.
> Other applications do not have this problem.
> Can I tell the program the output device for the call?
> 
> Mac OS 10.14.6
> Telegram 7.0.1 (205092) Beta

you don't use telegram desktop (telegram lite on macos) instead telegram for macos.

**Comment by x-tropic** [comment]
> you don't use telegram desktop (telegram lite on macos) instead telegram for macos.

I have already installed version 2.3.1.
will test.

**Comment by x-tropic** [comment]
I guess what the problem is. In the system settings, audio-midi is 32-bit depth 44100. I cannot change this parameter, most likely telegram limits support to 24 bits?

**Comment by metkram** [comment]
> I guess what the problem is. In the system settings, audio-midi is 32-bit depth 44100. I cannot change this parameter, most likely telegram limits support to 24 bits?

it depends what external audio interface do you use
in my case (focusrite), I decreased it in the ASIO control panel

**Comment by x-tropic** [comment]
> > I guess what the problem is. In the system settings, audio-midi is 32-bit depth 44100. I cannot change this parameter, most likely telegram limits support to 24 bits?
> 
> it depends what external audio interface do you use
> in my case (focusrite), I decreased it in the ASIO control panel

I have a rme babyface. If I find an opportunity to change this setting to mac os, then I will write here about the result.

**Comment by metkram** [comment]
> > > I guess what the problem is. In the system settings, audio-midi is 32-bit depth 44100. I cannot change this parameter, most likely telegram limits support to 24 bits?
> > 
> > 
> > it depends what external audio interface do you use
> > in my case (focusrite), I decreased it in the ASIO control panel
> 
> I have a rme babyface. If I find an opportunity to change this setting to mac os, then I will write here about the result.

maybe it'll help https://www.rme-audio.de/downloads/bface_pro_e.pdf

**Comment by Deilan** [comment]
> I found out some interesting thing about non-working microphone. By default it's set to 2ch 24bit 192kHz by Windows. TDesktop can't work with it. The limit is 96kHz. Once I set it to 96kHz or lower (16 or 24 bits), it started working. Note for "Call Settings" screen: after any adjust in system settings, change your input device selection to something else and back to see if it's working.

In my case both input (Playback) and output (Recording) are both limited by 16 bit, 48 kHz. But the issue is still present anyway.

**Comment by ilya-fedin** [comment]
webrtc :+1: /s

**Comment by ilya-fedin** [comment]
> I guess what the problem is. In the system settings, audio-midi is 32-bit depth 44100. I cannot change this parameter, most likely telegram limits support to 24 bits?

Enable debug logs by entering `debugmode` in settings like a cheat code, make a call and check `last_call_log.txt` in `DebugLogs` folder of your tdesktop profile folder (`%APPDATA\Telegram Desktop` on Windows, `~/.local/share/Telegram Desktop` on generic Linux installs (non-snap, non-flatpak), I don't know where it is on Mac)

**Comment by x-tropic** [comment]
> > I guess what the problem is. In the system settings, audio-midi is 32-bit depth 44100. I cannot change this parameter, most likely telegram limits support to 24 bits?
> 
> Enable debug logs by entering `debugmode` in settings like a cheat code, make a call and check `last_call_log.txt` in `DebugLogs` folder of your tdesktop profile folder (`%APPDATA\Telegram Desktop` on Windows, `~/.local/share/Telegram Desktop` on generic Linux installs (non-snap, non-flatpak), I don't know where it is on Mac)

[last_call_log.txt.zip](https://github.com/telegramdesktop/tdesktop/files/5282063/last_call_log.txt.zip)

**Comment by x-tropic** [comment]
(audio_device_mac.cc:101): Error in AudioConverterFillComplexBuffer(): -1-1-1-50

**Comment by ilya-fedin** [comment]
Seems to be a webrtc bug
https://webrtc.googlesource.com/src/+/refs/heads/master/modules/audio_device/mac/audio_device_mac.cc#2230
https://webrtc.googlesource.com/src/+/refs/heads/master/modules/audio_device/mac/audio_device_mac.cc#2470

I don't know where is their bugtracker though

**Comment by ilya-fedin** [comment]
Looks like I found: http://bugs.webrtc.org/

**Comment by ilya-fedin** [comment]
Oh, i searched their bugtracker and looks like their audio backends for demo purposes only and tdesktop should have its own audio backend for webrtc
https://bugs.chromium.org/p/webrtc/issues/detail?id=10622#c3

**Comment by dtheb** [comment]
I'm having a similar issue https://github.com/telegramdesktop/tdesktop/issues/8648, and was told to move the discussion here.

All sounds work fine but it goes silent for both sides as soon as I make or get a call.

Default device set, telegram call setting set and tested 👇 as you can see here

![Zwmnxeu0pm](https://user-images.githubusercontent.com/6548599/94431014-70451180-019d-11eb-97e4-d4f0428d5473.gif)


### Logs: 
```log
[2020.09.28 12:56:14] Launched version: 2003001, install beta: [FALSE], alpha: 0, debug mode: [FALSE]
[2020.09.28 12:56:14] Executable dir: D:/Telegram/, name: Telegram.exe
[2020.09.28 12:56:14] Initial working dir: D:/Telegram/
[2020.09.28 12:56:14] Working dir: D:/Telegram/
[2020.09.28 12:56:14] Command line: D:\Telegram\Telegram.exe
[2020.09.28 12:56:14] Executable path before check: D:/Telegram/Telegram.exe
[2020.09.28 12:56:14] Logs started
[2020.09.28 12:56:14] Connecting local socket to Global\c2764e6f12b4016e432fe963325d797e-{87A94AB0-E370-4cde-98D3-ACC110C5967D}...
[2020.09.28 12:56:14] This is the only instance of Telegram, starting server and app...
[2020.09.28 12:56:14] Moved logging from 'D:/Telegram/log_start0.txt' to 'D:/Telegram/log.txt'!
[2020.09.28 12:56:14] Primary screen DPI: 96
[2020.09.28 12:56:14] Font: from ':/gui/fonts/DAOpenSansRegular.ttf' loaded 'DAOpenSansRegular'
[2020.09.28 12:56:14] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
[2020.09.28 12:56:14] Font: from ':/gui/fonts/DAOpenSansRegularItalic.ttf' loaded 'DAOpenSansRegularItalic'
[2020.09.28 12:56:14] Font: from ':/gui/fonts/DAVazirRegular.ttf' loaded 'DAVazirRegular'
[2020.09.28 12:56:14] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
[2020.09.28 12:56:14] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2020.09.28 12:56:14] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
[2020.09.28 12:56:14] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2020.09.28 12:56:14] Font: from ':/gui/fonts/DAOpenSansSemiboldAsBold.ttf' loaded 'DAOpenSansSemibold'
[2020.09.28 12:56:14] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2020.09.28 12:56:14] Font: from ':/gui/fonts/DAOpenSansSemiboldItalicAsBold.ttf' loaded 'DAOpenSansSemiboldItalic'
[2020.09.28 12:56:15] Font: from ':/gui/fonts/DAVazirMediumAsBold.ttf' loaded 'DAVazirMedium'
[2020.09.28 12:56:15] App Info: reading settings...
[2020.09.28 12:56:15] App Info: reading encrypted settings...
[2020.09.28 12:56:15] Lang Info: Loaded cached, keys: 2723
[2020.09.28 12:56:15] OpenAL Logging Level: (not set)
[2020.09.28 12:56:15] Audio Playback Devices: OpenAL Soft on Speakers (2- Sound BlasterX G6);OpenAL Soft on VoiceMeeter Aux Input (VB-Audio VoiceMeeter AUX VAIO);OpenAL Soft on VoiceMeeter Input (VB-Audio VoiceMeeter VAIO)
[2020.09.28 12:56:15] Audio Playback Default Device: OpenAL Soft on Speakers (2- Sound BlasterX G6)
[2020.09.28 12:56:15] Audio Capture Devices: OpenAL Soft on External Mic (2- Sound BlasterX G6)
[2020.09.28 12:56:15] Audio Capture Default Device: OpenAL Soft on External Mic (2- Sound BlasterX G6)
[2020.09.28 12:56:15] App Info: reading accounts info...
[2020.09.28 12:56:15] App Info: reading encrypted info...
[2020.09.28 12:56:15] App Info: reading map...
[2020.09.28 12:56:15] App Info: reading encrypted map...
[2020.09.28 12:56:15] App Info: reading encrypted user settings...
[2020.09.28 12:56:15] App Info: encrypted user settings read.
[2020.09.28 12:56:15] App Info: reading encrypted mtp data...
[2020.09.28 12:56:15] MTP Info: read keys, current: 4, to destroy: 0
[2020.09.28 12:56:15] Map read time: 0
[2020.09.28 12:56:15] App Info: reading encrypted mtp config...
[2020.09.28 12:56:15] Export Info: Destroy top bar by controller removal.
[2020.09.28 12:56:16] Message Info: bad message notification received (error_code 33) for msg_id = 6877475191079621176, seq_no = 36
[2020.09.28 12:56:16] Message Info: bad message notification received, msgId 6877475191079621176, error_code 33
[2020.09.28 12:56:36] Error: could not locate 'background.jpg' in a zip file.
[2020.09.28 13:04:35] API Warning: emoji 🇹🇦 is not supported, word: flag.
[2020.09.28 13:04:35] API Warning: emoji 🇩🇬 is not supported, word: flag.
[2020.09.28 13:04:35] API Warning: emoji 🇦🇨 is not supported, word: flag.
[2020.09.28 13:04:35] API Warning: emoji 🇪🇦 is not supported, word: flag.
[2020.09.28 13:04:35] API Warning: emoji 🇲🇫 is not supported, word: flag.
[2020.09.28 13:04:35] API Warning: emoji 🇹🇦 is not supported, word: flag.
[2020.09.28 13:04:35] API Warning: emoji 🇩🇬 is not supported, word: flag.
[2020.09.28 13:04:35] API Warning: emoji 🇦🇨 is not supported, word: flag.
[2020.09.28 13:04:35] API Warning: emoji 🇪🇦 is not supported, word: flag.
[2020.09.28 13:04:35] API Warning: emoji 🇲🇫 is not supported, word: flag.
[2020.09.28 13:04:35] API Warning: emoji 🇩🇬 is not supported, word: diego garcia.
[2020.09.28 13:04:35] API Warning: emoji 🧑‍🤝‍🧑 is not supported, word: bf.
[2020.09.28 13:04:35] API Warning: emoji 🇹🇦 is not supported, word: ta.
[2020.09.28 13:04:35] API Warning: emoji 🇦🇨 is not supported, word: ascension island.
[2020.09.28 13:04:35] API Warning: emoji 🇦🇨 is not supported, word: ac.
[2020.09.28 13:04:35] API Warning: emoji 🇦🇨 is not supported, word: flag_ac.
[2020.09.28 13:04:35] API Warning: emoji 🇹🇦 is not supported, word: tristan da cunha.
[2020.09.28 13:04:35] API Warning: emoji 🇩🇬 is not supported, word: british indian ocean territory.
[2020.09.28 13:04:35] API Warning: emoji 🇹🇦 is not supported, word: flag_ta.
[2020.09.28 13:04:35] API Warning: emoji 🇲🇫 is not supported, word: st. martin.
[2020.09.28 13:04:35] API Warning: emoji 🇪🇦 is not supported, word: ceuta & melilla.
[2020.09.28 13:04:35] API Warning: emoji 🇹🇦 is not supported, word: علم.
[2020.09.28 13:04:35] API Warning: emoji 🇲🇫 is not supported, word: علم.
[2020.09.28 13:04:35] API Warning: emoji 🇦🇨 is not supported, word: علم.
[2020.09.28 13:04:35] API Warning: emoji 🇪🇦 is not supported, word: علم.
[2020.09.28 13:04:35] API Warning: emoji 🇩🇬 is not supported, word: علم.
[2020.09.28 13:04:35] API Warning: emoji 🇹🇦 is not supported, word: علم.
[2020.09.28 13:04:35] API Warning: emoji 🇲🇫 is not supported, word: علم.
[2020.09.28 13:04:35] API Warning: emoji 🇦🇨 is not supported, word: علم.
[2020.09.28 13:04:35] API Warning: emoji 🇪🇦 is not supported, word: علم.
[2020.09.28 13:04:35] API Warning: emoji 🇩🇬 is not supported, word: علم.
[2020.09.28 13:04:35] API Warning: emoji 🇦🇨 is not supported, word: أسينشين.
[2020.09.28 13:04:35] API Warning: emoji 🇹🇦 is not supported, word: تريستان دا كونا.
[2020.09.28 13:04:35] API Warning: emoji 🇩🇬 is not supported, word: دييغو غارسيا.
[2020.09.28 13:04:35] API Warning: emoji 🇪🇦 is not supported, word: سبتة ومليلية.
[2020.09.28 13:04:35] API Warning: emoji 🇦🇨 is not supported, word: جزيرة أسينشين.
[2020.09.28 13:04:35] API Warning: emoji 🇪🇦 is not supported, word: مليلية.
[2020.09.28 13:04:35] API Warning: emoji 🇪🇦 is not supported, word: سبتة.
[2020.09.28 13:04:35] API Warning: emoji 🇲🇫 is not supported, word: سانت مارتن.
[2020.09.28 13:06:37] Audio Info: recreating audio device and reattaching the tracks
[2020.09.28 13:06:39] Audio Info: Closing audio playback device.
[2020.09.28 13:06:50] Audio Info: recreating audio device and reattaching the tracks
[2020.09.28 13:06:52] Message Info: bad message notification received (error_code 33) for msg_id = 6877477922251037772, seq_no = 136
[2020.09.28 13:06:52] Message Info: bad message notification received, msgId 6877477922251037772, error_code 33
[2020.09.28 13:06:52] Audio Info: Closing audio playback device.
[2020.09.28 13:06:52] Audio Info: recreating audio device and reattaching the tracks
[2020.09.28 13:06:56] Audio Info: Closing audio playback device.
[2020.09.28 13:07:17] Message Info: bad message notification received (error_code 33) for msg_id = 6877478029613228004, seq_no = 48
[2020.09.28 13:07:17] Message Info: bad message notification received, msgId 6877478029613228004, error_code 33
[2020.09.28 13:07:23] App Info: writing encrypted user settings...
[2020.09.28 13:07:23] Message Info: bad message notification received (error_code 33) for msg_id = 6877478055412725288, seq_no = 40
[2020.09.28 13:07:23] Message Info: bad message notification received, msgId 6877478055412725288, error_code 33
[2020.09.28 13:40:52] Audio Info: recreating audio device and reattaching the tracks
[2020.09.28 13:40:54] Audio Info: Closing audio playback device.
[2020.09.28 13:41:03] Audio Info: recreating audio device and reattaching the tracks
[2020.09.28 13:41:17] Call Info: Creating instance with version '2.7.7', allowP2P: [TRUE]
[2020.09.28 13:41:18] Call Error: Unexpected state in handleStateChange: 4
[2020.09.28 13:41:19] Audio Info: Closing audio playback device.
[2020.09.28 13:41:32] Audio Info: recreating audio device and reattaching the tracks
[2020.09.28 13:41:33] Audio Info: Closing audio playback device.
[2020.09.28 13:43:42] Audio Info: recreating audio device and reattaching the tracks
[2020.09.28 13:43:44] Audio Info: Closing audio playback device.
[2020.09.28 13:43:45] Audio Info: recreating audio device and reattaching the tracks
[2020.09.28 13:43:47] Audio Info: Closing audio playback device.
```

**Comment by iocomxda** [comment]
Do the devs know that this issue exist? Have they stated something about it?

**Comment by zaid894** [comment]
The issue is still there I hope it's solved soon

**Comment by iocomxda** [comment]
> 
> 
> The issue is still there I hope it's solved soon

Yes, i currently switched to Discord because of this problem. Unbelievable.

**Comment by TEXHIK** [comment]
v2.4.7 on win 10 still not working

**Comment by Nawoth-Th** [comment]
How to fix this bug ?

**Comment by zaid894** [comment]
> How to fix this bug ?

sadly it's not fixable yet

**Comment by amon** [comment]
I'm experiencing the same issue on 2.4.7 / w10.

**Comment by jeverduzco** [comment]
I'm experiencing the same issue on 2.4.7 / W10 20H2. The voice messages work well but the microphone doesn't work in the calls.

**Comment by zaid894** [comment]
Still not solved

**Comment by MarouaneMan** [comment]
Same here

**Comment by MarouaneMan** [comment]
is someone actually working on this ?

**Comment by ilya-fedin** [comment]
> is someone actually working on this ?

AFAIK, no

**Comment by MarouaneMan** [comment]
Reverted back to 2.2.0, working as expected !

**Comment by iocomxda** [comment]
> 
> 
> Reverted back to 2.2.0, working as expected !

How did you solve? I tried to download 2.2.0 but it doesn't have the videocall option (as it's outdated).

**Comment by MarouaneMan** [comment]
> > Reverted back to 2.2.0, working as expected !
> 
> How did you solve? I tried to download 2.2.0 but it doesn't have the videocall option (as it's outdated).

I had the problem with voice only calls, i'm not using video, reverting to 2.2.0 was suffisent to fix it.

**Comment by Hvalfisk** [comment]
Changing device configuration from 7.1 to stereo fixed it

**Comment by john-preston** [comment]
Is it ok in 2.5.2 beta?

**Comment by zaid894** [comment]
NOW IT'S FIXED WITH AN UPDATE 💃💃

**Comment by iocomxda** [comment]
IT IS FIXED IN 2.5.2 BETA! https://github.com/telegramdesktop/tdesktop/releases/tag/v2.5.2
