### ISSUE TITLE
Xubuntu 14.04 - tray icon is missing

### ISSUE THREAD

**Issue by Arandhras** [telegramdesktop/tdesktop#952]
Hi, on my desktop computer running Xubuntu 14.04 64 bit I have just upgraded to Telegram 0.8.43 from a previous stable version... and unlike before, now I can't correctly see the program's tray icon anymore. I have tried everything, including removing the ~/.TelegramDesktop directory and redownloading and reinstalling the program entirely, but I still get this bug. On another computer that is running Debian 8 i686 with XFCE I don't have this issue at all.

What could it be? And how can it be fixed?
Thank you lots for the attention.

![telegram](https://cloud.githubusercontent.com/assets/7527086/9025830/fe5d0b44-3916-11e5-9f15-51518d076ea9.png)

Update: the same behavior happens on my laptop which is also running Xubuntu 14.04 64 bit.

**Comment by Arandhras** [comment]
Update: the same behavior happens on my laptop which is also running Xubuntu 14.04 64 bit.

**Comment by completit** [comment]
+1 I've also got this issue since update (v 0.8.43 stable 31.07.15)[https://desktop.telegram.org/#v-0-8-43-stable-31-07-15]

**Comment by telegramdesktop** [comment]
I use Qt 5.5 tray icon there, I don't know why some of Linux builds running xfce display it correctly and some don't :( Manjaro XFCE displays it right, for example. The previous version was based on Qt 5.4 and it seems they broke something from 5.4 to 5.5.

**Comment by auchri** [comment]
@Arandhras try https://launchpad.net/sni-qt

**Comment by telegramdesktop** [comment]
I'll fix that in 0.8.45 stable version, trying to use libappindicator first, and QSystemTrayIcon from Qt 5.5 only if that attempt failed. This gives the required behaviour in Manjaro XFCE and Xubuntu for me.

**Comment by Arandhras** [comment]
Thank you a lot @telegramdesktop !

**Comment by auchri** [comment]
Fixed with 0.8.45 @Arandhras ?

**Comment by Arandhras** [comment]
Yup it's fixed! Thank you everyone! :+1:

**Comment by completit** [comment]
Thank you very much for the hotfix :+1:

**Comment by telegramdesktop** [comment]
Should be fine.

**Comment by David-Estevez** [comment]
This issue still persists in Linux Mint 17.1 64bit with XFCE4 desktop and Telegram 0.8.48

![screenshot - 08092015 - 01 40 08 am](https://cloud.githubusercontent.com/assets/1451819/9152930/4670818c-3e3e-11e5-8cdc-f3dcd24b2a9c.png)

Any clue about what can I do to solve it?

**Comment by auchri** [comment]
do you have libappindicator installed?

**Comment by David-Estevez** [comment]
Yes, I tried installing libappindicator, but nothing happened.

I'll attach a screenshot of the packages currently installed just in case the required one is a different one from the ones that I installed.

![screenshot - 08092015 - 02 37 30 am](https://cloud.githubusercontent.com/assets/1451819/9152970/aa10b4d6-3e3f-11e5-9bfa-3829074c4a94.png)

**Comment by David-Estevez** [comment]
Any clue about how to solve this, @auchri ?

**Comment by neformatoz** [comment]
Today upgrade  0.9.24, icon is missing.. so sad.

**Comment by DaFri-Nochiterov** [comment]
And after {someUpdateVersion} missed integration with cinnamon panel menu, sadly, now it Windows98-style context menu :(

**Comment by john-preston** [comment]
@neformatoz which version misses the icon?

@DaFri-Nochiterov enabling Qt styling using gtk was breaking Xubuntu 15.10 completely.

**Comment by DaFri-Nochiterov** [comment]
@john-preston also, if we try to load TDesktop with argument `--style=gtk` and open file manager with "Attach file" button, our Linux falls :fearful:
Ubuntu 15.10 Cinnamon DE

**Comment by neformatoz** [comment]
@john-preston sorry, my fault.. checked again, everything works, my indicator plugin had been crashing
